name = "parquet-fortran"
version = "VERSION.txt"
license = "BSD-3-Clause"
author = "Elmo Tempel"
maintainer = "elmo.tempel@ut.ee"
copyright = "Copyright 2026, Elmo Tempel"
description = "Parquet Fortran is a Fortran library for reading and writing Parquet files."
homepage = "https://github.com/etempel/parquet-fortran"
keywords = ["parquet", "arrow", "io", "columnar", "maml", "data"]
categories = ["io"]

[[executable]]
name = "run_parquet_fortran"
source-dir = "app"
main = "program.f90"

[dependencies]
openmp = "*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["arrow", "arrow_compute", "parquet"]

[install]
library = false
test = false

[preprocess]
[preprocess.cpp]
suffixes = ["f90"]
macros=["RELEASE_VERSION={version}"]

[extra.ford]
project = "parquet-fortran"
summary = "Fortran library for reading and writing Parquet files"
src_dir = ["./src"]
exclude_dir = ["./test"]
exclude = ["**/parquet_bindings.f90"]
page_dir = "./doc/pages"
output_dir = "./ford-doc"
media_dir = "./doc/media"
favicon = "./doc/media/favicon.png"
css = "./doc/user.css"
display = ["public", "protected"]
source = true
graph = true
search = true
preprocessor = "cpp -traditional-cpp -E"
md_extensions = ["markdown.extensions.toc"]

[extra.ford.extra_mods]
iso_fortran_env = "https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fFORTRAN_005fENV.html"
iso_c_binding = "https://gcc.gnu.org/onlinedocs/gfortran/ISO_005fC_005fBINDING.html"
