name = "parquet-fortran"
version = "VERSION.txt"
license = "BSD-3-Clause"
author = "Elmo Tempel"
maintainer = "elmo.tempel@ut.ee"
copyright = "Copyright 2026, Elmo Tempel"
description = "Parquet Fortran is a Fortran library for reading and writing Parquet files."

[[executable]]
name = "run_parquet_fortran"
source-dir = "app"
main = "program.f90"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"

openmp = "*"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["arrow", "parquet", "c++"]

[install]
library = false
test = false

[preprocess]
[preprocess.cpp]
suffixes = ["f90"]
macros=["RELEASE_VERSION={version}"]
