#!/usr/bin/env bash
#
# check_module_footprints.sh -- assert how much of this library each advertised entry module
# actually drags into a consumer's build.
#
# WHAT THIS MEASURES, AND WHY NOTHING ELSE CAN. fpm prunes at MODULE granularity: a consumer
# compiles a source file only if some module it imports needs it, and a submodule is never pruned
# separately from the module it belongs to. So `use parquet_argsort` in a downstream project
# compiles a specific, knowable set of this library's files -- and one added `use` line anywhere in
# that set can silently double it. `fpm test` cannot see that happen (the library obviously builds
# either way), `tools/check_source_conventions.py`'s Arrow-free checks cannot either (a tier can
# double in size without ever touching parquet_bindings), and no compiler warns. This script is the
# only instrument that answers "how big did the graph get".
#
# It is the size counterpart of check_parquet_argsort_stays_arrow_free and friends, which answer a
# different question -- "does the graph reach the Arrow stack" -- and the two catch different
# regressions. Keep both.
#
# HOW IT WORKS. For each entry module it writes a throwaway consumer project into a temporary
# directory, points it at this repository through a relative symlink (fpm 0.13.0 alpha rejects an
# absolute `path =` dependency), builds it COLD, and lists the library files fpm actually compiled
# -- by reading the OBJECT FILES the build produced, never fpm's progress output, which truncates
# a long filename and so drops it silently (see measure_module).
# The result is compared against tools/module_footprints.txt, which is committed.
#
# A final SELF-CHECK then asserts that the [parquet] measurement accounts for every src/*.f90 bar
# a named exclusion list. Comparing a measurement against an expectation generated by the same
# code cannot detect a measurement that has stopped seeing files -- both sides move together and
# every section still reports [ok] -- so that self-check is the only thing here that can.
#
# WHEN IT FAILS, THE FIX IS ALMOST NEVER TO UPDATE THE EXPECTATION. A module that grew did so
# because something it imports gained a dependency; move whatever needed that import UP a tier
# instead, exactly as the Arrow-free checks' headers say. Update the expectation only when the
# growth is the deliberate, reviewed point of the change -- and say so in the commit message,
# because a silently-updated expectation is a check that has been switched off.
#
# USAGE
#   tools/check_module_footprints.sh                 check every entry module
#   tools/check_module_footprints.sh parquet_argsort check one
#   tools/check_module_footprints.sh --print         print the current footprints in the
#                                                    expectation file's own format, for review
#
# This is slow by construction -- each module is a cold build of its whole subtree -- so it is a
# maintainer command, not part of tools/run_lint_check.sh or CI's lint stage.
#
# bash 3.2 only (macOS ships 3.2 and this is run by hand there): no associative arrays, no
# mapfile, no ${var,,}. See `.claude/rules/testing.md`, "`tools/*.sh` checks".
# ---------------------------------------------------------------------------------------------
# Answers the adjacent question -- not does an entry module's
# graph reach Arrow, but how big did it get. For each advertised entry module -- the rows of
# Choosing a module (doc/pages/operating/choosing-a-module.md)'s table, which is the authority for
# that list -- it writes a throwaway consumer project into a temporary directory, points it at this
# repository through a relative symlink (fpm 0.13.0 alpha rejects an absolute `path =` dependency),
# builds it cold, and compares the library files fpm actually compiled against
# `tools/module_footprints.txt`, which is committed. It reads the object files the build produced
# rather than fpm's progress output, which right-aligns a filename in a 30-character column and
# truncates anything longer -- a defect that silently dropped one source file from two sections for
# as long as the script existed, invisibly, because the expectation file had been generated by the
# same lossy grep and so agreed with it. A final self-check guards against exactly that recurring:
# it asserts the `[parquet]` footprint accounts for every `src/.f90` bar a named exclusion list,
# which is the one thing comparing a measurement against a same-code expectation can never do. fpm
# prunes at *module granularity and never prunes a submodule separately from its module, so one
# added `use` line can multiply what a downstream project compiles -- a tier can double in size
# without ever touching `parquet_bindings`, which is exactly what the Arrow-free checks cannot see.
# When it fails, the fix is almost never to update the expectation: a module that grew did so
# because something it imports gained a dependency, and the right answer is to move whatever needed
# that import up a tier. Update `tools/module_footprints.txt` only when the growth is the
# deliberate, reviewed point of the change, and say so in the commit message -- a silently-updated
# expectation is a check that has been switched off. Deliberately not in CI: each module is a cold
# build of its whole subtree, including `src/parquet_wrapper.cpp` every time, so it is minutes
# rather than the seconds the checks above take. Maintainer-only.
#
#     tools/check_module_footprints.sh                  # every entry module
#     tools/check_module_footprints.sh parquet_argsort  # just one
#     tools/check_module_footprints.sh --print          # current footprints, in the expectation file's format
# ---------------------------------------------------------------------------------------------

set -u

finished=0
work=""
cleanup() {
    if [ -n "$work" ] && [ -d "$work" ]; then rm -rf "$work"; fi
    if [ "$finished" != "1" ]; then
        echo "check_module_footprints.sh: TERMINATED EARLY -- this run proves nothing" >&2
        exit 2
    fi
}
trap cleanup EXIT

repo="$(cd "$(dirname "$0")/.." && pwd)"
expect_file="$repo/tools/module_footprints.txt"

# The advertised entry modules, in tier order: the Arrow-free tiers first, then the four whose
# Fortran graph reaches parquet_bindings by design. Adding one here without adding its section to
# tools/module_footprints.txt is a hard failure, which is the intent.
#
# THIS LIST MUST MATCH THE TABLE IN doc/pages/operating/choosing-a-module.md, which is the single
# authority for what an advertised entry module is. It did not, for a long time and in the
# direction that measures nothing: parquet_tables and parquet_settings were both absent, so this
# script answered "'parquet_tables' is not an advertised entry module" to the very name the page,
# CLAUDE.md and CONTRIBUTING.md all use for it, and the number the page printed for it (64, where
# the truth is 62) had never been measured by anything at all.
ENTRY_MODULES="parquet_version parquet_utils parquet_temporal parquet_strings parquet_random parquet_argsort parquet_index \
parquet_sampling parquet_spatial parquet_healpix parquet_sphere parquet_skycoord parquet_columns parquet_list \
parquet_struct parquet_map \
parquet_sorting parquet_stats parquet_kde parquet_integrate parquet_interpolate parquet_cosmology \
parquet_cosmology_config parquet_optimize \
parquet_prima parquet_root \
parquet_transform parquet_logging parquet_toml parquet_settings \
parquet_io parquet_tables parquet"

mode="check"
only=""
if [ $# -gt 0 ]; then
    case "$1" in
        --print) mode="print" ;;
        -h|--help) sed -n '2,40p' "$0"; finished=1; exit 0 ;;
        -*) echo "check_module_footprints.sh: unknown option '$1'" >&2; exit 2 ;;
        *) only="$1" ;;
    esac
fi

if [ ! -f "$expect_file" ] && [ "$mode" = "check" ]; then
    echo "check_module_footprints.sh: missing expectation file $expect_file" >&2
    exit 2
fi

work="$(mktemp -d "${TMPDIR:-/tmp}/pf-footprint.XXXXXX")"
ln -s "$repo" "$work/pf"

# Prints the sorted list of library source files a cold build of `use <module>` compiles.
# The probe's own m.f90 is excluded; src/parquet_wrapper.cpp is NOT -- it is compiled for every
# module because `link` is a package-level key in fpm.toml, and seeing it in every section is the
# reminder that no module makes the PACKAGE Arrow-free.
measure_module() {
    _mod="$1"
    _probe="$work/probe_$_mod"
    rm -rf "$_probe"
    mkdir -p "$_probe/src"
    printf 'name = "probe"\nversion = "0.1.0"\n[dependencies]\nparquet-fortran = { path = "../pf" }\n' \
        > "$_probe/fpm.toml"
    printf 'module m_probe\n    use %s\n    implicit none\nend module m_probe\n' "$_mod" \
        > "$_probe/src/m.f90"
    ( cd "$_probe" && fpm build ) > "$_probe/build.log" 2>&1
    _rc=$?
    if [ "$_rc" -ne 0 ]; then
        echo "check_module_footprints.sh: probe build FAILED for 'use $_mod'" >&2
        tail -n 25 "$_probe/build.log" >&2
        exit 1
    fi
    # READ THE OBJECT FILES, NOT THE BUILD LOG. fpm's progress output right-aligns the filename
    # in a 30-CHARACTER column and TRUNCATES anything longer, so a grep over the log silently
    # loses every source file with a long name. That is not hypothetical: it dropped
    # parquet_maml_base_add_col_qc.f90 (32 characters, and the only name in src/ over 30) from
    # every section that should have held it, understating [parquet_io] and [parquet] by one
    # each -- for as long as this script has existed, invisibly, because the expectation file
    # was generated by the same lossy grep and so agreed with it perfectly. The objects fpm
    # actually produced cannot be truncated and cannot be cached away, which the log can: a log
    # lists only what was compiled THIS run, so a warm build under-reports too.
    #
    # LC_ALL=C, or the ORDER of this list depends on the caller's locale and every section
    # reshuffles: under en_US.UTF-8 collation punctuation is weighted differently, so
    # parquet_settings_base.f90 sorts before parquet_settings.f90 while under C it sorts after.
    # tools/module_footprints.txt was generated under C, and a regeneration from a UTF-8 shell
    # produces a diff touching every section in which the one real change is invisible.
    #
    # The object name carries the dependency's path, so `../pf/src/x.f90` becomes
    # `.._pf_src_x.f90.o`; stripping through the last `src_` recovers the source filename and
    # leaves the probe's own `src_m.f90.o` as plain `m.f90`, which is then dropped.
    #
    # THE `_pf_src_` FILTER RUNS BEFORE THAT STRIP, AND IT IS LOAD-BEARING. This repository's own
    # sources reach the probe through the relative symlink `../pf`, so every one of their objects
    # carries `_pf_src_` in its flattened name; a BUILD DEPENDENCY's sources are fetched into the
    # probe's own `build/dependencies/<name>/` instead and flatten differently, so they do not.
    # Without the filter, `toml-f`'s ~35 files would appear in every section that reaches
    # `parquet_toml` -- and the committed expectation, the guide's Files column and README's would
    # all start counting somebody else's parser. The decision (feature_toml.md section 3) is that
    # this bookkeeping tracks THIS library's own sources; the dependency still compiles, and the
    # guide page says so next to the `parquet_toml` row. Note the filter also drops the probe's own
    # `src_m.f90.o`, which the `grep -v` below then no longer has to catch -- it is kept anyway, so
    # that neither guard alone is silently doing all the work.
    find "$_probe/build" -type f -name '*.o' \
        | sed 's#.*/##' \
        | grep '_pf_src_' \
        | sed 's/^.*src_//; s/\.o$//' \
        | grep -v '^m\.f90$' | LC_ALL=C sort -u
}

# Reads one module's expected file list out of the committed expectation file.
expected_for() {
    awk -v want="[$1]" '
        $0 == want { on = 1; next }
        /^\[/      { on = 0 }
        on && NF   { print }
    ' "$expect_file"
}

status=0
checked=0

for mod in $ENTRY_MODULES; do
    if [ -n "$only" ] && [ "$only" != "$mod" ]; then continue; fi
    got="$work/got_$mod"
    measure_module "$mod" > "$got"
    n=$(grep -c . "$got")

    if [ "$mode" = "print" ]; then
        echo "[$mod]"
        cat "$got"
        echo ""
        checked=$((checked + 1))
        continue
    fi

    want="$work/want_$mod"
    expected_for "$mod" > "$want"
    if [ ! -s "$want" ]; then
        echo "[FAIL] $mod: no [$mod] section in tools/module_footprints.txt" >&2
        status=1
        checked=$((checked + 1))
        continue
    fi

    if diff -u "$want" "$got" > "$work/diff_$mod" 2>&1; then
        echo "[ok]   $mod: $n files"
    else
        echo "[FAIL] $mod: footprint changed ($(grep -c . "$want") expected, $n compiled)" >&2
        sed -n '3,200p' "$work/diff_$mod" >&2
        status=1
    fi
    checked=$((checked + 1))
done

if [ "$checked" -eq 0 ]; then
    echo "check_module_footprints.sh: '$only' is not an advertised entry module" >&2
    exit 2
fi

# ----------------------------------------------------------------------------------------------
# SELF-CHECK: does the measurement still SEE every file it should?
#
# Everything above compares one measurement against one expectation, and both come out of the same
# code -- so a measurement that quietly stops seeing a file agrees with an expectation generated by
# the same defect, and every section reports [ok] while being wrong. That is exactly what happened
# with the truncating build-log grep this script used to have (see measure_module). A check whose
# failure mode is a green report is worse than no check, so this asserts the one thing the
# comparison above cannot: that the [parquet] measurement accounts for every source file in src/.
#
# `use parquet` reaches the whole library by construction, so the facade's footprint must be all of
# src/*.f90 minus a short, DELIBERATE exclusion list. Both directions are checked -- a file missing
# from the measurement, and an exclusion that is no longer excluded -- because an exclusion list
# that has gone stale hides the very gap it was written to explain (CLAUDE.md, "A static check that
# enumerates names goes stale silently").
FACADE_EXCLUDES="parquet_sorting_oracle.f90 parquet_table_example.f90 parquet_cosmology_config.f90"
#
#   parquet_sorting_oracle.f90     the C++ sort engine, reachable only behind
#                                  parquet_sorting_oracle's procedure pointers. TEST-ONLY and
#                                  deliberately re-exported by no facade -- if this one ever
#                                  appears in the [parquet] footprint, the Arrow-free tiers have
#                                  lost the property check_parquet_*_stays_arrow_free exists to
#                                  protect.
#   parquet_table_example.f90      a worked example emitted by tools/generate_user_table_code.py;
#                                  it ships as a demonstration and nothing in the library uses it,
#                                  so no `use parquet` program compiles it.
#   parquet_cosmology_config.f90   the [cosmology] section of a TOML configuration file, over
#                                  parquet_cosmology and parquet_toml. Deliberately re-exported by
#                                  no facade: a caller that wants a cosmology from a configuration
#                                  file names this module, exactly as it already names
#                                  parquet_toml, and `use parquet` stays clear of a pairing only
#                                  some programs want.

if [ "$mode" = "check" ] && [ -z "$only" ]; then
    _got_parquet="$work/got_parquet"
    _missing=""
    for _f in "$repo"/src/*.f90; do
        _b="$(basename "$_f")"
        case " $FACADE_EXCLUDES " in
            *" $_b "*) continue ;;
        esac
        grep -qx "$_b" "$_got_parquet" || _missing="$_missing $_b"
    done
    _stale=""
    for _b in $FACADE_EXCLUDES; do
        if [ ! -f "$repo/src/$_b" ]; then
            _stale="$_stale $_b(gone)"
        elif grep -qx "$_b" "$_got_parquet"; then
            _stale="$_stale $_b(compiled)"
        fi
    done
    if [ -n "$_missing" ]; then
        echo "[FAIL] self-check: the [parquet] measurement does not account for:$_missing" >&2
        echo "       Either \`use parquet\` genuinely no longer reaches them -- in which case add" >&2
        echo "       them to FACADE_EXCLUDES with a reason -- or measure_module has stopped seeing" >&2
        echo "       files, which makes EVERY section above meaningless. Check the second first." >&2
        status=1
    fi
    if [ -n "$_stale" ]; then
        echo "[FAIL] self-check: FACADE_EXCLUDES is stale:$_stale" >&2
        echo "       An entry marked (compiled) is now reached by \`use parquet\` and must be" >&2
        echo "       removed from the list; one marked (gone) names a file that no longer exists." >&2
        status=1
    fi
    if [ -z "$_missing" ] && [ -z "$_stale" ]; then
        echo "[ok]   self-check: [parquet] accounts for every src/*.f90 but $(set -- $FACADE_EXCLUDES; echo $#)"
    fi
fi

if [ "$mode" = "check" ]; then
    if [ "$status" -eq 0 ]; then
        echo "All $checked module footprint(s) match tools/module_footprints.txt."
    else
        echo "check_module_footprints.sh: at least one footprint changed -- read this script's" >&2
        echo "header before updating tools/module_footprints.txt." >&2
    fi
fi

finished=1
exit $status
