#!/usr/bin/env python3
"""Golden vectors for `pf_random_perm_at`, from an independent arbitrary-precision model.

The whole point is that this file shares no code with `src/parquet_random.f90`: it is a
transcription of the *contract* -- the width rule, the round count, the round function and the
key derivation -- written from the specification rather than from the Fortran. A vector produced
by running the library would only prove the library agrees with itself.

Python integers are arbitrary precision, so nothing here wraps, and every intermediate is masked
exactly where the Fortran masks it. That makes this the reference for the claim that the Fortran
kernel cannot overflow: if the two agree, no int64 intermediate exceeded its bound.

**These vectors are what guards the frozen contract.** Bijectivity cannot see the round count --
an odd count transposes the factors and still yields a permutation -- so a change from four rounds
to three passes every structural test and breaks only these. Same for the multipliers, the width
rule and the key schedule.

Usage:
    python3 tools/generate_random_perm_vectors.py          # emit Fortran declarations
"""

MASK64 = (1 << 64) - 1
M31 = (1 << 31) - 1
M32 = (1 << 32) - 1
C1 = 2654435761          # 0x9E3779B1, the odd 32-bit golden-ratio constant
C2 = 2246822519          # 0x85EBCA77, xxHash PRIME32_2
ROUNDS = 4


def mix2(rk, x):
    """Two masked multiplies. Every operand is below 2**31 before a multiply by a value below
    2**32, so each product is below 2**63 -- the bound the Fortran relies on."""
    z = x ^ rk
    z = (z & M31) * C1
    assert z < (1 << 63), "product exceeded the int64 bound the Fortran assumes"
    z ^= z >> 29
    z = (z & M31) * C2
    assert z < (1 << 63), "product exceeded the int64 bound the Fortran assumes"
    z ^= z >> 31
    return z & M32


def round_keys(seed):
    s = seed & MASK64
    return [mix2((j * C1), s & M32) ^ mix2(j, (s >> 32) & M32) for j in range(1, ROUNDS + 1)]


def factors(m):
    a = 1
    while a * a < m:
        a += 1
    return a, (m + a - 1) // a


def feistel(rk, a, b, x):
    p, q = a, b
    l = x // q
    r = x - l * q
    for j in range(ROUNDS):
        w = mix2(rk[j], r) & M31
        prod = w * p
        assert prod < (1 << 63), "multiply-shift exceeded the int64 bound"
        t = l + (prod >> 31)
        if t >= p:
            t -= p
        l, r = r, t
        p, q = q, p
    return l * q + r


def perm_at(seed, m, k):
    n = max(m, 1)
    x = min(max(k - 1, 0), n - 1)
    if n == 1:
        return 1
    a, b = factors(n)
    rk = round_keys(seed)
    while True:
        x = feistel(rk, a, b, x)
        if x < n:
            return x + 1


def main():
    # Cases chosen for what they exercise, not for tidiness: a size where a*b == m exactly (100),
    # two where the cycle-walk must run (5 -> 3x2, 7 -> 3x3), a non-square mid size, a population
    # above int32, and a negative seed (the key schedule shifts the seed right, and Fortran's ISHFT
    # is logical, so a negative seed is the case a signed shift would get wrong).
    cases = [
        (20260816, 100, [1, 2, 3, 50, 99, 100]),
        (20260816, 5, [1, 2, 3, 4, 5]),
        (20260816, 7, [1, 4, 7]),
        (1, 1000, [1, 2, 500, 999, 1000]),
        (-7, 1000, [1, 2, 500, 1000]),
        (20260816, 4000000000, [1, 2, 3999999999, 4000000000]),
    ]
    print("    ! Generated by tools/generate_random_perm_vectors.py -- do not edit by hand.")
    print("    ! An independent arbitrary-precision model of the contract, never a Fortran run.")
    for seed, m, ks in cases:
        vals = [perm_at(seed, m, k) for k in ks]
        # A permutation of a small m is checked whole, so the vector is the whole thing.
        print(f"    ! seed={seed} m={m}")
        print(f"    !   k   = {ks}")
        print(f"    !   val = {vals}")
    print()
    print("    ! Flat form for the test's DATA statements:")
    seeds, ms, kk, vv = [], [], [], []
    for seed, m, ks in cases:
        for k in ks:
            seeds.append(seed)
            ms.append(m)
            kk.append(k)
            vv.append(perm_at(seed, m, k))
    for name, arr in (("seed", seeds), ("m", ms), ("k", kk), ("expect", vv)):
        body = ", ".join(f"{v}_int64" for v in arr)
        print(f"    {name}: {body}")


if __name__ == "__main__":
    main()
