#!/usr/bin/env bash
set -euo pipefail

work_dir="$(pwd)"
mode="${1:-}"

python3 - "$work_dir" "$mode" <<'PY'
from pathlib import Path
import re
import sys

work_dir = Path(sys.argv[1]).resolve()
mode = sys.argv[2]
is_base = (mode == 'base')

docs_dir = work_dir / 'docs'
module_name = 'parquet_maml_base' if is_base else 'parquet_maml'
out_path = work_dir / 'src' / f'{module_name}.f90'

maml_files = sorted(docs_dir.rglob('*.maml'))
if not maml_files:
    raise SystemExit('No .maml files found under docs/')


def make_identifier(name: str) -> str:
    stem = Path(name).stem.lower()
    ident = re.sub(r'[^a-z0-9]+', '_', stem).strip('_')
    if not ident:
        ident = 'maml'
    if ident[0].isdigit():
        ident = 'maml_' + ident
    return 'parquet_maml_' + ident


def fstr(s: str) -> str:
    return '"' + s.replace('"', '""') + '"'


# Free-form Fortran source lines are limited to 132 characters and a single
# statement may span at most 255 continuation lines (F2008+). Emitting one
# assignment statement per MAML line (rather than one big array constructor
# chained with "&") keeps the number of continuation lines per statement
# small and independent of the total MAML file length. Individual MAML
# lines are chunked here too, so even a very long single line stays safely
# under both limits.
CHUNK_LEN = 100


def emit_assignment(target: str, text: str) -> list:
    quoted = fstr(text)
    if len(quoted) <= CHUNK_LEN + 2:
        return [f'        {target} = {quoted}']
    chunks = [text[i:i + CHUNK_LEN] for i in range(0, len(text), CHUNK_LEN)] or ['']
    stmt = [f'        {target} = &']
    for idx, chunk in enumerate(chunks):
        suffix = ' // &' if idx < len(chunks) - 1 else ''
        stmt.append(f'            {fstr(chunk)}{suffix}')
    return stmt

lines = []
lines.append('!===========================================')
lines.append('! This file is automatically generated! Do not edit it directly!')
lines.append('! Instead, edit the MAML files under docs/ and run generate_parquet_maml.sh to regenerate this file.')
lines.append('! Generator script: parquet-fortran/tools/generate_parquet_maml.sh')
lines.append('!===========================================')
lines.append('!')
lines.append(f'module {module_name}')
if not is_base:
    lines.append('    use parquet, only: parquet_maml_file, parquet_load_maml_file')
    lines.append('    use parquet, only: parquet_validate_maml, parquet_validate_user_maml')
lines.append('    implicit none')
lines.append('    private')
lines.append('')
if is_base:
    lines.append('    type, public :: parquet_maml_file')
    lines.append('        character(len=:), allocatable :: name')
    lines.append('        character(len=:), allocatable :: lines(:)')
    lines.append('    end type parquet_maml_file')
    lines.append('')

public_names = ['get_parquet_maml']
if not is_base:
    public_names.append('set_maml')
function_blocks = []
case_blocks = []

for path in maml_files:
    identifier = make_identifier(path.name)
    public_names.append(identifier)
    file_lines = path.read_text(encoding='utf-8').splitlines()
    max_len = max((len(x) for x in file_lines), default=1)
    rel_name = path.relative_to(docs_dir).as_posix()

    block = []
    block.append(f'    function {identifier}() result(maml)')
    block.append('        type(parquet_maml_file) :: maml')
    block.append('')
    block.append(f'        maml%name = {fstr(rel_name)}')
    if file_lines:
        block.append(f'        allocate(character(len={max_len}) :: maml%lines({len(file_lines)}))')
        for idx, text in enumerate(file_lines):
            block.extend(emit_assignment(f'maml%lines({idx + 1})', text))
    else:
        block.append('        allocate(character(len=1) :: maml%lines(0))')
    block.append(f'    end function {identifier}')
    function_blocks.append('\n'.join(block))

    case_blocks.append(f'        case ({fstr(rel_name)})')
    case_blocks.append(f'            maml = {identifier}()')
    case_blocks.append(f'        case ({fstr(Path(rel_name).stem)})')
    case_blocks.append(f'            maml = {identifier}()')

for public_name in public_names:
    lines.append(f'    public :: {public_name}')
lines.append('')
lines.append('contains')
lines.append('')
lines.append('    function get_parquet_maml(name) result(maml)')
lines.append('        character(len=*), intent(in) :: name')
lines.append('        type(parquet_maml_file) :: maml')
lines.append('')
lines.append('        select case (trim(name))')
lines.extend(case_blocks)
lines.append('        case default')
lines.append('            error stop "get_parquet_maml: unknown internal MAML file: " // trim(name)')
lines.append('        end select')
if not is_base:
    lines.append('        call parquet_validate_maml(maml)')
lines.append('    end function get_parquet_maml')
lines.append('')
if not is_base:
    lines.append('    function set_maml(maml_default, maml_file) result(maml)')
    lines.append("        character(len=*),intent(in) :: maml_default       ! < default MAML name (input to get_parquet_maml)")
    lines.append("        character(len=*),intent(in),optional :: maml_file ! < MAML file name (if provided, overrides default)")
    lines.append('        type(parquet_maml_file) :: maml')
    lines.append('        type(parquet_maml_file) :: maml_base')
    lines.append('        logical :: has_maml_file')
    lines.append('        !')
    lines.append('        has_maml_file = present(maml_file)')
    lines.append('        if (has_maml_file) then')
    lines.append("            has_maml_file = trim(maml_file) /= ''")
    lines.append('        end if')
    lines.append('        !')
    lines.append('        if (has_maml_file) then')
    lines.append('            ! read MAML from file')
    lines.append('            maml = parquet_load_maml_file(trim(maml_file))')
    lines.append('            ! validate user defined MAML file')
    lines.append('            maml_base = get_parquet_maml(trim(maml_default))')
    lines.append('            call parquet_validate_user_maml(maml_base, maml)')
    lines.append('        else')
    lines.append('            ! no MAML provided, use default MAML')
    lines.append('            maml = get_parquet_maml(trim(maml_default))')
    lines.append('        end if')
    lines.append('        !')
    lines.append('    end function set_maml')
    lines.append('')
lines.extend(function_blocks)
lines.append('')
lines.append(f'end module {module_name}')
lines.append('')

out_path.write_text('\n'.join(lines), encoding='ascii')
print(f'Generated {out_path} from {len(maml_files)} MAML files (module {module_name})')
PY
