#!/usr/bin/env python3
"""Generate the golden vectors that freeze `parquet_random`'s bit contract.

`parquet_random` produces values that are permanent: every one of them is baked into the
library's public promise, and changing any of them after release is a major-version event made
visible only through `pf_random_algorithm`. The vectors below are what pin that promise, so they
are derived here -- from an arbitrary-precision Python model of the contract -- rather than read
back out of a Fortran run, which could only ever confirm that the implementation agrees with
itself.

Emitted (COMMITTED to the repository, like every other generator's output -- nothing is generated
at build time, so the fpm build stays dependency-free):

  test/test_random_vectors.f90    module `test_random_vectors`: the Random123 known-answer
                                  vectors, and golden tables for pf_random_at, pf_random32_at,
                                  pf_random_bits_at, pf_random_int_at, pf_random_key and
                                  pf_random_fill_draws.

Usage:  tools/generate_random_golden_vectors.py [--check] [--self-test]

  --check      regenerate into memory and compare with the committed file; exit 1 on any
               difference (so CI, or a reviewer, can prove the committed output is current).
  --self-test  re-derive every PUBLISHED anchor -- the three Random123 KATs, the mix64 checksum,
               the wide-width oracle value, and the stable rows of the reference tables -- and
               exit 1 if any of them fails. This is what makes the emitted table trustworthy:
               without it the generator would merely be self-consistent.

NEVER HAND-EDIT A VECTOR. A contract change is an edit to the oracle below plus a regeneration;
an edit to the emitted table is a lie that `--check` will catch and nothing else would.

--------------------------------------------------------------------------------------------
ONE CONTRACT POINT WHERE THE PUBLISHED TABLE AND THE PUBLISHED PROSE DISAGREED, AND WHY THE
PROSE WON. `feature_random_reference.md` Table 1's rows for `draw = 2` and `draw = 5` were
generated by an earlier, scratch oracle that gave each `real64` value a WHOLE block (block
`d-1`, words `c0,c1`). Both documents' prose says the opposite in so many words -- value `d`
takes words `2d-2` and `2d-1`, i.e. block `(d-1)/2`, pair `mod(d-1,2)`, TWO values per block --
and three independent statements corroborate the prose:

  * `feature_random.md` §20: "two `real64` values at `draw = 1, 2` share block 0";
  * the reference's §5: whole-block consumption in a draw-axis fill is worth 1.68x-1.71x
    "simply not discarding half of each enciphering", and is "not available to an index-axis
    loop, where each block's second value is reserved for draw 2 at that index" -- neither
    sentence means anything if a scalar draw already consumes a whole block;
  * the reference's §2.2 note that a future `pf_random_fill_int` costs ~1/0.6 of its `real64`
    sibling per value -- a ratio that would be exactly 1.0 under one-block-per-value. (That 0.6
    is itself now obsolete: it described `/v1`, where the integer generic really did take a whole
    block. Under `/v2` the two fills are on one grid and the ratio is far closer to 1. It is still
    evidence for what the reference assumed about `real64`, which is the only thing it is cited
    for here.)

Nine of Table 1's twelve rows use `draw = 1`, where the two mappings coincide, which is why only
two rows ever disagreed. The mapping lives in `real64_word_indices()` below; reversing this
decision is an edit to that one function plus a regeneration.

`pf_random_int_at` USED TO BE THE ODD ONE OUT, and `/v2` fixed it. Under `philox4x32-10/v1` it
was the generic that really did take a whole block per value (`index = d - 1`, first pair only),
which is a plausible reason the scratch oracle above generalised that shape to `real64` as well.
The consequence was an exact collision -- `int_at(seed, i, lo, hi, d)` returned the bits of
`bits_at(seed, i, 2d-1)` -- so an integer at draw 2 and a real at draw 3 were the same
randomness. `/v2` gives it stride 2 like its siblings. Draw 1 is bit-identical under both, which
is why every anchor in this file survived the change untouched; every emitted vector at draw >= 2
did not. Same rule as above: the mapping is `int_at()` below, and reversing it is an edit there
plus a regeneration -- never an edit to the table.
--------------------------------------------------------------------------------------------
"""

import argparse
import pathlib
import struct
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "test" / "test_random_vectors.f90"

# ---------------------------------------------------------------------------------------------
# The contract, as arbitrary-precision integers.  Every constant here is permanent bit contract.
# ---------------------------------------------------------------------------------------------

M32 = 0xFFFFFFFF
MASK64 = (1 << 64) - 1
INT64_MIN = -(1 << 63)
INT64_MAX = (1 << 63) - 1

PHILOX_M0 = 0xD2511F53
PHILOX_M1 = 0xCD9E8D57
PHILOX_W0 = 0x9E3779B9
PHILOX_W1 = 0xBB67AE85
PHILOX_ROUNDS = 10

MIX_A = 0xBF58476D1CE4E5B9
MIX_B = 0x94D049BB133111EB

#: Offset in label space that keeps a retried draw's key off `pf_random_key(seed, n)`, which is
#: a documented user idiom -- without it 100 % of retried draws share that family's block.
RETRY_TAG = 0x5A17000000000000

#: The widest range served by the 32-bit candidate grid.  **Frozen contract, never a setting.**
#: A block is four 32-bit words, so a narrow integer draw costs a quarter of an enciphering
#: instead of a half.  The price is a rejection rate of `(2**32 mod s)/2**32`, which rises with
#: `s` and peaks at 33.3 % just above `2**32/3`; capping the WIDTH at `2**24` bounds the worst
#: case over every admitted `s` at 0.389 %, attained at `s = 16711936`.  The cap is on the width
#: `hi - lo + 1`, never on how many values are drawn -- the two coincide for a resample and differ
#: for everything else.
NARROW32_CAP = 1 << 24


def u64(x):
    """The unsigned 64-bit pattern of `x`."""
    return x & MASK64


def signed64(x):
    """`x`'s 64-bit pattern read as a signed `integer(int64)`."""
    x = u64(x)
    return x - (1 << 64) if x > INT64_MAX else x


def philox4x32_10(c0, c1, c2, c3, k0, k1):
    """Philox4x32-10 on four 32-bit counter words and two 32-bit key words."""
    for r in range(PHILOX_ROUNDS):
        p0 = PHILOX_M0 * c0
        p1 = PHILOX_M1 * c2
        hi0, lo0 = p0 >> 32, p0 & M32
        hi1, lo1 = p1 >> 32, p1 & M32
        c0, c1, c2, c3 = (hi1 ^ c1 ^ k0) & M32, lo1, (hi0 ^ c3 ^ k1) & M32, lo0
        if r != PHILOX_ROUNDS - 1:       # the key bump is skipped after the final round
            k0 = (k0 + PHILOX_W0) & M32
            k1 = (k1 + PHILOX_W1) & M32
    return c0, c1, c2, c3


def key_of(k):
    """Split a 64-bit key into Philox's two 32-bit key words: low half first."""
    k = u64(k)
    return k & M32, (k >> 32) & M32


def block(seed, stream, index, key=None):
    """Block `index` (0-based) of `stream` under `seed`, or under an explicit retry `key`."""
    k0, k1 = key_of(seed if key is None else key)
    s = u64(stream)
    return philox4x32_10(index & M32, (index >> 32) & M32, s & M32, (s >> 32) & M32, k0, k1)


def word(seed, stream, index):
    """Word `index` (0-based) of the stream: blocks 0,1,2,... each giving c0,c1,c2,c3 in order."""
    return block(seed, stream, index // 4)[index % 4]


def clamp_draw(draw):
    """`draw < 1` is a documented precondition violation, absorbed so tier 0 stays total."""
    return draw if draw >= 1 else 1


def real64_word_indices(draw):
    """The two word indices a `real64`/raw-bits value occupies.  THE contract point above."""
    d = clamp_draw(draw)
    return 2 * (d - 1), 2 * (d - 1) + 1


def bits_at(seed, stream, draw=1):
    """`pf_random_bits_at`: the first word is the LOW half of the 64-bit pattern."""
    lo_index, hi_index = real64_word_indices(draw)
    return (word(seed, stream, hi_index) << 32) | word(seed, stream, lo_index)


def at(seed, stream, draw=1):
    """`pf_random_at`: the top 53 bits of the pattern, scaled to [0, 1).  Exact in real64."""
    return float(bits_at(seed, stream, draw) >> 11) * (2.0 ** -53)


def at32(seed, stream, draw=1):
    """`pf_random32_at`: the top 24 bits of ONE word.  Its own sequence, not a narrowing."""
    return float(word(seed, stream, clamp_draw(draw) - 1) >> 8) * (2.0 ** -24)


def mix64(z):
    """The SplitMix64 finaliser.  `mix64(0) == 0`, and it is a bijection."""
    z = u64(z)
    z = u64((z ^ (z >> 30)) * MIX_A)
    z = u64((z ^ (z >> 27)) * MIX_B)
    return z ^ (z >> 31)


def random_key(seed, label):
    """`pf_random_key`: a derived key IS a seed, so it composes by nesting."""
    return mix64(mix64(seed) ^ u64(label))


def retry_key(seed, attempt):
    """The key for retry `attempt` (1-based).  Re-keys; never tweaks, and never moves the counter."""
    return mix64(mix64(seed) ^ u64(attempt ^ RETRY_TAG))


def umod_2p64(s):
    """`2**64 mod s` for `s` read as unsigned.  Correct at and above 2**63, where the naive
    spelling silently makes up to half the requested range unreachable."""
    return (1 << 64) % s


def int_at(seed, stream, lo, hi, draw=1):
    """`pf_random_int_at`: exact rejection, on ONE OF TWO GRIDS chosen by the range's WIDTH.

    **Narrow (`1 <= s <= NARROW32_CAP`): stride 1, a single 32-bit candidate.**  Draw `d` is word
    `d - 1` -- exactly the grid `pf_random32_at` walks -- so one enciphering serves four draws
    instead of two.  `x < 2**32` and `s <= 2**24` make `x * s` fit an ordinary signed 64-bit
    integer, so the reduction needs no 128-bit product.  The rejection test is the exact 32-bit
    analogue, accept iff `low32(x*s) >= 2**32 mod s`, so the result is exactly uniform rather than
    uniform to within `2**-32`.

    **Wide (everything else): stride 2, the same grid as `pf_random_at`/`pf_random_bits_at`** --
    draw `d` is words `2d-2` and `2d-1`, i.e. block `(d-1)//2` pair `(d-1)%2`.

    So the documented "the three 64-bit generics are one grid at one coordinate" property is now
    RANGE-DEPENDENT: it holds for a wide range, and for a narrow one the integer draw shares its
    grid with `pf_random32_at` instead.  The advice that follows is unchanged -- take two generics
    at different draws, or on different streams -- but which generic a narrow integer draw collides
    with has moved.  Under `/v1` this generic had stride 4; `/v2` aligned it to stride 2 and then
    admitted this narrow rule.  Returns (value, retries).
    """
    if lo > hi:
        lo, hi = hi, lo
    a, s = lo, u64(hi - lo + 1)
    d = clamp_draw(draw)
    if s == 0:                                    # the full int64 range: nothing to reduce
        return signed64(bits_at(seed, stream, d)), 0
    if 1 <= s <= NARROW32_CAP:                    # the 32-bit grid
        threshold = (1 << 32) % s
        blk, slot = (d - 1) // 4, (d - 1) % 4
        attempt = 0
        while True:                               # uncapped: a cap would reintroduce bias
            key = None if attempt == 0 else retry_key(seed, attempt)
            x = block(seed, stream, blk, key=key)[slot]
            product = x * s
            if (product & M32) >= threshold:
                return a + (product >> 32), attempt
            attempt += 1
    blk, pair = (d - 1) // 2, (d - 1) % 2
    threshold = umod_2p64(s)
    attempt = 0
    while True:                                   # uncapped: a cap would reintroduce bias
        key = None if attempt == 0 else retry_key(seed, attempt)
        c = block(seed, stream, blk, key=key)
        x = (c[2 * pair + 1] << 32) | c[2 * pair]
        product = x * s
        if (product & MASK64) >= threshold:
            return a + (product >> 64), attempt
        attempt += 1


def fill_at(seed, stream, count, draw=1):
    return [at(seed, stream, draw + k) for k in range(count)]


def fill_at32(seed, stream, count, draw=1):
    return [at32(seed, stream, draw + k) for k in range(count)]


# ---------------------------------------------------------------------------------------------
# Published anchors.  Every one is independent of RETRY_TAG and of the draw-mapping question, so
# each is evidence about the oracle rather than about a decision.  Provenance is in the names:
# KAT = Random123's own test vectors; the rest are feature_random_reference.md §3.
# ---------------------------------------------------------------------------------------------

KAT = [
    ((0x00000000, 0x00000000, 0x00000000, 0x00000000), (0x00000000, 0x00000000),
     (0x6627e8d5, 0xe169c58d, 0xbc57ac4c, 0x9b00dbd8)),
    ((0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff), (0xffffffff, 0xffffffff),
     (0x408f276d, 0x41c83b0e, 0xa20bc7c6, 0x6d5451fd)),
    ((0x243f6a88, 0x85a308d3, 0x13198a2e, 0x03707344), (0xa4093822, 0x299f31d0),
     (0xd16cfe09, 0x94fdcceb, 0x5001e420, 0x24126ea1)),
]

MIX64_CHECKSUM = 3577507447353514381          # xor of mix64(n*2654435761), n = 1..200000
WIDE_WIDTH_ANCHOR = 8560708566805553027       # pf_random_int_at(12345, 1, 0, huge(int64))

#: Reference Table 1, restricted to `draw = 1` -- the rows the superseded draw mapping cannot
#: reach (see the module docstring).  (seed, stream, bits, at).
ANCHOR_SCALAR = [
    (0, 1, -1113111854248028703, 0.93965808547024587),
    (1, 1, 4792503686440360978, 0.25980214542417135),
    (12345, 1, -1325326940098445562, 0.92815388261458487),
    (-7, 1, 4192158348114182785, 0.22725735942143199),
    (INT64_MAX, 1, 7027889878920110309, 0.38098267373570360),
    (12345, 2, -1078885104378990352, 0.94151352129850241),
    (12345, -5, 3491215599672883141, 0.18925917688903104),
    (12345, 1000000, 5778726092042289111, 0.31326536915954584),
    (INT64_MIN, 1, -6995668981347843496, 0.62076402462166058),
    (42, 0, 8643895580192075859, 0.46858651833910492),
]

#: Reference Table 2, restricted to the rows that do not retry (the retrying ones predate
#: RETRY_TAG).  (seed, stream, lo, hi, value).
#:
#: **Six rows were RE-BASELINED when the narrow 32-bit grid was admitted, and their provenance is
#: therefore weaker than the rest of this list.** Every row whose width is `<= NARROW32_CAP` moved,
#: because a narrow draw now reads one 32-bit word where it used to read a 64-bit pair. Those rows
#: no longer match `feature_random_reference.md` §3 Table 2, which documents the superseded rule --
#: they are marked `narrow` below, and that document's Table 2 should be read as historical for
#: them. The rows marked `wide` are untouched and remain independent evidence about this oracle,
#: as do the KATs, `MIX64_CHECKSUM`, `WIDE_WIDTH_ANCHOR` and every scalar/key anchor.
#:
#: `check_narrow_from_spec()` below is what keeps the re-baselined rows from being circular: it
#: recomputes them from the written specification rather than by calling `int_at`.
ANCHOR_INT = [
    (12345, 1, 0, 999999, 485065),                # narrow, re-baselined
    (12345, 1, 0, 3999999999999, 3712615530458),  # wide
    (12345, 1, 1, 6, 3),                          # narrow, re-baselined
    (12345, 1, 999999, 0, 485065),                # narrow, re-baselined
    (12345, 1, 7, 7, 7),                          # narrow, degenerate: any rule gives 7
    (12345, 1, -10, 10, 0),                       # narrow, re-baselined
    (12345, 1, 0, INT64_MAX, 8560708566805553027),        # wide
    (12345, 1, -INT64_MAX, INT64_MAX, 7898045096756330246),  # wide
    (12345, 1, INT64_MIN, INT64_MAX, -1325326940098445562),  # wide, full range
    (0, 1, 0, 999999, 516679),                    # narrow, re-baselined
    (-7, 3, -100, 100, -10),                      # narrow, re-baselined
    (INT64_MAX, 1, 0, 4294967296, 1636308124),    # wide (width 2**32+1 > NARROW32_CAP)
]


def check_narrow_from_spec(seed, stream, lo, hi, draw=1):
    """Recompute a narrow integer draw FROM THE WRITTEN SPECIFICATION, not by calling `int_at`.

    Deliberately spelled out rather than factored: this exists so the re-baselined anchors above
    are checked by a second, independently written path.  If this and `int_at` are ever refactored
    into calling one another, the check silently becomes worthless.
    """
    if lo > hi:
        lo, hi = hi, lo
    width = hi - lo + 1
    assert 1 <= width <= NARROW32_CAP, "not a narrow range"
    d = draw if draw >= 1 else 1
    # The candidate is word `d-1` of the stream -- block `(d-1)//4`, word `(d-1)%4`.
    c0, c1, c2, c3 = philox4x32_10((d - 1) // 4 & M32, ((d - 1) // 4 >> 32) & M32,
                                   u64(stream) & M32, (u64(stream) >> 32) & M32,
                                   u64(seed) & M32, (u64(seed) >> 32) & M32)
    candidate = [c0, c1, c2, c3][(d - 1) % 4]
    attempt = 0
    while True:
        product = candidate * width
        if (product % (1 << 32)) >= ((1 << 32) % width):
            return lo + product // (1 << 32)
        attempt += 1
        k = retry_key(seed, attempt)
        c0, c1, c2, c3 = philox4x32_10((d - 1) // 4 & M32, ((d - 1) // 4 >> 32) & M32,
                                       u64(stream) & M32, (u64(stream) >> 32) & M32,
                                       u64(k) & M32, (u64(k) >> 32) & M32)
        candidate = [c0, c1, c2, c3][(d - 1) % 4]

#: Reference Table 3, entire.  (seed, label, value).
ANCHOR_KEY = [
    (0, 0, 0),
    (0, 1, 6238072747940578789),
    (1, 0, 8841707400507832957),
    (12345, 1, -6019050582001612395),
    (12345, 2, -4080249998812334667),
    (12345, -1, -581499740233304683),
    (-7, 3, 7469970230224790144),
    (INT64_MAX, INT64_MAX, 2193281995749435141),
    (42, 1000000, 2272459864431828475),
]


def self_test():
    """Re-derive every published anchor.  Returns a list of failure descriptions."""
    bad = []

    def eq(label, got, want):
        if got != want:
            bad.append("%-52s got %s  want %s" % (label, got, want))

    for n, (ctr, key, out) in enumerate(KAT, start=1):
        eq("Random123 KAT %d" % n, philox4x32_10(*ctr, *key), out)

    checksum = 0
    for n in range(1, 200001):
        checksum ^= mix64(n * 2654435761)
    eq("mix64 xor checksum n=1..200000", signed64(checksum), MIX64_CHECKSUM)
    eq("mix64(0)", mix64(0), 0)
    eq("pf_random_key(0, 0)", random_key(0, 0), 0)

    eq("int_at(12345,1,0,huge) wide-width anchor", int_at(12345, 1, 0, INT64_MAX)[0],
       WIDE_WIDTH_ANCHOR)

    for seed, stream, want_bits, want_at in ANCHOR_SCALAR:
        eq("bits_at(%d,%d)" % (seed, stream), signed64(bits_at(seed, stream)), want_bits)
        eq("at(%d,%d)" % (seed, stream), "%.17f" % at(seed, stream), "%.17f" % want_at)

    for seed, stream, lo, hi, want in ANCHOR_INT:
        value, retries = int_at(seed, stream, lo, hi)
        eq("int_at(%d,%d,%d,%d)" % (seed, stream, lo, hi), value, want)
        # For a narrow range, check the SAME value a second time from the written specification.
        # Six of these anchors were re-baselined when the narrow grid was admitted, so without an
        # independently written path they would only be checking the oracle against itself.
        w = (max(lo, hi) - min(lo, hi)) + 1
        if 1 <= w <= NARROW32_CAP:
            eq("int_at(%d,%d,%d,%d) from spec" % (seed, stream, lo, hi),
               check_narrow_from_spec(seed, stream, lo, hi), want)
        if retries:
            bad.append("int_at(%d,%d,%d,%d) retried %d times -- it is not a stable anchor and "
                       "must be removed from ANCHOR_INT" % (seed, stream, lo, hi, retries))

    for seed, label, want in ANCHOR_KEY:
        eq("pf_random_key(%d,%d)" % (seed, label), signed64(random_key(seed, label)), want)

    # Contract identities, asserted here as well as in the suite: a break in any of them would
    # otherwise reach the emitted table as a consistent pair of wrong values.
    eq("width-0 int_at == bits_at", int_at(12345, 1, INT64_MIN, INT64_MAX)[0],
       signed64(bits_at(12345, 1)))
    eq("lo>hi swaps", int_at(12345, 1, 999999, 0)[0], int_at(12345, 1, 0, 999999)[0])
    eq("draw 0 clamps to 1", bits_at(12345, 1, 0), bits_at(12345, 1, 1))
    eq("draw -5 clamps to 1", bits_at(12345, 1, -5), bits_at(12345, 1, 1))
    eq("at == to_real64(bits_at)", at(12345, 7, 3), float(bits_at(12345, 7, 3) >> 11) * 2.0**-53)
    eq("fill prefix consistency", fill_at(12345, 1, 3), fill_at(12345, 1, 6)[:3])
    eq("fill offset start", fill_at(12345, 1, 3, draw=4), fill_at(12345, 1, 6)[3:])
    eq("fill agrees with scalar", fill_at(12345, 1, 1), [at(12345, 1)])
    eq("fill32 agrees with scalar", fill_at32(12345, 1, 1), [at32(12345, 1)])

    # The two real64 values of one block must come from that block's two pairs -- the property
    # the superseded mapping broke, restated so a regression cannot pass quietly.
    c = block(12345, 1, 0)
    eq("draw 1 is pair (c0,c1)", bits_at(12345, 1, 1), (c[1] << 32) | c[0])
    eq("draw 2 is pair (c2,c3)", bits_at(12345, 1, 2), (c[3] << 32) | c[2])

    # `/v2`: the integer generic is on the SAME grid as the 64-bit real one.  Asserted at every
    # draw, not only draw 1 -- draw 1 agrees under `/v1` too, so a draw-1-only check would pass
    # unchanged against the mapping this replaced and prove nothing.
    for d in (1, 2, 3, 4, 5, 8, 9):
        eq("int_at at draw %d is bits_at at draw %d" % (d, d),
           int_at(12345, 1, INT64_MIN, INT64_MAX, d)[0], signed64(bits_at(12345, 1, d)))
    # Negative control: the `/v1` identity `int_at(d) == bits_at(2d-1)` must now FAIL for d >= 2.
    # Without this, restoring the old mapping would satisfy every check above at draw 1 alone.
    for d in (2, 3, 5):
        if int_at(12345, 1, INT64_MIN, INT64_MAX, d)[0] == signed64(bits_at(12345, 1, 2 * d - 1)):
            bad.append("int_at at draw %d still equals bits_at at draw %d -- this is the /v1 "
                       "stride-4 mapping, which /v2 replaced" % (d, 2 * d - 1))
    # Two consecutive integer draws must share one block, which is what the bulk fill amortises.
    eq("int draws 1 and 2 share block 0", ((1 - 1) // 2, (2 - 1) // 2), (0, 0))

    return bad


# ---------------------------------------------------------------------------------------------
# The golden tables.
# ---------------------------------------------------------------------------------------------

SEEDS = [0, 1, 12345, -7, INT64_MAX, INT64_MIN]
STREAMS = [-5, 0, 1, 2, 1000000]
DRAWS = [0, 1, 2, 5]                              # 0 exercises the clamp


def scalar_rows():
    """Every (seed, stream, draw) of the grid, with all three scalar draws' results."""
    rows = []
    for seed in SEEDS:
        for stream in STREAMS:
            for draw in DRAWS:
                rows.append((seed, stream, draw, signed64(bits_at(seed, stream, draw)),
                             at(seed, stream, draw), at32(seed, stream, draw)))
    return rows


#: (seed, stream, lo, hi, draw, note).  The reference's own rows first, then the regenerated
#: retrying pair, then rows that exercise regimes the reference table does not reach.
INT_CASES = [
    (12345, 1, 0, 999999, 1, "the common case"),
    (12345, 1, 0, 3999999999999, 1, "width above 2**32"),
    (12345, 1, 1, 6, 1, "a die"),
    (12345, 1, 999999, 0, 1, "lo > hi swaps"),
    (12345, 1, 7, 7, 1, "degenerate range"),
    (12345, 1, -10, 10, 1, "straddles zero"),
    (12345, 1, 0, INT64_MAX, 1, "width 2**63"),
    (12345, 1, -INT64_MAX, INT64_MAX, 1, "width 2**64 - 1"),
    (12345, 1, INT64_MIN, INT64_MAX, 1, "width 0: equals pf_random_bits_at"),
    (12345, 2, -6050532056176732160, 6148914691236517205, 1, "retries (regenerated: RETRY_TAG)"),
    (12345, 10, -6050532056176732160, 6148914691236517205, 1, "retries (regenerated: RETRY_TAG)"),
    (0, 1, 0, 999999, 1, "seed 0"),
    (-7, 3, -100, 100, 1, "negative seed"),
    (INT64_MAX, 1, 0, 4294967296, 1, "width just over 2**32"),
    # ---- the draw axis -------------------------------------------------------------------------
    # Under `/v2` an integer draw has stride 2, so draw `d` is block `(d-1)/2` pair `(d-1)%2` and
    # consecutive draws share a block two at a time. These rows exist to pin BOTH halves of that:
    # the block index and the parity. Draws 1 and 2 must land in block 0, draws 3 and 4 in block 1.
    # Under `/v1` (stride 4, first pair only) every one of them named a different block and always
    # pair 0, so a grid that stopped at draw 1 could not tell the two mappings apart at all.
    (12345, 1, 0, 999999, 2, "draw 2 -- block 0's SECOND pair, shared with draw 1"),
    (12345, 1, 0, 999999, 3, "draw 3 -- block 1, first pair"),
    (12345, 1, 0, 999999, 4, "draw 4 -- block 1, second pair"),
    (12345, 1, 0, 999999, 5, "draw 5"),
    (12345, 1, 0, 999999, 0, "draw 0 clamps to 1"),
    (12345, 1, 0, 999999, 1000, "a large even draw: block index arithmetic"),
    (12345, 1, 0, 999999, 1001, "the odd draw sharing that block"),
    (12345, 1, INT64_MIN, INT64_MAX, 2, "width 0 at draw 2: the pair choice, unreduced"),
    (12345, 1, INT64_MIN, INT64_MAX, 3, "width 0 at draw 3: the block step, unreduced"),
    # A retry taken OFF draw 1. The retry re-keys and re-reads the same coordinate, so it inherits
    # the stride -- under `/v1` this row would read block 1 pair 0 of the retry key, under `/v2`
    # block 0 pair 1. Nothing else in the grid pins the retry path's own addressing.
    (12345, 2, INT64_MIN, INT64_MIN + int(0.672 * 2 ** 64) - 1, 2, "a retry at draw 2"),
    (12345, 7, INT64_MIN, INT64_MIN + int(0.672 * 2 ** 64) - 1, 3, "a retry at draw 3"),
    (INT64_MIN, -1, INT64_MIN, 0, 1, "width 2**63 placed at the bottom of the range"),
    (12345, 1, -1, INT64_MAX, 1, "width 2**63 + 1, low limb borrows"),
    (12345, 4, INT64_MIN + 1, INT64_MAX - 1, 1, "width 2**64 - 3"),
    (-1, 1, 1, 2, 1, "seed -1, a two-value range"),
    (12345, 1, 0, 1, 1, "the narrowest non-degenerate range"),
]


def int_rows():
    rows = []
    for seed, stream, lo, hi, draw, note in INT_CASES:
        value, retries = int_at(seed, stream, lo, hi, draw)
        rows.append((seed, stream, lo, hi, draw, value, retries, note))
    return rows


#: Rows whose whole point is that a retry fires; the suite asserts the count is non-zero, so a
#: retry path that is compiled and never entered cannot pass as tested.
def retrying_int_rows():
    """Streams at a width close to 2**64 * 2/3, where rejection is most likely."""
    lo, hi = INT64_MIN, INT64_MIN + int(0.672 * 2 ** 64) - 1
    rows = []
    for stream in range(1, 400):
        value, retries = int_at(12345, stream, lo, hi)
        if retries:
            rows.append((12345, stream, lo, hi, 1, value, retries, "retry chain %d" % retries))
        if len(rows) == 8:
            break
    return rows


KEY_CASES = ANCHOR_KEY + [
    (12345, 0, None), (-7, -7, None), (INT64_MIN, 1, None), (1, INT64_MIN, None),
    (0, INT64_MAX, None), (12345, 1000000, None),
]

FILL_CASES = [
    (12345, 1, 1, 6, "the whole prefix, spanning three blocks"),
    (12345, 1, 4, 3, "an offset start, mid-block"),
    (12345, 1, 1, 1, "a single value: must equal the scalar draw"),
    (0, -3, 2, 5, "negative stream, starting at draw 2"),
    (INT64_MIN, 0, 1, 8, "extreme seed, stream 0"),
]


def fill_rows():
    """(seed, stream, start, count) plus the flattened real64 and real32 expectations."""
    meta, v64, v32 = [], [], []
    for seed, stream, start, count, note in FILL_CASES:
        meta.append((seed, stream, start, count, len(v64) + 1, note))
        v64.extend(fill_at(seed, stream, count, start))
        v32.extend(fill_at32(seed, stream, count, start))
    return meta, v64, v32


# ---------------------------------------------------------------------------------------------
# Fortran emission.
# ---------------------------------------------------------------------------------------------

BANNER = """!===========================================
! Author: Elmo Tempel (elmo.tempel@ut.ee)
!===========================================
!
! GENERATED FILE -- DO NOT EDIT BY HAND.
! Regenerate with:  tools/generate_random_golden_vectors.py
! The contract oracle lives in that script; edit it there, not here. Never hand-edit a vector.
!"""

WIDTH = 128           # emitted lines stay inside the project's 132-column limit


def int_literal(value, kind):
    """A Fortran literal for `value`.  The extreme negative of a kind cannot be written directly:
    `-9223372036854775808_int64` is parsed as the negation of a constant that does not fit, which
    is a compile error, so it is built from `huge` instead (the same trap as `-128_int8`)."""
    limits = {"int64": INT64_MIN, "int32": -(1 << 31)}
    if value == limits[kind]:
        return "(-huge(1_%s) - 1_%s)" % (kind, kind)
    return "%d_%s" % (value, kind)


def real_literal(value, kind):
    """Shortest round-tripping decimal, with an explicit kind so no literal is default-real."""
    text = repr(value)
    if "e" in text or "E" in text:
        mantissa, _, exponent = text.partition("e")
        if "." not in mantissa:
            mantissa += ".0"
        return "%s_%s * 10.0_%s**(%d)" % (mantissa, kind, kind, int(exponent))
    if "." not in text:
        text += ".0"
    return "%s_%s" % (text, kind)


def array(decl, name, size_expr, items, indent=4):
    """Emit `decl :: name(size_expr) = [ ... ]`, wrapped with '&' continuations."""
    pad = " " * indent
    body = " " * (indent + 4)
    out = ["%s%s, parameter :: %s(%s) = [ &" % (pad, decl, name, size_expr)]
    line = body
    for n, item in enumerate(items):
        piece = item + (", " if n < len(items) - 1 else "]")
        if line.rstrip() != body.rstrip() and len(line) + len(piece) + 2 > WIDTH:
            out.append(line.rstrip() + " &")
            line = body
        line += piece
    out.append(line.rstrip())
    return out


def comment_block(text, indent=4):
    return ["%s!! %s" % (" " * indent, line) if line else "%s!!" % (" " * indent)
            for line in text.split("\n")]


def gen_module():
    scalars = scalar_rows()
    ints = int_rows() + retrying_int_rows()
    keys = [(seed, label, signed64(random_key(seed, label))) for seed, label, _ in KEY_CASES]
    fill_meta, fill64, fill32 = fill_rows()

    L = []
    L.append(BANNER)
    L.append("")
    L.append("!> Golden vectors freezing `parquet_random`'s bit contract.")
    L.append("!!")
    L.append("!! Every value here is permanent: it is what the library promises to return for a")
    L.append("!! given seed, stream and draw, on every machine and compiler, for as long as")
    L.append("!! `pf_random_algorithm` reads \"philox4x32-10/v2\". The tables are derived from an")
    L.append("!! arbitrary-precision model of the contract in the generator named above, never")
    L.append("!! from a Fortran run -- a table read back out of the implementation could only")
    L.append("!! ever confirm that the implementation agrees with itself.")
    L.append("!!")
    L.append("!! Real values are carried BOTH as a decimal literal and as the `transfer` bit")
    L.append("!! pattern of that value. The bit pattern is the authoritative form: it is exact,")
    L.append("!! and it cannot be quietly weakened by a compiler's decimal conversion.")
    L.append("module test_random_vectors")
    L.append("    use iso_fortran_env, only: int32, int64, real32, real64")
    L.append("    implicit none")
    L.append("    public")
    L.append("")

    # -- Random123 known-answer vectors --------------------------------------------------------
    L.append("    ! ---- Philox4x32-10 known-answer vectors (Random123) ----")
    L.append("    !")
    L.append("    ! Flattened: KAT k occupies kat_ctr(4k-3:4k), kat_key(2k-1:2k), kat_out(4k-3:4k).")
    L.append("    ! Only KAT 1 is reachable through the public surface (seed 0, stream 0, block 0,")
    L.append("    ! i.e. draws 1 and 2); the other two need counter words no draw index can produce,")
    L.append("    ! so all three are asserted against the suite's own strict Philox reference, which")
    L.append("    ! is what the agreement sweep then checks the library against.")
    L.append("    integer, parameter :: n_kat = %d" % len(KAT))
    L += array("integer(int64)", "kat_ctr", "4 * n_kat",
               [int_literal(w, "int64") for ctr, _, _ in KAT for w in ctr])
    L += array("integer(int64)", "kat_key", "2 * n_kat",
               [int_literal(w, "int64") for _, key, _ in KAT for w in key])
    L += array("integer(int64)", "kat_out", "4 * n_kat",
               [int_literal(w, "int64") for _, _, out in KAT for w in out])
    L.append("")

    # -- scalar draws ---------------------------------------------------------------------------
    L.append("    ! ---- pf_random_at / pf_random32_at / pf_random_bits_at ----")
    L.append("    !")
    L.append("    ! The full grid of %d seeds x %d streams x %d draws. Draw 0 is present on purpose:"
             % (len(SEEDS), len(STREAMS), len(DRAWS)))
    L.append("    ! it must clamp to 1 rather than flow into the block arithmetic, where truncating")
    L.append("    ! division would collide it with draw 1 by accident rather than by rule.")
    L.append("    integer, parameter :: n_scalar = %d" % len(scalars))
    L += array("integer(int64)", "scalar_seed", "n_scalar",
               [int_literal(r[0], "int64") for r in scalars])
    L += array("integer(int64)", "scalar_stream", "n_scalar",
               [int_literal(r[1], "int64") for r in scalars])
    L += array("integer(int64)", "scalar_draw", "n_scalar",
               [int_literal(r[2], "int64") for r in scalars])
    L += array("integer(int64)", "scalar_bits", "n_scalar",
               [int_literal(r[3], "int64") for r in scalars])
    L += array("integer(int64)", "scalar_at_bits", "n_scalar",
               [int_literal(struct.unpack("<q", struct.pack("<d", r[4]))[0], "int64")
                for r in scalars])
    L += array("integer(int32)", "scalar_at32_bits", "n_scalar",
               [int_literal(struct.unpack("<i", struct.pack("<f", r[5]))[0], "int32")
                for r in scalars])
    L += array("real(real64)", "scalar_at", "n_scalar", [real_literal(r[4], "real64")
                                                         for r in scalars])
    L += array("real(real32)", "scalar_at32", "n_scalar", [real_literal(r[5], "real32")
                                                           for r in scalars])
    L.append("")

    # -- integer draws --------------------------------------------------------------------------
    L.append("    ! ---- pf_random_int_at ----")
    L.append("    !")
    L.append("    ! int_retries is how many times the exact-rejection loop re-keyed before this")
    L.append("    ! value was accepted. It is data, not decoration: a suite that never asserts a")
    L.append("    ! non-zero entry here would pass just as happily against a retry path that is")
    L.append("    ! compiled and never entered.")
    L.append("    integer, parameter :: n_int = %d" % len(ints))
    L += array("integer(int64)", "int_seed", "n_int", [int_literal(r[0], "int64") for r in ints])
    L += array("integer(int64)", "int_stream", "n_int", [int_literal(r[1], "int64") for r in ints])
    L += array("integer(int64)", "int_lo", "n_int", [int_literal(r[2], "int64") for r in ints])
    L += array("integer(int64)", "int_hi", "n_int", [int_literal(r[3], "int64") for r in ints])
    L += array("integer(int64)", "int_draw", "n_int", [int_literal(r[4], "int64") for r in ints])
    L += array("integer(int64)", "int_value", "n_int", [int_literal(r[5], "int64") for r in ints])
    L += array("integer(int32)", "int_retries", "n_int", [int_literal(r[6], "int32") for r in ints])
    L.append("")

    # -- derived keys ---------------------------------------------------------------------------
    L.append("    ! ---- pf_random_key ----")
    L.append("    !")
    L.append("    ! pf_random_key(0, 0) is 0, and for every seed exactly one label derives 0: the")
    L.append("    ! finaliser is a bijection with mix64(0) = 0. Surprising, not a defect.")
    L.append("    integer, parameter :: n_key = %d" % len(keys))
    L += array("integer(int64)", "key_seed", "n_key", [int_literal(r[0], "int64") for r in keys])
    L += array("integer(int64)", "key_label", "n_key", [int_literal(r[1], "int64") for r in keys])
    L += array("integer(int64)", "key_value", "n_key", [int_literal(r[2], "int64") for r in keys])
    L.append("")

    # -- fills ------------------------------------------------------------------------------------
    L.append("    ! ---- pf_random_fill_draws ----")
    L.append("    !")
    L.append("    ! Case c fills fill_count(c) values starting at draw fill_start(c); its expected")
    L.append("    ! values are fill_at_bits(fill_first(c) : fill_first(c) + fill_count(c) - 1).")
    L.append("    integer, parameter :: n_fill = %d" % len(fill_meta))
    L.append("    integer, parameter :: n_fill_values = %d" % len(fill64))
    L += array("integer(int64)", "fill_seed", "n_fill",
               [int_literal(r[0], "int64") for r in fill_meta])
    L += array("integer(int64)", "fill_stream", "n_fill",
               [int_literal(r[1], "int64") for r in fill_meta])
    L += array("integer(int64)", "fill_start", "n_fill",
               [int_literal(r[2], "int64") for r in fill_meta])
    L += array("integer", "fill_count", "n_fill", ["%d" % r[3] for r in fill_meta])
    L += array("integer", "fill_first", "n_fill", ["%d" % r[4] for r in fill_meta])
    L += array("integer(int64)", "fill_at_bits", "n_fill_values",
               [int_literal(struct.unpack("<q", struct.pack("<d", v))[0], "int64") for v in fill64])
    L += array("integer(int32)", "fill_at32_bits", "n_fill_values",
               [int_literal(struct.unpack("<i", struct.pack("<f", v))[0], "int32") for v in fill32])
    L.append("")
    L.append("end module test_random_vectors")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="compare the committed file with a fresh generation; exit 1 on drift")
    ap.add_argument("--self-test", action="store_true",
                    help="re-derive every published anchor; exit 1 if any of them fails")
    args = ap.parse_args()

    if args.self_test:
        bad = self_test()
        if bad:
            print("generate_random_golden_vectors.py: %d published anchor(s) NOT reproduced:"
                  % len(bad), file=sys.stderr)
            for line in bad:
                print("  " + line, file=sys.stderr)
            print("The oracle does not implement the contract. Do NOT regenerate from it.",
                  file=sys.stderr)
            return 1
        print("generate_random_golden_vectors.py: self-test OK "
              "(%d KATs, the mix64 checksum, %d scalar, %d integer and %d key anchors, "
              "plus the contract identities)."
              % (len(KAT), len(ANCHOR_SCALAR), len(ANCHOR_INT), len(ANCHOR_KEY)))
        return 0

    text = gen_module()

    over = [n for n, line in enumerate(text.split("\n"), start=1) if len(line) > 132]
    if over:
        print("generate_random_golden_vectors.py: emitted line(s) exceed 132 columns: %s"
              % over[:10], file=sys.stderr)
        return 1

    if args.check:
        if not OUT_PATH.exists() or OUT_PATH.read_text() != text:
            print("generate_random_golden_vectors.py --check: %s differs from a fresh generation."
                  % OUT_PATH.relative_to(REPO_ROOT), file=sys.stderr)
            print("Re-run tools/generate_random_golden_vectors.py to regenerate.", file=sys.stderr)
            return 1
        print("generate_random_golden_vectors.py --check: %s is current."
              % OUT_PATH.relative_to(REPO_ROOT))
        return 0

    OUT_PATH.write_text(text)
    print("generate_random_golden_vectors.py: wrote %s (%d lines)."
          % (OUT_PATH.relative_to(REPO_ROOT), text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
