#!/usr/bin/env bash
set -euo pipefail

work_dir="$(pwd)"
mode=""
maml_dir="schemas"
check=""

# --dir=NAME / --dir NAME selects the directory (relative to the project
# root) to scan for .maml files; may appear before or after the positional
# mode argument (empty, or "base"). Defaults to "schemas" -- this project's
# own convention, and the one downstream projects following "Embedding your
# own MAML schemas" are expected to match unless they have their own.
# --check compares the regenerated content with the committed file instead of
# writing it, exiting nonzero on drift -- mirrors generate_parquet_columns.py's
# own --check. For this project's own base MAML, run as: base --check
while [ $# -gt 0 ]; do
    case "$1" in
        --dir=*)
            maml_dir="${1#--dir=}"
            shift
            ;;
        --dir)
            maml_dir="${2:?--dir requires a value}"
            shift 2
            ;;
        --check)
            check="1"
            shift
            ;;
        *)
            mode="$1"
            shift
            ;;
    esac
done

python3 - "$work_dir" "$mode" "$maml_dir" "$check" <<'PY'
from pathlib import Path
import re
import sys

work_dir = Path(sys.argv[1]).resolve()
mode = sys.argv[2]
maml_dir_name = sys.argv[3]
check = bool(sys.argv[4])
is_base = (mode == 'base')

maml_source_dir = work_dir / maml_dir_name
module_name = 'parquet_maml_base' if is_base else 'parquet_maml'
out_path = work_dir / 'src' / f'{module_name}.f90'

maml_files = sorted(maml_source_dir.rglob('*.maml'))
if not maml_files:
    raise SystemExit(f'No .maml files found under {maml_dir_name}/')


def make_identifier(name: str) -> str:
    stem = Path(name).stem.lower()
    ident = re.sub(r'[^a-z0-9]+', '_', stem).strip('_')
    if not ident:
        ident = 'maml'
    if ident[0].isdigit():
        ident = 'maml_' + ident
    return 'parquet_maml_' + ident


def fstr(s: str) -> str:
    return '"' + s.replace('"', '""') + '"'


# Wraps a leading '!>' doc-comment to the project's 132-column limit, splitting
# on word boundaries -- needed here (unlike the mostly-static doc blocks below,
# hand-wrapped and verified once) because this helper's callers interpolate
# runtime data (a .maml filename) of arbitrary length into the comment text.
def emit_doc(indent: str, *sentences: str) -> list:
    prefix = f'{indent}!> '
    text = ' '.join(sentences)
    avail = 132 - len(prefix)
    out = []
    cur = ''
    for word in text.split():
        cand = (cur + ' ' + word) if cur else word
        if len(cand) > avail and cur:
            out.append(prefix + cur)
            cur = word
        else:
            cur = cand
    if cur:
        out.append(prefix + cur)
    return out


# Free-form Fortran source lines are limited to 132 characters and a single
# statement may span at most 255 continuation lines (F2008+). Emitting one
# assignment statement per MAML line (rather than one big array constructor
# chained with "&") keeps the number of continuation lines per statement
# small and independent of the total MAML file length. Individual MAML
# lines are chunked here too, so even a very long single line stays safely
# under both limits.
CHUNK_LEN = 100


def emit_assignment(target: str, text: str) -> list:
    quoted = fstr(text)
    if len(quoted) <= CHUNK_LEN + 2:
        return [f'        {target} = {quoted}']
    chunks = [text[i:i + CHUNK_LEN] for i in range(0, len(text), CHUNK_LEN)] or ['']
    stmt = [f'        {target} = &']
    for idx, chunk in enumerate(chunks):
        suffix = ' // &' if idx < len(chunks) - 1 else ''
        stmt.append(f'            {fstr(chunk)}{suffix}')
    return stmt

lines = []
lines.append('!===========================================')
lines.append('! This file is automatically generated! Do not edit it directly!')
lines.append(f'! Instead, edit the MAML files under {maml_dir_name}/ and run generate_parquet_maml.sh to regenerate this file.')
lines.append('! Generator script: parquet-fortran/tools/generate_parquet_maml.sh')
lines.append('!===========================================')
if is_base:
    lines.append('!> Base-library MAML fixtures: embeds every .maml file under schemas/ bundled')
    lines.append('!> with this library as a compiled-in string array, addressable by filename via')
    lines.append('!> get_parquet_maml, plus the shared parquet_maml_file type and its')
    lines.append('!> add_col_qc/set_col_qc qc-maml builders.')
else:
    lines.append('!> Downstream-project MAML fixtures: embeds every local .maml schema file as a')
    lines.append('!> compiled-in string array, addressable by name via get_parquet_maml/set_maml,')
    lines.append('!> already parsed into a ready-to-use parquet_schema.')
lines.append(f'module {module_name}')
if not is_base:
    lines.append('    use parquet, only: parquet_schema, parquet_load_maml_file')
    lines.append('    use parquet, only: parquet_parse_maml, parquet_validate_user_maml')
lines.append('    implicit none')
lines.append('    private')
lines.append('')
if is_base:
    lines.append('    !> One schema field the base MAML declares but a user-supplied MAML omits;')
    lines.append('    !> populated by parquet_validate_user_maml, one entry per missing field.')
    lines.append('    type, public :: parquet_maml_missing_column')
    lines.append('        character(len=:), allocatable :: name      !! The name of the field [required].')
    lines.append('        character(len=:), allocatable :: unit      !! The unit of measurement for the field.')
    lines.append('        character(len=:), allocatable :: info      !! A short description of the field.')
    lines.append('        character(len=:), allocatable :: ucd       !! Unified Content Descriptor for IVOA (can have many).')
    lines.append('        character(len=:), allocatable :: data_type !! The data type of the field [required]; base token')
    lines.append('        !! only for a temporal column (unit/utc are in time_unit/is_utc).')
    lines.append('        integer :: time_unit = 0 !! time/timestamp stored unit (a parquet_unit_* selector; 0 if not temporal).')
    lines.append('        logical :: is_utc = .false. !! timestamp UTC-adjusted flag.')
    lines.append('        integer :: array_size = 1 !! Maximum length of character strings.')
    lines.append('        integer :: col_size = 1   !! The number of elements in the vector column.')
    lines.append('    end type parquet_maml_missing_column')
    lines.append('')
    lines.append('    !> One col_map: entry: `- <internal_name>: <output_name>`, i.e. the field')
    lines.append('    !> declared as `output_name` in this MAML fields: actually corresponds to')
    lines.append('    !> the internal/canonical column named `internal_name`.')
    lines.append('    type, public :: parquet_maml_col_map_entry')
    lines.append('        character(len=:), allocatable :: internal_name !! Canonical (internal) column name.')
    lines.append('        character(len=:), allocatable :: output_name   !! Renamed name as declared in fields:.')
    lines.append('    end type parquet_maml_col_map_entry')
    lines.append('')
    lines.append('    !> One embedded or user-supplied MAML file: its raw source lines plus, once')
    lines.append('    !> parsed/validated, the columns missing relative to the base schema and any')
    lines.append('    !> col_map: renames it declares. add_col_qc/set_col_qc build a qc-maml')
    lines.append('    !> incrementally (see parquet_maml_base_add_col_qc.f90).')
    lines.append('    type, public :: parquet_maml_file')
    lines.append('        logical :: user_maml = .false. !! true if this is a user defined MAML file')
    lines.append('        character(len=:), allocatable :: name !! This MAML file name (embedded fixture name or path).')
    lines.append('        character(len=:), allocatable :: lines(:) !! Raw MAML source, one array element per line.')
    lines.append('        !> Columns present in the base MAML but missing from this (user) MAML;')
    lines.append('        !> populated by parquet_validate_user_maml, consumed by parquet_read_maml.')
    lines.append('        type(parquet_maml_missing_column), allocatable :: missing_columns(:)')
    lines.append('        !> Parsed col_map: section (see parquet_maml_col_map_entry): exposes the')
    lines.append('        !> renames this MAML declares, for inspection; populated by')
    lines.append('        !> parquet_validate_user_maml. Renames are applied automatically whenever')
    lines.append('        !> this MAML lines are parsed, independent of whether this is set.')
    lines.append('        type(parquet_maml_col_map_entry), allocatable :: col_map(:)')
    lines.append('    contains')
    lines.append("        procedure :: add_col_qc => parquet_maml_add_col_qc !! Appends one qc: field entry.")
    lines.append("        procedure :: set_col_qc => parquet_maml_set_col_qc !! In-place form; parses the name into its argument.")
    lines.append('    end type parquet_maml_file')
    lines.append('')
    # add_col_qc/set_col_qc are two forms of the same type-bound builder for
    # read-time qc-mamls: both append one qc: field entry from a compact
    # "col, min, max, miss" string. add_col_qc is a subroutine returning the
    # parsed name via an optional out-argument; set_col_qc is also a
    # subroutine, but takes its single col_name argument as intent(inout): it
    # holds the compact string on entry and the parsed name on exit, so a
    # caller reuses one variable (call maml%set_col_qc(col)) instead of
    # assigning a function result back into it -- a subroutine can't alias the
    # same actual argument to separate intent(in)/intent(out) dummies, and a
    # function returning character(len=:), allocatable is never used in this
    # codebase (see "Build and compiler notes" in CLAUDE.md for why). Both
    # bodies are hand-written (string parsing + validation) in the submodule
    # src/parquet_maml_base_add_col_qc.f90 rather than embedded here, so they
    # are deferred via module-procedure interfaces: parquet_maml_base is at the
    # bottom of the module stack, so the body must stay self-contained (it
    # cannot use parquet_metadata's validation helpers without a cycle).
    lines.append('    interface')
    lines.append('        !> Appends one qc: field entry to this MAML from a compact')
    lines.append('        !> "col, min, max, miss" string. col_name (optional) returns the')
    lines.append('        !> parsed column name. Implemented in the submodule')
    lines.append('        !> src/parquet_maml_base_add_col_qc.f90.')
    lines.append('        module subroutine parquet_maml_add_col_qc(self, qc_input, col_name)')
    lines.append('            class(parquet_maml_file), intent(inout) :: self !! qc-maml being built; gains a fields: entry.')
    lines.append('            character(len=*), intent(in) :: qc_input !! compact "col, min, max, miss" string.')
    lines.append('            character(len=:), allocatable, intent(out), optional :: col_name !! parsed column name.')
    lines.append('        end subroutine parquet_maml_add_col_qc')
    lines.append('        !> In-place form of add_col_qc: appends the same qc: field entry. `col_name` is')
    lines.append('        !> `intent(inout)`: it holds the compact "col, min, max, miss" string on entry and')
    lines.append('        !> the parsed column name on exit, so a caller reuses one variable')
    lines.append('        !> (call maml%set_col_qc(col)) instead of naming a separate input and output.')
    lines.append('        module subroutine parquet_maml_set_col_qc(self, col_name)')
    lines.append('            class(parquet_maml_file), intent(inout) :: self !! qc-maml being built; gains a fields: entry.')
    lines.append('            character(len=:), allocatable, intent(inout) :: col_name !! compact "col, min, max, miss" string on')
    lines.append('            !! entry; parsed column name on exit.')
    lines.append('        end subroutine parquet_maml_set_col_qc')
    lines.append('    end interface')
    lines.append('')

public_names = ['get_parquet_maml']
if not is_base:
    public_names.append('set_maml')
function_blocks = []
case_blocks = []

for path in maml_files:
    identifier = make_identifier(path.name)
    public_names.append(identifier)
    file_lines = path.read_text(encoding='utf-8').splitlines()
    max_len = max((len(x) for x in file_lines), default=1)
    rel_name = path.relative_to(maml_source_dir).as_posix()

    # Non-base (downstream) mode returns a fully parsed parquet_schema --
    # parquet_parse_maml populates %cinfo/%metadata from %maml right here,
    # so callers get a ready-to-use schema with no separate parse step.
    # Base mode keeps returning the raw parquet_maml_file: it's this
    # library's own internal fixture accessor (parquet_maml_base sits below
    # parquet_core.f90/parquet_schema in the module stack, so it cannot return a
    # parquet_schema without a circular dependency), and its own callers
    # parse the result themselves via parquet_parse_maml.
    result_var = 'maml' if is_base else 'schema'
    result_type = 'parquet_maml_file' if is_base else 'parquet_schema'
    name_target = f'{result_var}%name' if is_base else f'{result_var}%maml%name'
    lines_target = f'{result_var}%lines' if is_base else f'{result_var}%maml%lines'

    block = []
    if is_base:
        block.extend(emit_doc('    ', f'Returns the embedded {rel_name} MAML fixture, unparsed (raw lines only).'))
    else:
        block.extend(emit_doc('    ', f'Returns the embedded {rel_name} MAML fixture, already parsed into a schema.'))
    block.append(f'    function {identifier}() result({result_var})')
    if is_base:
        block.append(f'        type({result_type}) :: {result_var} !! the {rel_name} MAML, unparsed.')
    else:
        block.append(f'        type({result_type}) :: {result_var} !! the {rel_name} MAML, parsed into a schema.')
    block.append('')
    block.append(f'        {name_target} = {fstr(rel_name)}')
    if file_lines:
        block.append(f'        allocate(character(len={max_len}) :: {lines_target}({len(file_lines)}))')
        for idx, text in enumerate(file_lines):
            block.extend(emit_assignment(f'{lines_target}({idx + 1})', text))
    else:
        block.append(f'        allocate(character(len=1) :: {lines_target}(0))')
    if not is_base:
        block.append(f'        call parquet_parse_maml({result_var})')
    block.append(f'    end function {identifier}')
    function_blocks.append('\n'.join(block))

    case_blocks.append(f'        case ({fstr(rel_name)})')
    case_blocks.append(f'            {result_var} = {identifier}()')
    case_blocks.append(f'        case ({fstr(Path(rel_name).stem)})')
    case_blocks.append(f'            {result_var} = {identifier}()')

for public_name in public_names:
    lines.append(f'    public :: {public_name}')
lines.append('')
lines.append('contains')
lines.append('')
result_var = 'maml' if is_base else 'schema'
result_type = 'parquet_maml_file' if is_base else 'parquet_schema'
if is_base:
    lines.append('    !> Returns the named embedded .maml fixture from schemas/ as a raw parquet_maml_file')
    lines.append('    !> (unparsed lines only); error stops on an unknown name. Names are matched')
    lines.append('    !> both with and without the .maml extension.')
else:
    lines.append('    !> Returns the named embedded MAML fixture, already parsed into a ready-to-use')
    lines.append('    !> parquet_schema; error stops on an unknown name. Names are matched both with')
    lines.append('    !> and without the .maml extension.')
lines.append(f'    function get_parquet_maml(name) result({result_var})')
lines.append('        character(len=*), intent(in) :: name !! embedded fixture name, with or without .maml.')
if is_base:
    lines.append(f'        type({result_type}) :: {result_var} !! the matching MAML, unparsed (raw lines only).')
else:
    lines.append(f'        type({result_type}) :: {result_var} !! the matching MAML, already parsed into a schema.')
lines.append('')
lines.append('        select case (trim(name))')
lines.extend(case_blocks)
lines.append('        case default')
lines.append('            error stop "get_parquet_maml: unknown internal MAML file: " // trim(name)')
lines.append('        end select')
# No explicit validate call needed here in either mode: base mode never
# validated at this point (its own callers parse/validate explicitly), and
# non-base no longer needs to either -- each per-file function above already
# ran parquet_parse_maml (which validates first) before returning its schema.
lines.append('    end function get_parquet_maml')
lines.append('')
if not is_base:
    lines.append('    !> Resolves to a parquet_schema for either a user-supplied MAML file (parsed')
    lines.append('    !> and validated against the maml_default embedded schema) or, if maml_file')
    lines.append('    !> is absent/blank, straight to the embedded maml_default fixture itself.')
    lines.append('    function set_maml(maml_default, maml_file) result(schema)')
    lines.append("        character(len=*),intent(in) :: maml_default       !! default MAML name (input to get_parquet_maml)")
    lines.append("        character(len=*),intent(in),optional :: maml_file !! MAML file name (if provided, overrides default)")
    lines.append('        type(parquet_schema) :: schema !! resulting parsed schema.')
    lines.append('        type(parquet_schema) :: schema_base')
    lines.append('        logical :: has_maml_file')
    lines.append('        !')
    lines.append('        has_maml_file = present(maml_file)')
    lines.append('        if (has_maml_file) then')
    lines.append("            has_maml_file = trim(maml_file) /= ''")
    lines.append('        end if')
    lines.append('        !')
    lines.append('        if (has_maml_file) then')
    lines.append('            ! read MAML from file')
    lines.append('            schema%maml = parquet_load_maml_file(trim(maml_file))')
    lines.append('            ! validate user defined MAML file against the default (base) schema')
    lines.append('            schema_base = get_parquet_maml(trim(maml_default))')
    lines.append('            call parquet_validate_user_maml(schema_base%maml, schema%maml)')
    lines.append('            call parquet_parse_maml(schema)')
    lines.append('        else')
    lines.append('            ! no MAML provided, use default MAML')
    lines.append('            schema = get_parquet_maml(trim(maml_default))')
    lines.append('        end if')
    lines.append('        !')
    lines.append('    end function set_maml')
    lines.append('')
lines.extend(function_blocks)
lines.append('')
lines.append(f'end module {module_name} ! GCOVR_EXCL_LINE')
lines.append('')

text = '\n'.join(lines)

if check:
    current = out_path.read_text(encoding='ascii') if out_path.exists() else ''
    if current != text:
        print(f'generate_parquet_maml.sh: {out_path.name} is out of date', file=sys.stderr)
        print('Re-run tools/generate_parquet_maml.sh and commit the result.', file=sys.stderr)
        sys.exit(1)
    print(f'generate_parquet_maml.sh: {out_path.name} is up to date (module {module_name})')
else:
    out_path.write_text(text, encoding='ascii')
    print(f'Generated {out_path} from {len(maml_files)} MAML files (module {module_name})')
PY
