#!/usr/bin/env bash
# Runs every scenario supported by the test/error_scenarios.f90 helper program
# and checks that each one aborts (or exits cleanly) as expected. This is the
# same check test_errors.f90 does from inside the test-drive suite, exposed
# here as a standalone script for manual/CI use without going through fpm's
# test-drive runner.
#
# Keep this list in sync with the `select case` in test/error_scenarios.f90 --
# it is intentionally a complete, independent mirror of every scenario name
# there (not a curated subset), since a script that silently only covers some
# scenarios would be misleading for the "quick manual check"/"CI step" use
# this is documented for in README.md.
set -uo pipefail

cd "$(dirname "$0")/.."

# Worker mode: this script re-invokes itself (via xargs -P below) as
#   run_error_scenarios.sh __worker__ <bin> <results_dir> <idx> <scenario> <expect_abort>
# to run exactly one scenario and record its PASS/FAIL line + status to
# "$results_dir/$idx.{status,line}". This lets the scenario list further down
# be dispatched across several worker processes in parallel via xargs -P
# instead of one `fpm test error_scenarios -- ...` invocation at a time --
# each scenario is an independent process writing to its own uniquely-named
# file under test_run/, so there is no cross-scenario interference. Kept as a
# re-invocation of this same file (rather than a separate helper script or an
# exported shell function) so it works unchanged under the old bash (3.2, no
# `export -f`/`wait -n`) macOS ships as /bin/bash.
if [ "${1:-}" = "__worker__" ]; then
    bin="$2"
    results_dir="$3"
    idx="$4"
    scenario="$5"
    expect_abort="$6"

    "$bin" "$scenario" > /dev/null 2>&1
    exitstat=$?

    # exit code 97 means error_scenarios.f90's `case default` was hit --
    # i.e. this scenario name isn't recognized there (typo, or renamed on
    # one side but not the other) -- distinct from a genuine abort so this
    # doesn't silently "pass" by coincidence.
    if [ "$exitstat" -eq 97 ]; then
        status=FAIL
        line=$(printf "[FAIL] %-50s scenario name not recognized by error_scenarios.f90 (typo?)" "$scenario")
    else
        if [ "$exitstat" -ne 0 ]; then aborted=1; else aborted=0; fi
        if [ "$aborted" -eq "$expect_abort" ]; then
            status=PASS
            line=$(printf "[PASS] %-50s (exit=%d, expected abort=%s)" "$scenario" "$exitstat" "$expect_abort")
        else
            status=FAIL
            line=$(printf "[FAIL] %-50s (exit=%d, expected abort=%s)" "$scenario" "$exitstat" "$expect_abort")
        fi
    fi
    echo "$status" > "$results_dir/$idx.status"
    echo "$line" > "$results_dir/$idx.line"
    exit 0
fi

# scenario:expect_abort ("0" or "1")
scenarios=(
    "ok:0"
    "print_stat_smoke:0"
    "print_stat_all_types:0"
    "print_stat_default_scalar_type:0"
    "print_stat_filtered_rows:0"
    "print_stat_screened_rows:0"
    "write_undeclared_column:1"
    "write_undeclared_column_int64:1"
    "write_undeclared_column_float32:1"
    "write_undeclared_column_float64:1"
    "write_undeclared_column_logical:1"
    "write_undeclared_column_string:1"
    "write_undeclared_column_string_compact:1"
    "write_undeclared_column_int32_matrix:1"
    "write_undeclared_column_int64_matrix:1"
    "write_undeclared_column_float32_matrix:1"
    "write_undeclared_column_float64_matrix:1"
    "write_undeclared_column_logical_matrix:1"
    "write_undeclared_column_string_matrix:1"
    "write_not_divisible_int64:1"
    "write_not_divisible_float32:1"
    "write_not_divisible_float64:1"
    "write_not_divisible_logical:1"
    "write_not_divisible_string:1"
    "write_array_mismatch_int32_matrix:1"
    "write_array_mismatch_int64_matrix:1"
    "write_array_mismatch_float32_matrix:1"
    "write_array_mismatch_float64_matrix:1"
    "write_array_mismatch_logical_matrix:1"
    "write_array_mismatch_string_matrix:1"
    "write_chunk_undeclared_column_int32:1"
    "write_chunk_undeclared_column_int64:1"
    "write_chunk_undeclared_column_float32:1"
    "write_chunk_undeclared_column_float64:1"
    "write_chunk_undeclared_column_logical:1"
    "write_chunk_undeclared_column_string:1"
    "write_chunk_undeclared_column_string_compact:1"
    "write_chunk_undeclared_column_int32_matrix:1"
    "write_chunk_undeclared_column_int64_matrix:1"
    "write_chunk_undeclared_column_float32_matrix:1"
    "write_chunk_undeclared_column_float64_matrix:1"
    "write_chunk_undeclared_column_logical_matrix:1"
    "write_chunk_undeclared_column_string_matrix:1"
    "write_chunk_not_divisible_int32:1"
    "write_chunk_not_divisible_int64:1"
    "write_chunk_not_divisible_float32:1"
    "write_chunk_not_divisible_float64:1"
    "write_chunk_not_divisible_logical:1"
    "write_chunk_not_divisible_string:1"
    "write_chunk_array_mismatch_int32_matrix:1"
    "write_chunk_array_mismatch_int64_matrix:1"
    "write_chunk_array_mismatch_float32_matrix:1"
    "write_chunk_array_mismatch_float64_matrix:1"
    "write_chunk_array_mismatch_logical_matrix:1"
    "write_chunk_array_mismatch_string_matrix:1"
    "write_chunk_string_matrix_exceeds_array_size:1"
    "write_chunk_string_exceeds_array_size:1"
    "write_chunk_no_row_group_open:1"
    "write_chunk_row_count_mismatch:1"
    "write_chunk_type_mismatch:1"
    "read_chunk_qc_hard_aborts:1"
    "read_chunk_qc_soft_warns:0"
    "read_chunk_check_complete_hard_aborts:1"
    "read_chunk_row_group_out_of_range:1"
    "get_chunk_size_row_group_out_of_range:1"
    "write_type_mismatch:1"
    "write_column_twice:1"
    "write_column_twice_no_schema:1"
    "write_maml_without_metadata:1"
    "write_protected_column_with_null:1"
    "write_values_not_divisible_by_col_size:1"
    "write_int64_to_int32_overflow:1"
    "write_float_to_int32_non_integral:1"
    "write_float_to_int32_out_of_range:1"
    "write_float_to_int64_non_integral:1"
    "write_float_to_int64_out_of_range:1"
    "write_string_matrix_exceeds_array_size:1"
    "write_string_exceeds_array_size:1"
    "write_unknown_compression:1"
    "write_overwrite_false_existing_file:1"
    "validate_bad_data_type:1"
    "validate_excluded_decimal_type:1"
    "validate_empty_field_name:1"
    "validate_duplicate_name:1"
    "validate_missing_table:1"
    "validate_no_fields:1"
    "validate_trailing_depends_no_fields:1"
    "validate_trailing_keywords_no_fields:1"
    "validate_user_maml_unknown_column:1"
    "validate_unknown_top_level_section:1"
    "validate_unknown_field_subkey:1"
    "validate_unknown_qc_subkey:1"
    "validate_protected_cols_unknown_name:1"
    "validate_col_map_unknown_internal:1"
    "validate_col_map_duplicate_internal:1"
    "validate_col_map_output_collision:1"
    "validate_col_map_output_not_declared:1"
    "validate_col_map_internal_also_in_fields:1"
    "validate_col_map_output_matches_other_field:1"
    "set_column_available_deactivated:1"
    "set_column_unavailable_deactivated:1"
    "validate_qc_min_not_numeric:1"
    "validate_qc_max_not_numeric:1"
    "validate_qc_min_non_integral_for_int32:1"
    "validate_qc_min_out_of_int32_range:1"
    "validate_qc_min_wrong_operator:1"
    "validate_qc_max_wrong_operator:1"
    "qc_maml_min_wrong_operator:1"
    "qc_maml_max_wrong_operator:1"
    "add_col_qc_min_reversed_operator:1"
    "add_col_qc_max_reversed_operator:1"
    "add_col_qc_operator_without_value:1"
    "add_col_qc_max_operator_without_value:1"
    "add_col_qc_bad_miss_value:1"
    "add_col_qc_too_many_fields:1"
    "add_col_qc_empty_column_name:1"
    "add_col_qc_duplicate_column:1"
    "add_col_qc_duplicate_column_single_quoted:1"
    "add_col_qc_duplicate_column_double_quoted:1"
    "set_col_qc_reversed_operator:1"
    "get_column_index_not_found:1"
    "get_field_name_index_too_low:1"
    "get_field_name_index_too_high:1"
    "read_column_with_nulls:1"
    "read_unsupported_physical_type:1"
    "large_string_roundtrip:0"
    "string_view_roundtrip:0"
    "string_view_compact_read_unsupported:1"
    "list_element_count_auto_multi_row_group:0"
    "columns_data_ptr_kind_mismatch:1"
    "columns_uninitialized_append_nulls:1"
    "columns_get_at_index_out_of_range:1"
    "columns_append_kind_mismatch:1"
    "columns_append_width_mismatch:1"
    "columns_paste_kind_mismatch:1"
    "columns_paste_width_mismatch:1"
    "columns_paste_string_kind:1"
    "columns_paste_source_index_below_one:1"
    "columns_paste_negative_count:1"
    "columns_paste_source_past_end:1"
    "columns_paste_destination_index_below_one:1"
    "columns_paste_destination_past_end:1"
    "columns_reindex_duplicate_index:1"
    "columns_clear_null_temporal:1"
    "string_column_reindex_length_mismatch:1"
    "string_column_reindex_out_of_range:1"
    "string_column_delete_by_mask_length_mismatch:1"
    "string_column_append_nulls_negative:1"
    "columns_string_column_wrong_kind:1"
    "columns_init_container_kind:1"
    "columns_init_width_on_scalar_kind:1"
    "columns_adopt_not_allocated_i32:1"
    "columns_adopt_not_allocated_i64:1"
    "columns_adopt_not_allocated_f32:1"
    "columns_adopt_not_allocated_f64:1"
    "columns_adopt_not_allocated_bool:1"
    "columns_adopt_not_allocated_date:1"
    "columns_adopt_not_allocated_time:1"
    "columns_adopt_not_allocated_ts:1"
    "columns_adopt_not_allocated_i32v:1"
    "columns_adopt_not_allocated_i64v:1"
    "columns_adopt_not_allocated_f32v:1"
    "columns_adopt_not_allocated_f64v:1"
    "columns_adopt_not_allocated_boolv:1"
    "columns_adopt_not_allocated_datev:1"
    "columns_adopt_not_allocated_timev:1"
    "columns_adopt_not_allocated_tsv:1"
    "columns_set_all_length_mismatch:1"
    "columns_get_at_width_mismatch:1"
    "columns_delete_by_mask_length_mismatch:1"
    "columns_reindex_length_mismatch:1"
    "table_assignment_blocked:1"
    "table_not_opened:1"
    "table_pointer_kind_mismatch:1"
    "table_get_array_kind_mismatch:1"
    "table_col_ptr_kind_mismatch_i32:1"
    "table_col_ptr_kind_mismatch_f32:1"
    "table_col_ptr_kind_mismatch_f64:1"
    "table_col_ptr_kind_mismatch_bool:1"
    "table_col_ptr_kind_mismatch_date:1"
    "table_col_ptr_kind_mismatch_time:1"
    "table_col_ptr_kind_mismatch_ts:1"
    "table_col_ptr_kind_mismatch_i32v:1"
    "table_col_ptr_kind_mismatch_i64v:1"
    "table_col_ptr_kind_mismatch_f32v:1"
    "table_col_ptr_kind_mismatch_f64v:1"
    "table_col_ptr_kind_mismatch_boolv:1"
    "table_col_ptr_kind_mismatch_datev:1"
    "table_col_ptr_kind_mismatch_timev:1"
    "table_col_ptr_kind_mismatch_tsv:1"
    "table_get_array_kind_mismatch_i64:1"
    "table_get_array_kind_mismatch_f32:1"
    "table_get_array_kind_mismatch_f64:1"
    "table_get_array_kind_mismatch_bool:1"
    "table_get_array_kind_mismatch_date:1"
    "table_get_array_kind_mismatch_time:1"
    "table_get_array_kind_mismatch_ts:1"
    "table_get_array_kind_mismatch_i32v:1"
    "table_get_array_kind_mismatch_i64v:1"
    "table_get_array_kind_mismatch_f32v:1"
    "table_get_array_kind_mismatch_f64v:1"
    "table_get_array_kind_mismatch_boolv:1"
    "table_get_array_kind_mismatch_datev:1"
    "table_get_array_kind_mismatch_timev:1"
    "table_get_array_kind_mismatch_tsv:1"
    "table_unknown_column:1"
    "table_unsupported_column_read:1"
    "table_prefetch_unknown_column:1"
    "table_prefetch_unsupported_column:1"
    "table_add_column_row_mismatch:1"
    "table_add_column_duplicate:1"
    "table_add_column_duplicate_force_false:1"
    "table_row_group_bounds_in_memory:1"
    "table_set_kind_mismatch:1"
    "table_get_file_metadata_in_memory:1"
    "table_get_file_metadata_missing_key:1"
    "table_kind_unknown_column:1"
    "table_set_length_mismatch:1"
    "table_write_missing_column:1"
    "table_write_unsupported_column:1"
    "table_write_unparsed_schema:1"
    "table_slice_below_first_row:1"
    "table_slice_past_last_row:1"
    "table_slice_inverted:1"
    "table_row_index_out_of_range:1"
    "table_get_slice_out_of_range:1"
    "table_slice_zero_step:1"
    "table_reload_in_memory_column:1"
    "table_reload_not_file_backed:1"
    "table_row_unknown_column:1"
    "table_row_unattached:1"
    "table_detached_read_unmaterialized:1"
    "table_detached_prefetch:1"
    "table_detached_materialize_all:1"
    "table_detached_reload:1"
    "table_detached_row_group_bounds:1"
    "table_mutate_unmaterialized_column:1"
    "table_mutate_unsupported_column:1"
    "table_filter_rows_mask_length:1"
    "table_delete_rows_out_of_range:1"
    "table_truncate_negative:1"
    "table_append_null_rows_negative:1"
    "table_sort_by_no_keys:1"
    "table_sort_by_flag_count_mismatch:1"
    "table_sort_by_nulls_first_count_mismatch:1"
    "table_sort_by_unknown_column:1"
    "table_sort_by_vector_column:1"
    "table_sort_by_unmaterialized_key:1"
    "table_append_unknown_column:1"
    "table_append_kind_mismatch:1"
    "table_append_width_mismatch:1"
    "table_append_unit_mismatch:1"
    "table_append_row_no_common_column:1"
    "table_set_element_row_out_of_range:1"
    "table_set_element_kind_mismatch:1"
    "table_set_null_row_out_of_range:1"
    "table_rename_duplicate_name:1"
    "table_rename_blank_name:1"
    "table_cast_unsupported_kind:1"
    "table_cast_duplicate_name:1"
    "table_cast_blank_name:1"
    "table_cast_lossy_value:1"
    "table_clone_type_mismatch:1"
    "table_row_unsupported_column:1"
    "table_row_string_kind_mismatch:1"
    "table_row_kind_mismatch:1"
    "table_get_slice_kind_mismatch:1"
    "table_remap_unknown_file_column:1"
    "table_remap_duplicate_internal:1"
    "col_size_overflow:1"
    "col_size_and_row_mode_avoid_whole_column_read:0"
    "list_width_never_reads_whole_column:0"
    "whole_column_read_forced_error_control:1"
    "read_array_full_bool_type_mismatch:1"
    "read_array_full_string_type_mismatch:1"
    "read_array_row_mode_bool_type_mismatch:1"
    "read_array_row_mode_string_type_mismatch:1"
    "read_array_element_mode_filtered_bool_col_index_out_of_range:1"
    "read_array_element_mode_filtered_bool_type_mismatch:1"
    "read_array_element_mode_filtered_string_col_index_out_of_range:1"
    "read_array_element_mode_filtered_string_type_mismatch:1"
    "read_array_element_mode_bool_col_index_out_of_range:1"
    "read_array_element_mode_bool_type_mismatch:1"
    "read_array_element_mode_string_col_index_out_of_range:1"
    "read_array_element_mode_string_type_mismatch:1"
    "read_array_column_chunk_bool_type_mismatch:1"
    "read_array_column_chunk_string_type_mismatch:1"
    "read_array_element_mode_filtered_int32_col_index_out_of_range:1"
    "read_array_element_mode_int32_col_index_out_of_range:1"
    "list_element_count_explicit_chunk_size_overflow:1"
    "row_group_explicit_nrows_overflow:1"
    "row_group_dangling_at_close:1"
    "row_group_whole_column_undercovered:1"
    "row_group_whole_column_overrun:1"
    "row_group_new_column_after_first:1"
    "row_group_whole_column_after_streaming_started:1"
    "row_group_started_while_open:1"
    "column_count_overflow:1"
    "prefetch_unknown_column:1"
    "filter_unknown_column:1"
    "filter_vector_column:1"
    "filter_malformed_rule:1"
    "filter_rule_too_long:1"
    "filter_bad_numeric_value:1"
    "filter_bad_numeric_value_scoped:1"
    "filter_int32_value_out_of_range:1"
    "filter_bad_numeric_value_float:1"
    "filter_unquoted_string_value:1"
    "filter_bad_boolean_value:1"
    "filter_boolean_value_must_be_unquoted:1"
    "filter_bool_ordering_not_supported:1"
    "filter_is_nan_non_float_column:1"
    "filter_nan_literal_rejected:1"
    "filter_is_nan_missing_combinator:1"
    "filter_unsupported_column_type:1"
    "sort_unsupported_column_type:1"
    "filter_temporal_value_not_quoted:1"
    "filter_unbalanced_parens:1"
    "filter_stray_close_paren:1"
    "filter_empty_parens:1"
    "filter_dangling_and:1"
    "filter_leading_or:1"
    "filter_not_without_operand:1"
    "filter_missing_combinator:1"
    "filter_nesting_too_deep:1"
    "filter_too_many_nodes:1"
    "filter_temporal_bad_iso_literal:1"
    "filter_temporal_literal_too_precise:1"
    "filter_set_filter_after_read:1"
    "filter_set_filter_twice:1"
    "filter_unterminated_quote:1"
    "filter_empty_rule:1"
    "filter_expected_close_paren:1"
    "filter_close_paren_as_clause:1"
    "filter_leaf_too_long:1"
    "filter_too_many_nodes_across_adds:1"
    "filter_scope_out_of_range:1"
    "filter_scope_reversed:1"
    "filter_row_element_mode_no_whole_column_read:0"
    "filter_scoped_reads_no_whole_column:0"
    "sort_unknown_column:1"
    "sort_vector_column:1"
    "sort_empty_key:1"
    "sort_bad_direction:1"
    "sort_minus_only:1"
    "sort_name_too_long:1"
    "sort_two_direction_words:1"
    "sort_minus_and_direction:1"
    "sort_key_too_long:1"
    "sort_too_many_keys:1"
    "sort_chunked_read:1"
    "sort_chunked_read_string:1"
    "sort_chunked_read_vector:1"
    "sort_chunked_read_temporal:1"
    "sort_get_chunk_size:1"
    "sort_set_sort_twice:1"
    "sort_set_sort_after_read:1"
    "sample_negative_fraction:1"
    "sample_nan_fraction:1"
    "print_stat_sampled_rows:0"
    "print_stat_released_column:0"
    "print_stat_sorted_rows:0"
    "sample_mask_build_error:1"
    "string_length_on_non_string_column:1"
    "qc_range_violation_warns:0"
    "qc_range_violation_string_warns:0"
    "qc_range_violation_float_warns:0"
    "extended_qc_range_violation_warns:0"
    "qc_range_violation_int64_warns:0"
    "qc_maml_stray_no_colon_line:0"
    "qc_null_violation_warns:0"
    "qc_range_violation_hard_aborts:1"
    "qc_range_violation_string_hard_aborts:1"
    "qc_range_violation_float_hard_aborts:1"
    "qc_null_violation_hard_aborts:1"
    "qc_miss_null_no_warning:0"
    "qc_existing_null_abort_unchanged:1"
    "qc_column_not_in_file:0"
    "qc_disabled_explicit_no_warning:0"
    "qc_maml_bad_miss_value:1"
    "qc_maml_duplicate_field:1"
    "qc_maml_missing_name:1"
    "qc_maml_unknown_subkey:1"
    "maml_line_too_long:1"
    "write_row_count_mismatch:1"
    "read_row_count_mismatch:1"
    "read_before_open:1"
    "write_before_open:1"
    "get_nrows_before_open:1"
    "close_reader_before_open:1"
    "close_writer_before_open:1"
    "close_writer_missing_write:1"
    "close_writer_missing_write_unnamed_schema:1"
    "read_unknown_column:1"
    "read_nested_struct_field_not_found:1"
    "read_nested_struct_path_not_a_struct:1"
    "read_nested_struct_intermediate_not_leaf:1"
    "nested_struct_shares_cached_read:0"
    "open_reader_missing_file:1"
    "open_reader_nrows_zero_rows:1"
    "open_writer_bad_path:1"
    "set_max_threads_below_one:1"
    "qc_warning_numeric:0"
    "qc_warning_fractional_bound:0"
    "qc_warning_string:0"
    "qc_silently_ignored_for_boolean:0"
    "qc_miss_default_active_numeric_warns:0"
    "qc_miss_declared_null_no_warning:0"
    "qc_miss_string_warns:0"
    "qc_miss_temporal_warns:0"
    "add_field_qc_drives_reader_enforcement:0"
    "get_metadata_missing_key_no_default:1"
    "get_metadata_conversion_failure_no_default:1"
    "get_metadata_missing_int64_no_default:1"
    "get_metadata_missing_float32_no_default:1"
    "get_metadata_missing_float64_no_default:1"
    "get_metadata_missing_logical_no_default:1"
    "get_metadata_missing_string_no_default:1"
    "get_metadata_conversion_int64_no_default:1"
    "get_metadata_conversion_float32_no_default:1"
    "get_metadata_conversion_float64_no_default:1"
    "get_metadata_conversion_logical_no_default:1"
    "get_metadata_missing_int32_array_no_default:1"
    "get_metadata_conversion_int32_array_no_default:1"
    "get_metadata_missing_int64_array_no_default:1"
    "get_metadata_conversion_int64_array_no_default:1"
    "get_metadata_missing_float32_array_no_default:1"
    "get_metadata_conversion_float32_array_no_default:1"
    "get_metadata_missing_float64_array_no_default:1"
    "get_metadata_conversion_float64_array_no_default:1"
    "get_metadata_missing_logical_array_no_default:1"
    "get_metadata_conversion_logical_array_no_default:1"
    "get_metadata_missing_string_array_no_default:1"
    "schema_add_field_before_init:1"
    "schema_init_twice:1"
    "schema_init_after_maml_parse:1"
    "parse_maml_file_after_init:1"
    "schema_init_empty_table:1"
    "schema_add_field_empty_name:1"
    "schema_add_field_duplicate_name:1"
    "schema_add_field_invalid_data_type:1"
    "schema_add_field_qc_min_reversed_operator:1"
    "schema_add_field_qc_max_reversed_operator:1"
    "schema_add_field_qc_operator_without_value:1"
    "schema_add_field_qc_max_operator_without_value:1"
    "schema_add_field_bad_qc_miss_value:1"
    "get_field_by_name_not_found:1"
    "get_field_by_index_out_of_range:1"
    "add_field_from_source_not_found:1"
    "print_schema_info_no_unit_no_filename:1"
    "print_schema_info_unit_not_open:1"
    "print_schema_info_unit_read_only:1"
    "print_schema_info_unit_filename_mismatch:1"
    "print_schema_info_uninitialized_schema:1"
    "print_schema_info_open_failure:1"
    "schema_add_metadata_before_parse:1"
    "string_column_index_out_of_range:1"
    "string_column_view_all_size_mismatch:1"
    "string_column_get_null:1"
    "string_column_to_character_null:1"
    "string_handle_unassociated:1"
    "string_handle_stale_index:1"
    "string_set_null_unassociated:1"
    "string_set_null_stale_index:1"
    "string_slice_invalid_range:1"
    "string_view_slice_invalid_range:1"
    "string_view_slice_size_mismatch:1"
    "string_build_from_self_alias:1"
    "string_build_from_unassociated:1"
    "string_build_from_stale_index:1"
    "string_column_append_buffers_offset_not_zero:1"
    "string_column_append_buffers_offset_not_zero_int32:1"
    "compact_string_write_requires_scalar_column:1"
    "compact_string_write_chunk_requires_scalar_column:1"
    "extended_uint32_overflow_int32:1"
    "extended_uint64_overflow_int32:1"
    "extended_uint64_overflow_int64:1"
    "extended_real_nonintegral_int32:1"
    "extended_real_overflow_int32:1"
    "extended_real_nonintegral_int64:1"
    "extended_real_overflow_int64:1"
    "extended_decimal_nonintegral_int32:1"
    "extended_decimal_overflow_int32:1"
    "extended_decimal_nonintegral_int64:1"
    "extended_decimal_overflow_int64:1"
    "temporal_date_set_invalid_month:1"
    "temporal_date_set_invalid_day:1"
    "temporal_date_set_out_of_range:1"
    "temporal_date_set_mjd_out_of_range:1"
    "temporal_date_parse_invalid:1"
    "temporal_date_null_get:1"
    "temporal_date_null_comparison:1"
    "temporal_time_set_invalid_hour:1"
    "temporal_time_set_invalid_nanosecond:1"
    "temporal_time_set_raw_out_of_range:1"
    "temporal_time_parse_invalid:1"
    "temporal_time_null_get:1"
    "temporal_ts_set_invalid_day:1"
    "temporal_ts_parse_invalid:1"
    "temporal_ts_null_to_unix:1"
    "temporal_ts_null_comparison:1"
    "temporal_ts_to_unix_precision_loss:1"
    "temporal_ts_to_unix_overflow:1"
    "temporal_ts_set_mjd_out_of_range:1"
    "temporal_ts_set_raw_invalid_nanoseconds:1"
    "temporal_invalid_time_unit:1"
    "temporal_ts_get_year_overflow:1"
    "temporal_write_time_precision_loss:1"
    "temporal_protected_col_null:1"
    "temporal_read_date_via_int32:1"
    "temporal_read_int32_via_date:1"
    "temporal_foreign_int96_roundtrip:0"
    "temporal_foreign_tz_roundtrip:0"
    "list_type_foreign_fixture:0"
    "schema_add_field_date_with_unit:1"
    "validate_qc_on_temporal_column:1"
    "schema_add_field_seconds_unit_rejected:1"
    "schema_add_field_time_utc_rejected:1"
    "schema_add_field_unclosed_bracket_rejected:1"
    "temporal_date_eq_null:1"
    "temporal_time_get_null:1"
    "temporal_time_minute_null:1"
    "temporal_time_second_null:1"
    "temporal_time_nanosecond_null:1"
    "temporal_time_eq_null:1"
    "temporal_time_lt_null:1"
    "temporal_date_year_null:1"
    "temporal_date_month_null:1"
    "temporal_date_day_null:1"
    "temporal_date_to_mjd_null:1"
    "temporal_date_to_string_null:1"
    "temporal_time_to_string_null:1"
    "temporal_ts_set_invalid_month:1"
    "temporal_ts_set_invalid_nanosecond:1"
    "temporal_ts_get_null:1"
    "temporal_ts_get_date_range_exceeded:1"
    "temporal_ts_to_unix_overflow_negative:1"
    "temporal_ts_to_mjd_null:1"
    "temporal_ts_to_string_null:1"
    "temporal_ts_lt_null:1"
    "temporal_date_diff_null:1"
    "temporal_date_offset_null:1"
    "temporal_date_offset_out_of_range:1"
    "temporal_date_offset_int64_overflow_positive:1"
    "temporal_date_offset_int64_overflow_negative:1"
    "temporal_date_sub_int64_min:1"
    "temporal_time_diff_null:1"
    "temporal_time_offset_null:1"
    "temporal_time_offset_magnitude_add:1"
    "temporal_time_offset_magnitude_sub:1"
    "temporal_ts_diff_ns_null:1"
    "temporal_ts_diff_ns_overflow:1"
    "temporal_ts_diff_seconds_null:1"
    "temporal_ts_offset_null:1"
    "temporal_ts_offset_ns_overflow:1"
    "temporal_ts_offset_seconds_overflow_positive:1"
    "temporal_ts_offset_seconds_overflow_negative:1"
    "temporal_ts_sub_int64_min:1"
    "temporal_write_column_not_defined:1"
    "temporal_write_array_size_mismatch:1"
    "temporal_write_type_mismatch:1"
    "temporal_chunk_column_not_defined:1"
    "temporal_chunk_array_size_mismatch:1"
    "temporal_chunk_type_mismatch:1"
    "mask_row_mask_after_write_started:1"
    "mask_row_mask_shape_mismatch:1"
    "mask_row_mask_zero_length:1"
    "mask_row_mask_called_twice:1"
    "mask_chunk_row_mask_after_row_mask:1"
    "mask_row_mask_after_chunk_row_mask:1"
    "mask_chunk_row_mask_after_whole_column:1"
    "mask_chunk_row_mask_not_used_every_group:1"
    "mask_chunk_row_mask_introduced_late:1"
    "mask_chunk_row_mask_called_twice:1"
    "mask_chunk_row_mask_size_mismatch:1"
    "mask_row_mask_window_exhausted:1"
    "mask_row_mask_not_fully_consumed:1"
    "mask_chunk_row_mask_no_row_group_open:1"
    "mask_chunk_row_mask_scheme_declined:1"
    "mask_row_group_no_writes_at_all:1"
    "get_version_invalid_mode:1"
    "column_exists_bad_type_token:1"
    "column_exists_empty_type_filter:1"
    "get_column_type_unsupported:1"
    "col_size_malformed_value:1"
    "array_size_malformed_value:1"
    "array_size_auto_on_non_string:1"
    "set_col_size_non_positive:1"
    "set_col_size_already_resolved_no_force:1"
    "set_array_size_non_string_column:1"
    "set_array_size_non_positive:1"
    "set_array_size_already_resolved_no_force:1"
    "flat_write_col_size_still_auto:1"
)

# concurrent_calls_into_shared_reader/writer are deliberately not in the list
# above: they only reliably trigger under genuine multi-threaded execution (a
# real OpenMP flag supplied via FPM_FFLAGS -- see README's "Thread safety"
# section), which this script does not assume. When OpenMP is not active the
# scenarios detect that (omp_get_max_threads() <= 1) and skip cleanly. They are
# run separately below, sequentially (not part of the parallel batch -- they
# specifically probe OpenMP thread contention, and running them alongside a
# pool of other concurrent processes would only add timing noise), and do not
# count towards failures whether they abort (guard fired) or skip (no real
# concurrency available).
# table_first_touch_in_parallel and table_resolve_width_in_parallel join them
# for the same reason: without a real OpenMP flag there is no parallel region
# for the RF4 guard to notice, so the scenario simply reads the column and
# exits 0.
#
# table_first_touch_in_parallel_single/table_resolve_width_in_parallel_single
# are the deterministic (single-touching-thread, via !$omp single) siblings of
# the two above: they still need a real OpenMP flag for their team of 2 to be
# an "active" parallel region at all (same skip-and-exit-0 fallback otherwise),
# so they belong in this same best-effort bucket rather than the strict,
# exact-stderr-checked list above -- but unlike their racy siblings they do
# not depend on two threads racing into error stop's abort machinery at once,
# so they are what actually cover table_touch's/table_resolve_width's guard
# body lines (parquet_tables_read.f90) reliably under a real -fopenmp build.
concurrency_scenarios=(
    "concurrent_calls_into_shared_reader"
    "concurrent_calls_into_shared_writer"
    "table_first_touch_in_parallel"
    "table_resolve_width_in_parallel"
    "table_first_touch_in_parallel_single"
    "table_resolve_width_in_parallel_single"
)

echo "Building error_scenarios..."
if ! fpm build --tests 2>&1 | tail -5; then
    echo "fpm build failed" >&2
    exit 1
fi

bin="$(find "${FPM_BUILD_DIR:-build}" -type f -name error_scenarios | head -n 1)"
if [ -z "$bin" ]; then
    echo "could not locate the built error_scenarios binary under build/" >&2
    exit 1
fi

mkdir -p test_run
results_dir="$(mktemp -d test_run/run_error_scenarios_results.XXXXXX)"
trap 'rm -rf "$results_dir"' EXIT

# Number of scenarios to run concurrently -- override with
# RUN_ERROR_SCENARIOS_JOBS=N if the default (one per logical CPU) is too
# aggressive for a given machine.
jobs_n="${RUN_ERROR_SCENARIOS_JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}"

idx=0
tokens=()
for entry in "${scenarios[@]}"; do
    scenario="${entry%%:*}"
    expect_abort="${entry##*:}"
    idx=$((idx + 1))
    tokens+=("$idx" "$scenario" "$expect_abort")
done

printf '%s\n' "${tokens[@]}" | xargs -P "$jobs_n" -n 3 "$0" __worker__ "$bin" "$results_dir"

failures=0
i=1
while [ "$i" -le "$idx" ]; do
    echo "$(cat "$results_dir/$i.line")"
    if [ "$(cat "$results_dir/$i.status")" = "FAIL" ]; then
        failures=$((failures + 1))
    fi
    i=$((i + 1))
done

echo
echo "Concurrency scenarios (best-effort, need FPM_FFLAGS with a real OpenMP flag to reliably trigger):"
for scenario in "${concurrency_scenarios[@]}"; do
    if "$bin" "$scenario" > /dev/null 2>&1; then
        printf "[INFO] %-50s did not abort (skipped or single-threaded: needs genuine OpenMP concurrency)\n" "$scenario"
    else
        printf "[PASS] %-50s aborted as expected\n" "$scenario"
    fi
done

echo
if [ "$failures" -eq 0 ]; then
    echo "All error scenarios behaved as expected."
    exit 0
else
    echo "$failures scenario(s) did not behave as expected."
    exit 1
fi
