!> The HEALPix sphere pixelisation: position <-> pixel, scheme conversion, and disc queries.
!!
!! HEALPix divides the sphere into `12*nside**2` pixels of exactly equal area, arranged on rings of
!! constant latitude. `parquet_healpix` implements the part of it a program actually needs to hold
!! sky data on a grid: converting a direction to the pixel containing it and back, converting
!! between the two pixel-numbering schemes, and enumerating the pixels of a disc.
!!
!! **Written from the published algorithm, not translated from any implementation.** The
!! pixelisation is described completely in Gorski et al. 2005, ApJ 622, 759, and the geometry is
!! elementary; every formula here was derived from that paper and then checked against reference
!! vectors (`test/test_healpix_vectors.f90`, generated by `tools/generate_healpix_reference.py`).
!! No HEALPix source was consulted while writing this module, and none should be if it is ever
!! re-derived -- the paper plus the vectors are sufficient, and they are what keeps this library
!! BSD-3-Clause while `libhealpix` is GPL-2.0.
!!
!! **This module is Arrow-free by construction and that is the point of its tier.** It reaches
!! `iso_fortran_env`, `ieee_arithmetic` and `parquet_settings_base`, and nothing else, so
!! `use parquet_healpix` in a downstream project compiles six Fortran files rather than the
!! sixty-odd the reader/writer stack costs. `check_parquet_healpix_stays_arrow_free`
!! (tools/check_source_conventions.py) and `tools/module_footprints.txt` are what keep that true --
!! a `use` line added here can silently multiply what every consumer compiles, and no test can see
!! it happen.
!!
!! **No module state, no saved variables, no lazy initialisation.** Every procedure here is a
!! function of its arguments alone, so the whole module is thread-safe with nothing to arrange and
!! the scalar conversions are `pure elemental`. Do not add a cache: a `logical, save :: ready`
!! reached from inside a parallel region is a check-then-act on shared state.
!!
!! **Two conventions a caller must get right, and neither has a default this module can pick:**
!!
!! * `theta` is COLATITUDE from the north pole in radians, so `theta = pi/2 - dec`. A mirrored
!!   frame (`theta = pi/2 + dec`) is in live use in several projects that feed this module, and is
!!   self-consistent -- a reflection preserves angular distance -- but mixing the two searches the
!!   wrong hemisphere silently. This module takes HEALPix-native `theta`/`phi` and unit vectors
!!   only, and offers no RA/Dec layer, precisely so that the choice stays visible at each call.
!! * A pixel INDEX runs `0 .. 12*nside**2 - 1`, as the pixelisation itself defines it. The
!!   `listpix` array `pf_query_disc` fills is 1-based, like every other user-facing array in this
!!   library. The array base and the pixel base are different things and are the pair most easily
!!   conflated: `listpix(1)` holds the first pixel found, and its VALUE may well be 0.
module parquet_healpix
    use, intrinsic :: iso_fortran_env, only: int32, int64, real64
    use, intrinsic :: ieee_arithmetic, only: ieee_is_nan, ieee_is_finite
    use parquet_settings_base, only: parquet_set_verbosity, parquet_get_verbosity, &
        parquet_set_message_stream, parquet_get_message_stream, &
        parquet_clamp_to_affinity, parquet_auto_thread_count
    implicit none
    private

    public :: PF_HP_RING, PF_HP_NEST
    public :: pf_ang2pix_ring, pf_ang2pix_nest
    public :: pf_pix2ang_ring, pf_pix2ang_nest
    public :: pf_pix2vec_ring, pf_pix2vec_nest
    public :: pf_ring2nest, pf_nest2ring
    public :: pf_query_disc, pf_query_disc_count, pf_query_disc_alloc
    public :: pf_angdist
    public :: pf_max_pixrad
    !
    ! ---- Tier B ----
    !
    public :: pf_ang2vec, pf_vec2ang
    public :: pf_vec2pix_ring, pf_vec2pix_nest
    public :: pf_nside2npix, pf_npix2nside
    public :: pf_nside2order, pf_order2nside
    public :: pf_nside2pixarea, pf_nside2resol
    public :: pf_pix2ring_ring, pf_pix2ring_nest, pf_ring2z
    public :: pf_ud_pix_nest
    public :: pf_chord2_from_angle, pf_angle_from_chord2
    public :: pf_ang2pix_ring_bulk, pf_ang2pix_nest_bulk
    public :: pf_pix2ang_ring_bulk, pf_pix2ang_nest_bulk
    public :: pf_vec2pix_ring_bulk, pf_vec2pix_nest_bulk
    public :: pf_pix2vec_ring_bulk, pf_pix2vec_nest_bulk
    public :: pf_ang2vec_bulk, pf_vec2ang_bulk
    !
    ! ---- Settings this module's own code reads, re-exported so a narrow import can configure it ----
    !
    !> The output pair, because `pf_query_disc`'s bulk siblings emit a thread-clamp warning through
    !! the same channel every other tier does. Re-exported here so a program whose only import is
    !! `use parquet_healpix` can silence it without naming `parquet_settings` -- which would put the
    !! C++ boundary, and with it Arrow, back into an otherwise Arrow-free build.
    public :: parquet_set_verbosity, parquet_get_verbosity
    public :: parquet_set_message_stream, parquet_get_message_stream

    ! ---- Scheme selectors ----

    !> RING scheme: pixels numbered along rings of constant latitude, north to south.
    !!
    !! Index order follows latitude, which is what makes a declination band one contiguous range of
    !! indices. `pf_query_disc` returns RING results in ascending index order.
    integer, parameter :: PF_HP_RING = 0
    !> NEST scheme: pixels numbered so that the four children of a pixel at the next resolution are
    !! consecutive.
    !!
    !! A resolution change is a bit shift in this scheme, which is what makes it the right choice
    !! for hierarchical work. `pf_query_disc` does not promise any particular order for NEST output.
    integer, parameter :: PF_HP_NEST = 1

    ! ---- Kind and range limits ----

    !> Largest `nside` whose pixel indices still fit `integer(int32)`.
    !!
    !! `12*8192**2` is 805306368; the next power of two overflows a signed 32-bit index, so the
    !! int32 specifics refuse it rather than wrapping.
    integer(int64), parameter :: hpx_nside_max_i32 = 8192_int64
    !> Largest `nside` this module accepts at all, in either kind.
    !!
    !! `2**29` matches the ceiling the HEALPix ecosystem itself uses and keeps every intermediate
    !! inside `integer(int64)`: `npix` is `3*2**60`, the Morton interleave of two 29-bit
    !! coordinates occupies 58 bits, the face offset reaches `11*4**29 < 2**62`, and the cap-ring
    !! inversion's square-root argument stays below 7e18, where a double still resolves it to
    !! better than one part in a ring.
    integer(int64), parameter :: hpx_nside_max = 536870912_int64

    ! ---- Mathematical constants ----

    !> pi.
    real(real64), parameter :: hpx_pi = 3.141592653589793238462643_real64
    !> pi/2.
    real(real64), parameter :: hpx_halfpi = 0.5_real64 * hpx_pi
    !> 2*pi.
    real(real64), parameter :: hpx_twopi = 2.0_real64 * hpx_pi
    !> The |z| at which the polar caps meet the equatorial belt.
    real(real64), parameter :: hpx_twothird = 2.0_real64 / 3.0_real64
    !> `sqrt(pi/3)`, the constant in `pf_nside2resol`.
    !!
    !! A compile-time constant so that the resolution costs one division and contains no `sqrt` of
    !! a runtime value -- one less thing to reason about for the module's IEEE promise.
    real(real64), parameter :: hpx_sqrt_pi_third = 1.023326707946488151_real64

    !> Largest resolution order, `log2(hpx_nside_max)`.
    integer(int64), parameter :: hpx_order_max = 29_int64
    !> Largest resolution order whose `nside` the int32 entry points accept, `log2(8192)`.
    integer(int32), parameter :: hpx_order_max_i32 = 13_int32

    ! ---- Morton-order bit masks ----
    !
    ! The NEST index interleaves the bits of a pixel's two within-face coordinates. Spreading and
    ! compacting them is done with the standard five-step mask sequence rather than a lookup table,
    ! which keeps the codec branch-free and -- more to the point here -- keeps the module free of
    ! any data at all, so there is nothing for a parallel region to share.

    !> Bit mask 0x00000000FFFFFFFF.
    integer(int64), parameter :: hpx_m32 = int(z'00000000FFFFFFFF', int64)
    !> Bit mask 0x0000FFFF0000FFFF.
    integer(int64), parameter :: hpx_m16 = int(z'0000FFFF0000FFFF', int64)
    !> Bit mask 0x00FF00FF00FF00FF.
    integer(int64), parameter :: hpx_m8 = int(z'00FF00FF00FF00FF', int64)
    !> Bit mask 0x0F0F0F0F0F0F0F0F.
    integer(int64), parameter :: hpx_m4 = int(z'0F0F0F0F0F0F0F0F', int64)
    !> Bit mask 0x3333333333333333.
    integer(int64), parameter :: hpx_m2 = int(z'3333333333333333', int64)
    !> Bit mask 0x5555555555555555 -- the even bit positions.
    integer(int64), parameter :: hpx_m1 = int(z'5555555555555555', int64)

    ! ---- Per-face ring and phi offsets ----
    !
    ! Faces 0-3 are the north cap, 4-7 the equatorial belt, 8-11 the south cap. These two tables
    ! place each face's centre on the (ring, index-in-ring) grid, and are what the NEST <-> RING
    ! conversions are built from.

    !> Ring offset of each face centre, in units of `nside`.
    integer(int64), parameter :: hpx_jrll(0:11) = [2_int64, 2_int64, 2_int64, 2_int64, &
        3_int64, 3_int64, 3_int64, 3_int64, 4_int64, 4_int64, 4_int64, 4_int64]
    !> Longitude offset of each face centre, in units of a ring's quarter width.
    integer(int64), parameter :: hpx_jpll(0:11) = [1_int64, 3_int64, 5_int64, 7_int64, &
        0_int64, 2_int64, 4_int64, 6_int64, 1_int64, 3_int64, 5_int64, 7_int64]

    ! ---- Public generic interfaces ----

    !> Pixel containing the direction `(theta, phi)`, in the RING scheme.
    !!
    !! `nside` is a positive power of two, `theta` is colatitude in radians (0 at the north pole,
    !! pi at the south), `phi` is longitude in radians and may lie outside `[0, 2*pi)`. `ipix`
    !! comes back in the same integer kind as `nside`, in `0 .. 12*nside**2 - 1`.
    !!
    !! **Total and `pure elemental`: it validates nothing and never aborts.** An `nside` that is
    !! not a positive power of two, or a `theta` outside `[0, pi]`, produces a meaningless result
    !! rather than an error -- `pf_ang2pix_ring(0, ...)` returns nonsense. That is deliberate: this
    !! is the per-element hot path, and validation belongs in the once-per-query entry points
    !! (`pf_query_disc`), which check `nside` once before their walk. A NaN angle propagates into
    !! the integer conversion, which may raise `IEEE_INVALID`; every OTHER path in this module is
    !! free of IEEE exceptions on validated input.
    interface pf_ang2pix_ring
        module procedure hpx_ang2pix_ring_i32
        module procedure hpx_ang2pix_ring_i64
    end interface pf_ang2pix_ring

    !> Pixel containing the direction `(theta, phi)`, in the NEST scheme.
    !!
    !! Arguments and kinds are `pf_ang2pix_ring`'s, and so is the total, non-validating contract:
    !! see that procedure for the full statement of both.
    interface pf_ang2pix_nest
        module procedure hpx_ang2pix_nest_i32
        module procedure hpx_ang2pix_nest_i64
    end interface pf_ang2pix_nest

    !> Direction of a RING pixel's centre, as `(theta, phi)` in radians.
    !!
    !! `ipix` is a RING index in `0 .. 12*nside**2 - 1`, in the same kind as `nside`. `theta` comes
    !! back in `[0, pi]` and `phi` in `[0, 2*pi)`.
    !!
    !! **Total and `pure elemental`, exactly as `pf_ang2pix_ring` is** -- an out-of-range `ipix`
    !! gives a meaningless answer rather than an abort.
    !!
    !! **Near the poles at very high resolution, `theta` carries fewer digits than `phi` does**, and
    !! that is inherent rather than a defect here: a ring's centre is defined by its `z`, and
    !! `theta = acos(z)` loses about half the significant digits when `z` is within an ulp or two of
    !! +-1. At `nside = 2**20` the first ring's `z` is `1 - 3e-13`, so `theta` is good to about
    !! 4e-10 rather than to an ulp. Work in `z`, or in unit vectors through `pf_pix2vec_ring`, when
    !! that matters.
    interface pf_pix2ang_ring
        module procedure hpx_pix2ang_ring_i32
        module procedure hpx_pix2ang_ring_i64
    end interface pf_pix2ang_ring

    !> Direction of a NEST pixel's centre, as `(theta, phi)` in radians.
    !!
    !! Arguments, kinds, contract and polar-precision caveat are `pf_pix2ang_ring`'s.
    interface pf_pix2ang_nest
        module procedure hpx_pix2ang_nest_i32
        module procedure hpx_pix2ang_nest_i64
    end interface pf_pix2ang_nest

    !> Unit vector of a RING pixel's centre.
    !!
    !! `vec` is the Cartesian direction `(x, y, z)` of the pixel centre. **This is the primitive
    !! form and `pf_pix2ang_ring` is derived from it**, not the other way round: the centre is
    !! built from the ring's `z` directly, with no `acos`/`cos` round trip. That is load-bearing
    !! rather than an optimisation -- a round trip moves a centre lying exactly on a disc's rim to
    !! the wrong side of it, which flips a whole equatorial ring in or out of a pole-centred
    !! hemisphere.
    !!
    !! Total and `pure`; not `elemental`, because the result is an array.
    interface pf_pix2vec_ring
        module procedure hpx_pix2vec_ring_i32
        module procedure hpx_pix2vec_ring_i64
    end interface pf_pix2vec_ring

    !> Unit vector of a NEST pixel's centre.
    !!
    !! Arguments, kinds and contract are `pf_pix2vec_ring`'s.
    interface pf_pix2vec_nest
        module procedure hpx_pix2vec_nest_i32
        module procedure hpx_pix2vec_nest_i64
    end interface pf_pix2vec_nest

    !> RING pixel index -> NEST pixel index, at the same `nside`.
    !!
    !! `ipring` and `ipnest` are both in `0 .. 12*nside**2 - 1` and in the same kind as `nside`.
    !! Exact integer arithmetic throughout -- no direction is computed and nothing rounds. Total
    !! and `pure elemental`, so an out-of-range input gives a meaningless answer rather than an
    !! abort.
    interface pf_ring2nest
        module procedure hpx_ring2nest_i32
        module procedure hpx_ring2nest_i64
    end interface pf_ring2nest

    !> NEST pixel index -> RING pixel index, at the same `nside`.
    !!
    !! The exact inverse of `pf_ring2nest`; same kinds, same total contract.
    interface pf_nest2ring
        module procedure hpx_nest2ring_i32
        module procedure hpx_nest2ring_i64
    end interface pf_nest2ring

    !> Largest angular distance from a pixel centre to one of its own corners, in radians.
    !!
    !! **The margin `pf_query_disc`'s `inclusive = .true.` mode enlarges its radius by, and the
    !! bound that mode publishes** -- so it is also the honest way to size a search margin around a
    !! position, where code of this kind often carries a rule-of-thumb factor instead.
    !!
    !! Attained on the first equatorial ring, whose pixels are the most elongated, at the corner
    !! lying on the quadrant meridian. `nside` takes either integer kind; the result is `real64`.
    !!
    !! `pure elemental` and total: it validates nothing, so an `nside` that is not a positive power
    !! of two gives a meaningless answer rather than an error, exactly as the conversions do.
    interface pf_max_pixrad
        module procedure hpx_max_pixrad_i32
        module procedure hpx_max_pixrad_i64
    end interface pf_max_pixrad

    !> Pixels of a disc: every pixel within `radius` of the direction `vec`.
    !!
    !! **The one entry point here that validates its arguments**, and the one that aborts. See
    !! `hpx_query_disc_i64` for the full contract: the two `inclusive` modes, the ordering promise
    !! (ascending for `PF_HP_RING`, unspecified for `PF_HP_NEST`), the 1-based `listpix` against
    !! 0-based pixel values, and every condition that stops the run.
    interface pf_query_disc
        module procedure hpx_query_disc_i32
        module procedure hpx_query_disc_i64
    end interface pf_query_disc

    !> How many pixels a disc holds, without materialising the list.
    !!
    !! Answers exactly the `nlist` that `pf_query_disc` would report for the same arguments, and
    !! does it by running the same walk with its stores switched off -- so the two cannot disagree,
    !! and sizing a buffer from this needs no margin. It touches no output array at all, so there
    !! is nothing to overflow and no capacity abort.
    !!
    !! Validates its arguments exactly as `pf_query_disc` does, minus the buffer check, and every
    !! message names this routine. `scheme` and `inclusive` are optional with the same defaults
    !! (`PF_HP_RING`, `.false.`); `scheme` changes nothing about the count and is accepted so that
    !! one call can be switched between the three entry points without editing its arguments.
    interface pf_query_disc_count
        module procedure hpx_query_disc_count_i32
        module procedure hpx_query_disc_count_i64
    end interface pf_query_disc_count

    !> Pixels of a disc, into an array this routine allocates to the exact size needed.
    !!
    !! **The form that removes the buffer-too-small failure entirely.** `listpix` comes back
    !! `allocated` with `size(listpix) == nlist`, so there is no capacity to get wrong and no abort
    !! for getting it wrong -- against `pf_query_disc`, where sizing the buffer is the caller's
    !! problem and every downstream project has invented its own answer to it.
    !!
    !! **An empty result allocates a ZERO-LENGTH array, never an unallocated one**, so `size()` is
    !! the only thing a caller ever has to test and an `if (.not. allocated(listpix))` branch
    !! written against this API is dead code.
    !!
    !! **It walks the disc TWICE** -- once to count, once to emit -- which is what buys the exact
    !! size with no allocation inside the ring loop and no over-allocation. Where that matters,
    !! `pf_query_disc` into a reused buffer is the form to use: it is the hot-path shape and it is
    !! not going away. Everything else should prefer this one.
    !!
    !! Contract, ordering, the inclusive bound and the small-disc limit are all exactly
    !! `pf_query_disc`'s; only the buffer's ownership differs.
    interface pf_query_disc_alloc
        module procedure hpx_query_disc_alloc_i32
        module procedure hpx_query_disc_alloc_i64
    end interface pf_query_disc_alloc

    ! ---- Interfaces: position <-> pixel ----
    !
    ! Implemented in submodule parquet_healpix_core.

    interface
        !> RING pixel for a direction, int32 kinds. See the `pf_ang2pix_ring` generic.
        pure elemental module subroutine hpx_ang2pix_ring_i32(nside, theta, phi, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int32), intent(out) :: ipix !! RING pixel index, 0-based.
        end subroutine hpx_ang2pix_ring_i32

        !> RING pixel for a direction, int64 kinds. See the `pf_ang2pix_ring` generic.
        pure elemental module subroutine hpx_ang2pix_ring_i64(nside, theta, phi, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int64), intent(out) :: ipix !! RING pixel index, 0-based.
        end subroutine hpx_ang2pix_ring_i64

        !> NEST pixel for a direction, int32 kinds. See the `pf_ang2pix_nest` generic.
        pure elemental module subroutine hpx_ang2pix_nest_i32(nside, theta, phi, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int32), intent(out) :: ipix !! NEST pixel index, 0-based.
        end subroutine hpx_ang2pix_nest_i32

        !> NEST pixel for a direction, int64 kinds. See the `pf_ang2pix_nest` generic.
        pure elemental module subroutine hpx_ang2pix_nest_i64(nside, theta, phi, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int64), intent(out) :: ipix !! NEST pixel index, 0-based.
        end subroutine hpx_ang2pix_nest_i64

        !> Centre direction of a RING pixel, int32 kinds. See the `pf_pix2ang_ring` generic.
        pure elemental module subroutine hpx_pix2ang_ring_i32(nside, ipix, theta, phi)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_ring_i32

        !> Centre direction of a RING pixel, int64 kinds. See the `pf_pix2ang_ring` generic.
        pure elemental module subroutine hpx_pix2ang_ring_i64(nside, ipix, theta, phi)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_ring_i64

        !> Centre direction of a NEST pixel, int32 kinds. See the `pf_pix2ang_nest` generic.
        pure elemental module subroutine hpx_pix2ang_nest_i32(nside, ipix, theta, phi)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_nest_i32

        !> Centre direction of a NEST pixel, int64 kinds. See the `pf_pix2ang_nest` generic.
        pure elemental module subroutine hpx_pix2ang_nest_i64(nside, ipix, theta, phi)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_nest_i64

        !> Centre unit vector of a RING pixel, int32 kinds. See the `pf_pix2vec_ring` generic.
        pure module subroutine hpx_pix2vec_ring_i32(nside, ipix, vec)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_ring_i32

        !> Centre unit vector of a RING pixel, int64 kinds. See the `pf_pix2vec_ring` generic.
        pure module subroutine hpx_pix2vec_ring_i64(nside, ipix, vec)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_ring_i64

        !> Centre unit vector of a NEST pixel, int32 kinds. See the `pf_pix2vec_nest` generic.
        pure module subroutine hpx_pix2vec_nest_i32(nside, ipix, vec)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_nest_i32

        !> Centre unit vector of a NEST pixel, int64 kinds. See the `pf_pix2vec_nest` generic.
        pure module subroutine hpx_pix2vec_nest_i64(nside, ipix, vec)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_nest_i64
    end interface

    ! ---- Interfaces: scheme conversion ----
    !
    ! Implemented in submodule parquet_healpix_core.

    interface
        !> RING -> NEST, int32 kinds. See the `pf_ring2nest` generic.
        pure elemental module subroutine hpx_ring2nest_i32(nside, ipring, ipnest)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipring !! RING pixel index, 0-based.
            integer(int32), intent(out) :: ipnest !! the same pixel's NEST index.
        end subroutine hpx_ring2nest_i32

        !> RING -> NEST, int64 kinds. See the `pf_ring2nest` generic.
        pure elemental module subroutine hpx_ring2nest_i64(nside, ipring, ipnest)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipring !! RING pixel index, 0-based.
            integer(int64), intent(out) :: ipnest !! the same pixel's NEST index.
        end subroutine hpx_ring2nest_i64

        !> NEST -> RING, int32 kinds. See the `pf_nest2ring` generic.
        pure elemental module subroutine hpx_nest2ring_i32(nside, ipnest, ipring)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipnest !! NEST pixel index, 0-based.
            integer(int32), intent(out) :: ipring !! the same pixel's RING index.
        end subroutine hpx_nest2ring_i32

        !> NEST -> RING, int64 kinds. See the `pf_nest2ring` generic.
        pure elemental module subroutine hpx_nest2ring_i64(nside, ipnest, ipring)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipnest !! NEST pixel index, 0-based.
            integer(int64), intent(out) :: ipring !! the same pixel's RING index.
        end subroutine hpx_nest2ring_i64
    end interface

    ! ---- Interfaces: ring geometry and the Morton codec ----
    !
    ! Private to the module and its submodules. Implemented in parquet_healpix_core; declared here
    ! rather than contained in the module because gfortran gives a private module-contained
    ! procedure internal linkage, so a submodule calling one fails to LINK while compiling cleanly.

    interface
        !> Centre `z` of ring `i`, counted from the north pole.
        !>
        !> The single place the three regions' `z` formulas live. Every consumer of a ring's
        !> latitude -- the pixel centre, the disc walk's band test, the per-ring threshold -- goes
        !> through this one function, so the module cannot disagree with itself about where a ring
        !> is.
        pure module function hpx_ring_z(nside, i) result(z)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            real(real64) :: z !! cosine of the ring's colatitude.
        end function hpx_ring_z

        !> Where ring `i` starts, how many pixels it holds, and whether it is offset in longitude.
        pure module subroutine hpx_ring_first(nside, i, first, nr, shifted)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(out) :: first !! RING index of the ring's first pixel.
            integer(int64), intent(out) :: nr !! number of pixels on the ring.
            integer(int64), intent(out) :: shifted !! 1 when centres are offset by half a pixel.
        end subroutine hpx_ring_first

        !> Largest ring index whose centre `z` is at or above `z`; 0 when none is.
        !>
        !> Used only to bracket the disc walk's band of rings, which is then widened by one ring on
        !> each side, so an answer off by one costs three membership tests and never a wrong result.
        pure module function hpx_ring_above(nside, z) result(i)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: z !! cosine of a colatitude, in [-1, 1].
            integer(int64) :: i !! the ring index, 0 when the whole sphere lies below `z`.
        end function hpx_ring_above

        !> Ring index of a north-cap RING pixel.
        !>
        !> Inverts `p = 2*i*(i-1) + j` for `i`. The square root seeds the answer and the two
        !> single-step corrections make it exact: at `nside = 2**29` the argument reaches 7e18,
        !> where a double's relative error of 1e-16 is still far below one ring.
        pure module function hpx_cap_ring(p) result(i)
            integer(int64), intent(in) :: p !! a RING index within the north polar cap.
            integer(int64) :: i !! the ring the pixel lies on, 1-based from the pole.
        end function hpx_cap_ring

        !> RING pixel -> the ring it lies on and its position within that ring.
        pure module subroutine hpx_ring_decompose(nside, p, i, j, nr, shifted)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: p !! RING pixel index, 0-based.
            integer(int64), intent(out) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(out) :: j !! index within the ring, 0-based.
            integer(int64), intent(out) :: nr !! number of pixels on that ring.
            integer(int64), intent(out) :: shifted !! 1 when centres are offset by half a pixel.
        end subroutine hpx_ring_decompose

        !> Centre of a RING pixel as `(z, phi)`, with no `acos`/`cos` round trip.
        pure module subroutine hpx_pix2zphi_ring(nside, p, z, phi)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: p !! RING pixel index, 0-based.
            real(real64), intent(out) :: z !! cosine of the centre's colatitude.
            real(real64), intent(out) :: phi !! the centre's longitude, radians, in [0, 2*pi).
        end subroutine hpx_pix2zphi_ring

        !> `(ring, index-in-ring)` -> NEST pixel index.
        !>
        !> The half of `pf_ring2nest` that follows the ring decomposition, split out because the
        !> disc walk already knows both coordinates: going through `pf_ring2nest` there would
        !> re-derive them, paying a cap-ring inversion per emitted pixel.
        pure module function hpx_ringij2nest(nside, jr, j) result(ipnest)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: jr !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(in) :: j !! index within the ring, 0-based.
            integer(int64) :: ipnest !! the pixel's NEST index.
        end function hpx_ringij2nest

        !> Largest angular distance from a pixel centre to one of its own corners, in radians.
        !>
        !> This is the margin `pf_query_disc`'s inclusive mode enlarges its radius by, and the
        !> bound that mode publishes. It is attained on the first equatorial ring, whose pixels are
        !> the most elongated, at the corner lying on the quadrant meridian.
        pure module function hpx_max_pixrad(nside) result(r)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad

        !> Largest centre-to-corner angle at `nside`, int32 kind. See the `pf_max_pixrad` generic.
        pure elemental module function hpx_max_pixrad_i32(nside) result(r)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad_i32

        !> Largest centre-to-corner angle at `nside`, int64 kind. See the `pf_max_pixrad` generic.
        pure elemental module function hpx_max_pixrad_i64(nside) result(r)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad_i64

        !> Angular separation of two directions, in radians.
        !>
        !> `atan2(|v1 x v2|, v1.v2)` rather than `acos` of the dot product: accurate to about an ulp
        !> across the whole range, where the `acos` form loses half its digits near 0 and pi. The
        !> inputs need not be unit vectors -- the formula is scale-invariant -- and two parallel
        !> zero vectors give 0 rather than an exception.
        pure module subroutine pf_angdist(vec1, vec2, dist)
            real(real64), intent(in) :: vec1(3) !! first direction; any nonzero length.
            real(real64), intent(in) :: vec2(3) !! second direction; any nonzero length.
            real(real64), intent(out) :: dist !! the angle between them, radians, in [0, pi].
        end subroutine pf_angdist
    end interface

    ! ---- Interfaces: disc queries ----
    !
    ! Implemented in submodule parquet_healpix_query.

    interface
        !> Pixels of a disc, int32 kinds. See `hpx_query_disc_i64` for the contract.
        module subroutine hpx_query_disc_i32(nside, vec, radius, listpix, nlist, scheme, inclusive)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0.
            integer(int32), intent(out) :: listpix(:) !! filled from element 1 with 0-based indices.
            integer(int32), intent(out) :: nlist !! how many elements of `listpix` were filled.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_i32

        !> Pixels of a disc: every pixel of the pixelisation lying within `radius` of `vec`.
        !>
        !> **`inclusive = .false.` (the default) has an exact specification**: the pixels whose
        !> CENTRES lie within `radius` of `vec`. Reproducible against any correct implementation
        !> and testable by brute force.
        !>
        !> **`inclusive = .true.` returns the pixels OVERLAPPING the disc**, which every
        !> implementation computes as a bounded superset. The contract this one publishes is: every
        !> overlapping pixel is returned, and no pixel whose centre lies farther than
        !> `radius + max_pixrad(nside)` is returned. That bound is what a caller can rely on -- a
        !> returned pixel is not necessarily an overlapping one, and filtering the result is the
        !> caller's business.
        !>
        !> **Output ordering is ascending pixel index for `PF_HP_RING`, and UNSPECIFIED for
        !> `PF_HP_NEST`.** The ring walk emits ascending RING indices naturally, so that half is
        !> free; the RING-to-NEST conversion destroys monotonicity, and sorting afterwards would
        !> cost more than any caller needs. The NEST order is deterministic for a given input, but
        !> it is not promised and may change -- compare NEST results as sets.
        !>
        !> **`listpix` is filled from element 1; the pixel VALUES it holds are 0-based.** Those are
        !> two different bases and are the pair most easily conflated. `nlist` is the count, so the
        !> result is `listpix(1:nlist)`, and a value of 0 in it means pixel zero rather than an
        !> empty slot.
        !>
        !> **A disc smaller than about 1e-08 radians cannot be resolved, and returns too many
        !> pixels rather than too few.** Membership is decided against `cos(radius)`, whose
        !> distance from 1 is about `radius**2/2` -- so the radius is resolved to a fraction
        !> `2.2e-16/radius**2` of itself, which is 2e-10 at a milliradian and 1 at 1.05e-08 rad
        !> (0.0022 arcsec), where `cos(radius)` is exactly 1.0 and the comparison stops
        !> distinguishing anything. This is a property of a double-precision disc query rather than
        !> of this implementation, and it only becomes reachable at extreme resolution: a
        !> pixel-scale disc is resolvable through `nside = 2**28` and degenerates at `2**29`. Every
        !> `nside` a survey actually uses is many orders away from it.
        !>
        !> **No IEEE exception is raised on any input that passes validation.** That is the point of
        !> this module existing: a caller running under `-ffpe-trap=zero,invalid` needs no guard
        !> around these calls.
        !>
        !> Aborts, with a message naming the routine and the offending value, when `nside` is not a
        !> positive power of two or exceeds this kind's ceiling, when `radius` is negative or NaN,
        !> when `vec` holds a NaN or has zero length, when `scheme` is neither selector, or when
        !> `listpix` is too small to hold the result.
        module subroutine hpx_query_disc_i64(nside, vec, radius, listpix, nlist, scheme, inclusive)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0; above pi acts as pi.
            integer(int64), intent(out) :: listpix(:) !! filled from element 1 with 0-based indices.
            integer(int64), intent(out) :: nlist !! how many elements of `listpix` were filled.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_i64

        !> The disc walk itself, over `integer(int64)` and writing into whichever output is present.
        !>
        !> Both output arrays are optional and at most one is passed, which is what lets the two
        !> public kinds share one walk without the int32 form allocating a temporary the size of the
        !> caller's buffer -- the same shape `pf_spatial_index`'s scans use for the same reason.
        !>
        !> **Passing NEITHER is the counting mode**, and it is what `pf_query_disc_count` and the
        !> first pass of `pf_query_disc_alloc` use: every ring bound, every arc trim and every
        !> membership test is the same code, so a count cannot disagree with the list it predicts by
        !> construction rather than by test. In that mode `cap` should be `huge(0_int64)`, which
        !> makes the capacity abort unreachable.
        module subroutine hpx_query_disc_core(nside, vec, radius, scheme, inclusive, nlist, cap, &
                                              what, out32, out64)
            integer(int64), intent(in) :: nside !! resolution parameter, already validated.
            real(real64), intent(in) :: vec(3) !! disc centre, already validated, any length.
            real(real64), intent(in) :: radius !! disc radius, radians, already validated.
            integer, intent(in) :: scheme !! `PF_HP_RING` or `PF_HP_NEST`, already validated.
            logical, intent(in) :: inclusive !! whether to return the overlap superset.
            integer(int64), intent(out) :: nlist !! number of pixels written, or counted.
            integer(int64), intent(in) :: cap !! capacity of the output array, in elements.
            character(len=*), intent(in) :: what !! calling entry point, for a capacity message.
            integer(int32), intent(out), optional :: out32(:) !! int32 output buffer.
            integer(int64), intent(out), optional :: out64(:) !! int64 output buffer.
        end subroutine hpx_query_disc_core

        !> `pf_query_disc_count`, int32 kinds.
        module subroutine hpx_query_disc_count_i32(nside, vec, radius, nlist, scheme, inclusive)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0.
            integer(int32), intent(out) :: nlist !! how many pixels the disc holds.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_count_i32

        !> `pf_query_disc_count`, int64 kinds.
        module subroutine hpx_query_disc_count_i64(nside, vec, radius, nlist, scheme, inclusive)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0; above pi acts as pi.
            integer(int64), intent(out) :: nlist !! how many pixels the disc holds.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_count_i64

        !> `pf_query_disc_alloc`, int32 kinds.
        module subroutine hpx_query_disc_alloc_i32(nside, vec, radius, listpix, nlist, scheme, &
                                                   inclusive)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0.
            integer(int32), allocatable, intent(out) :: listpix(:) !! allocated to exactly `nlist`.
            integer(int32), intent(out) :: nlist !! how many pixels the disc holds.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_alloc_i32

        !> `pf_query_disc_alloc`, int64 kinds.
        module subroutine hpx_query_disc_alloc_i64(nside, vec, radius, listpix, nlist, scheme, &
                                                   inclusive)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0; above pi acts as pi.
            integer(int64), allocatable, intent(out) :: listpix(:) !! allocated to exactly `nlist`.
            integer(int64), intent(out) :: nlist !! how many pixels the disc holds.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_alloc_i64

        !> Validates the arguments shared by all three disc entry points, and aborts on any fault.
        !>
        !> `what` names the calling entry point so that every message identifies the call the
        !> caller actually made -- the same shape `parquet_spatial`'s `sky_chords(deg, what)` uses,
        !> and the reason three entry points can share one validator without any of them reporting
        !> a routine name the caller never wrote.
        module subroutine hpx_check_disc_args(nside, nside_max, vec, radius, scheme, what)
            integer(int64), intent(in) :: nside !! the resolution parameter to check.
            integer(int64), intent(in) :: nside_max !! the ceiling for the caller's integer kind.
            real(real64), intent(in) :: vec(3) !! the disc centre to check.
            real(real64), intent(in) :: radius !! the disc radius to check.
            integer, intent(in) :: scheme !! the resolved scheme selector to check.
            character(len=*), intent(in) :: what !! the calling entry point, for every message.
        end subroutine hpx_check_disc_args
    end interface

    ! ---- Tier B: public generic interfaces, angles and vectors ----

    !> Unit vector of the direction `(theta, phi)`.
    !!
    !! `theta` is colatitude in radians (0 at the north pole), `phi` is longitude in radians and
    !! may lie outside `[0, 2*pi)`. The result is a unit vector to within rounding.
    !!
    !! **Total and `pure`: it validates nothing and never aborts.** A `theta` outside `[0, pi]`
    !! produces the vector of the reflected direction rather than an error. Not `elemental`,
    !! because `vec` is rank 1 -- see `pf_ang2vec_bulk` for the array form.
    interface pf_ang2vec
        module procedure hpx_ang2vec
    end interface pf_ang2vec

    !> Colatitude and longitude of the direction `vec` points in.
    !!
    !! `vec` need not be normalised and its components may span any magnitude: the conversion
    !! divides by the largest component before anything is squared, so `[1e-300, 0, 1e-300]` and
    !! `[1e300, 0, 1e300]` both name the same direction, 45 degrees from the pole, and neither
    !! raises an IEEE exception. `theta` comes back in `[0, pi]` and `phi` in `[0, 2*pi)`.
    !!
    !! **Longitude is undefined at a pole and is reported as 0 there**, which is the conventional
    !! choice; the zero vector reports `theta = 0, phi = 0`. Both are documented answers rather
    !! than accidents -- `atan2(0, 0)` is prohibited by the standard and raises `IEEE_INVALID` on
    !! some compilers, so those two inputs are guarded rather than passed through.
    !!
    !! **Computed as `atan2(transverse, z)`, never as `acos(z/|v|)`**, which loses half its digits
    !! near either pole: for `[1e-8, 0, 1]` the quotient rounds to exactly 1 and an `acos` returns
    !! 0 where the true colatitude is 1e-8.
    interface pf_vec2ang
        module procedure hpx_vec2ang
    end interface pf_vec2ang

    !> Pixel containing the direction `vec` points in, in the RING scheme.
    !!
    !! The vector form is the more primitive one: `pf_ang2pix_ring` begins by taking the cosine of
    !! `theta`, which a caller holding a unit vector already has. `vec` need not be normalised, and
    !! is scaled by its largest component before anything is squared.
    !!
    !! **Total and `pure`: it validates nothing and never aborts**, on the same rule as
    !! `pf_ang2pix_ring`. Not `elemental`, because `vec` is rank 1 -- see `pf_vec2pix_ring_bulk`.
    interface pf_vec2pix_ring
        module procedure hpx_vec2pix_ring_i32
        module procedure hpx_vec2pix_ring_i64
    end interface pf_vec2pix_ring

    !> Pixel containing the direction `vec` points in, in the NEST scheme.
    !!
    !! See `pf_vec2pix_ring`; this is the same conversion into the other numbering scheme.
    interface pf_vec2pix_nest
        module procedure hpx_vec2pix_nest_i32
        module procedure hpx_vec2pix_nest_i64
    end interface pf_vec2pix_nest

    ! ---- Tier B: public generic interfaces, grid arithmetic ----
    !
    ! Every function in this group is `pure elemental` and TOTAL, so none of them can abort -- a
    ! `pure` procedure may not contain an `error stop`, which is an image control statement. Each
    ! reports an argument outside its domain by returning a value the valid range cannot hold:
    ! **-1** for every one of them, except `pf_ring2z`, whose results include -1 and which reports
    ! -2. A caller who ignores that gets a wrong answer rather than an abort, exactly as
    ! `pf_ang2pix_nest(0, ...)` already does.
    !
    ! The int32 and int64 specifics have DIFFERENT domains, and the boundary is each kind's API
    ! ceiling rather than an arithmetic accident: `nside` up to 8192 for int32 (order 13) and up
    ! to 2**29 for int64 (order 29). So `pf_order2nside(20_int32)` reports -1 rather than a
    ! representable 1048576 that no int32 entry point of this module would accept.

    !> Number of pixels at resolution `nside`: `12*nside**2`. -1 if `nside` is out of domain.
    interface pf_nside2npix
        module procedure hpx_nside2npix_i32
        module procedure hpx_nside2npix_i64
    end interface pf_nside2npix

    !> Resolution parameter of a pixel count, or **-1 when `npix` is not a valid one**.
    !!
    !! **This is the validity check on a pixel count read from a file**, and the -1 is what makes
    !! it one: `if (pf_npix2nside(n) < 0)` is the test. A valid `npix` is `12 * 4**order`, so the
    !! whole check is integer arithmetic -- divisibility by 12, then a power of four -- with no
    !! square root and nothing to reason about at the resolutions where a double stops
    !! representing consecutive integers.
    interface pf_npix2nside
        module procedure hpx_npix2nside_i32
        module procedure hpx_npix2nside_i64
    end interface pf_npix2nside

    !> `log2(nside)`, the resolution order. -1 if `nside` is out of domain.
    interface pf_nside2order
        module procedure hpx_nside2order_i32
        module procedure hpx_nside2order_i64
    end interface pf_nside2order

    !> `2**order`, the resolution parameter. -1 if `order` is out of domain.
    !!
    !! The domain is the caller's kind ceiling: `0 .. 13` for int32, `0 .. 29` for int64.
    interface pf_order2nside
        module procedure hpx_order2nside_i32
        module procedure hpx_order2nside_i64
    end interface pf_order2nside

    !> Area of one pixel at `nside`, in steradians: `4*pi/npix`, exactly and for every pixel.
    !!
    !! -1 if `nside` is out of domain. Steradians, not square degrees: this module is radians
    !! throughout, and the conversion is `* (180/pi)**2` at the call site where it is visible.
    interface pf_nside2pixarea
        module procedure hpx_nside2pixarea_i32
        module procedure hpx_nside2pixarea_i64
    end interface pf_nside2pixarea

    !> Pixel resolution at `nside`, in radians -- the side of the equal-area square.
    !!
    !! `sqrt(pf_nside2pixarea(nside))`, which is a definition rather than an approximation: it is
    !! the quantity a caller sizing a grid or a search cell wants. -1 if `nside` is out of domain.
    interface pf_nside2resol
        module procedure hpx_nside2resol_i32
        module procedure hpx_nside2resol_i64
    end interface pf_nside2resol

    !> Ring a RING-scheme pixel lies on, indexed `1 .. 4*nside-1` from the north pole.
    !!
    !! Ring `nside` is the first of the equatorial belt and ring `2*nside` is the equator. -1 if
    !! `nside` is out of domain or `ipix` is outside `0 .. 12*nside**2 - 1`.
    interface pf_pix2ring_ring
        module procedure hpx_pix2ring_ring_i32
        module procedure hpx_pix2ring_ring_i64
    end interface pf_pix2ring_ring

    !> Ring a NEST-scheme pixel lies on, on the same 1-based index as `pf_pix2ring_ring`.
    interface pf_pix2ring_nest
        module procedure hpx_pix2ring_nest_i32
        module procedure hpx_pix2ring_nest_i64
    end interface pf_pix2ring_nest

    !> `z = cos(theta)` of ring `iring`, counted `1 .. 4*nside-1` from the north pole.
    !!
    !! **-2, not -1, when the arguments are out of domain**: a ring's `z` legitimately reaches -1
    !! in the limit, so -1 could not signal anything here.
    interface pf_ring2z
        module procedure hpx_ring2z_i32
        module procedure hpx_ring2z_i64
    end interface pf_ring2z

    !> Nested-scheme resolution change: the parent, or the FIRST of the `4**k` children.
    !!
    !! In NEST the four pixels covering one pixel of the next-coarser grid are consecutive, so a
    !! resolution change is a bit shift and nothing rounds. Coarsening (`order_out < order_in`)
    !! gives the containing pixel; refining gives the **lowest-indexed** of the `4**k` children,
    !! the full set being `ipix_out .. ipix_out + 4**k - 1`. Equal orders are the identity.
    !!
    !! `order_in` and `order_out` take the same integer kind as `ipix`. **Total and `pure
    !! elemental`**: either order outside `0 .. 29`, or a negative `ipix`, yields -1 rather than an
    !! abort or an out-of-range shift. An `ipix` above `12 * 4**order_in - 1` is not checked -- it
    !! costs a multiply on the axis a caller sweeps -- and produces a correspondingly out-of-range
    !! result.
    interface pf_ud_pix_nest
        module procedure hpx_ud_pix_nest_i32
        module procedure hpx_ud_pix_nest_i64
    end interface pf_ud_pix_nest

    !> Squared chord length subtending `angle` radians on the unit sphere: `(2*sin(angle/2))**2`.
    !!
    !! **The cheap substitute for a repeated `pf_angdist`.** Where a caller already holds unit
    !! vectors, `sum((v1-v2)**2) <= pf_chord2_from_angle(r)` is the same test as
    !! `pf_angdist(v1,v2) <= r` with no inverse trigonometry per candidate. The chord is strictly
    !! increasing in the angle over `[0, pi]`, so comparing squared chords orders exactly as
    !! comparing angles does.
    !!
    !! **Radians in, and the SQUARE of the chord out.** `parquet_spatial` carries the same
    !! definition internally in the other units -- degrees in, the chord itself out -- so the two
    !! differ twice over. That tier and this one may not share code (this one reaches nothing but
    !! `parquet_settings_base`), so the agreement is checked by a test that imports both.
    interface pf_chord2_from_angle
        module procedure hpx_chord2_from_angle
    end interface pf_chord2_from_angle

    !> Angle in radians subtended by a squared chord: `2*asin(sqrt(chord2)/2)`.
    !!
    !! The inverse of `pf_chord2_from_angle`, clamped at both ends so that a `chord2` slightly
    !! below 0 or above 4 -- which a caller's own arithmetic can easily produce -- yields 0 or pi
    !! rather than raising `IEEE_INVALID` inside `sqrt` or `asin`.
    interface pf_angle_from_chord2
        module procedure hpx_angle_from_chord2
    end interface pf_angle_from_chord2

    ! ---- Interfaces: Tier B grid arithmetic and vector conversions ----
    !
    ! Implemented in submodule parquet_healpix_grid. Nothing in that file touches a ring walk, a
    ! face or a Morton code: it is closed-form arithmetic on `nside` and on angles, which is why
    ! it is a file of its own rather than more of parquet_healpix_core.

    interface
        !> Unit vector of `(theta, phi)`. See `pf_ang2vec`.
        pure module subroutine hpx_ang2vec(theta, phi, vec)
            real(real64), intent(in) :: theta !! colatitude, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value.
            real(real64), intent(out) :: vec(3) !! the unit vector of that direction.
        end subroutine hpx_ang2vec

        !> Divides `vec` by its largest component and then by its norm, giving a unit vector.
        !>
        !> **The scaling is what makes every vector entry point scale-invariant**, and it is the
        !> rule TA-12 established for `pf_query_disc`: a direction given as `[1e-300, 0, 1e-300]`
        !> is a perfectly good one at 45 degrees from the pole, and squaring its components before
        !> scaling underflows both to zero -- an answer wrong by the whole 45 degrees, not by a
        !> rounding. `[1e300, 0, 1e300]` overflows the other way and raises `IEEE_OVERFLOW` on the
        !> journey. Both were measured against `healpy` 1.20.0, which returns NaN for the first
        !> and `pi/2` for the second.
        !>
        !> A zero vector yields `[0, 0, 0]` rather than a division by zero; every caller treats
        !> that as the documented degenerate direction.
        pure module subroutine hpx_vec_unit(vec, x, y, z)
            real(real64), intent(in) :: vec(3) !! a direction; any length, including zero.
            real(real64), intent(out) :: x !! first component of the unit vector.
            real(real64), intent(out) :: y !! second component.
            real(real64), intent(out) :: z !! third component, clamped into `[-1, 1]`.
        end subroutine hpx_vec_unit

        !> Longitude of a direction whose unit components are `x` and `y`, in `[0, 2*pi)`.
        !>
        !> **`atan2(0, 0)` is prohibited** by F2018 16.9.16, and both arguments vanish at either
        !> POLE -- an entirely ordinary input, not a caller mistake. nagfor returns NaN and raises
        !> `IEEE_INVALID` there, terminating the process under its default `-ieee=stop`, while
        !> gfortran, ifx and flang return 0 silently. Longitude is undefined at a pole, so 0 is as
        !> correct as anything and is the conventional choice.
        pure module function hpx_xy2phi(x, y) result(phi)
            real(real64), intent(in) :: x !! first component.
            real(real64), intent(in) :: y !! second component.
            real(real64) :: phi !! the longitude, radians, in `[0, 2*pi)`; 0 at a pole.
        end function hpx_xy2phi

        !> Colatitude and longitude of `vec`. See `pf_vec2ang`.
        pure module subroutine hpx_vec2ang(vec, theta, phi)
            real(real64), intent(in) :: vec(3) !! a direction; any nonzero length.
            real(real64), intent(out) :: theta !! colatitude, radians, in `[0, pi]`.
            real(real64), intent(out) :: phi !! longitude, radians, in `[0, 2*pi)`.
        end subroutine hpx_vec2ang

    end interface

    ! ---- Interfaces: Tier B direction-to-pixel and resolution change ----
    !
    ! Implemented in parquet_healpix_core, beside the `ang2pix` workers and the NEST codec they
    ! share.

    interface
        !> `pf_vec2pix_ring`, int32 kinds.
        pure module subroutine hpx_vec2pix_ring_i32(nside, vec, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: vec(3) !! a direction; any nonzero length.
            integer(int32), intent(out) :: ipix !! the RING pixel containing it.
        end subroutine hpx_vec2pix_ring_i32

        !> `pf_vec2pix_ring`, int64 kinds.
        pure module subroutine hpx_vec2pix_ring_i64(nside, vec, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: vec(3) !! a direction; any nonzero length.
            integer(int64), intent(out) :: ipix !! the RING pixel containing it.
        end subroutine hpx_vec2pix_ring_i64

        !> `pf_vec2pix_nest`, int32 kinds.
        pure module subroutine hpx_vec2pix_nest_i32(nside, vec, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: vec(3) !! a direction; any nonzero length.
            integer(int32), intent(out) :: ipix !! the NEST pixel containing it.
        end subroutine hpx_vec2pix_nest_i32

        !> `pf_vec2pix_nest`, int64 kinds.
        pure module subroutine hpx_vec2pix_nest_i64(nside, vec, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: vec(3) !! a direction; any nonzero length.
            integer(int64), intent(out) :: ipix !! the NEST pixel containing it.
        end subroutine hpx_vec2pix_nest_i64

        !> `pf_ud_pix_nest`, int32.
        pure elemental module subroutine hpx_ud_pix_nest_i32(ipix, order_in, order_out, ipix_out)
            integer(int32), intent(in) :: ipix !! a NEST pixel index at `order_in`.
            integer(int32), intent(in) :: order_in !! the order it belongs to, `0 .. 29`.
            integer(int32), intent(in) :: order_out !! the order to convert it to, `0 .. 29`.
            integer(int32), intent(out) :: ipix_out !! the result, or -1 out of domain.
        end subroutine hpx_ud_pix_nest_i32

        !> `pf_ud_pix_nest`, int64.
        pure elemental module subroutine hpx_ud_pix_nest_i64(ipix, order_in, order_out, ipix_out)
            integer(int64), intent(in) :: ipix !! a NEST pixel index at `order_in`.
            integer(int64), intent(in) :: order_in !! the order it belongs to, `0 .. 29`.
            integer(int64), intent(in) :: order_out !! the order to convert it to, `0 .. 29`.
            integer(int64), intent(out) :: ipix_out !! the result, or -1 out of domain.
        end subroutine hpx_ud_pix_nest_i64

        !> The shared int64 worker behind `pf_ang2pix_ring` and `pf_vec2pix_ring`.
        pure module function hpx_zphi2pix_ring(nside, z, phi) result(ipix)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: z !! `cos(theta)` of the direction.
            real(real64), intent(in) :: phi !! its longitude, radians; any value.
            integer(int64) :: ipix !! the RING pixel containing it.
        end function hpx_zphi2pix_ring

        !> The shared int64 worker behind `pf_ang2pix_nest` and `pf_vec2pix_nest`.
        pure module function hpx_zphi2pix_nest(nside, z, phi) result(ipix)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: z !! `cos(theta)` of the direction.
            real(real64), intent(in) :: phi !! its longitude, radians; any value.
            integer(int64) :: ipix !! the NEST pixel containing it.
        end function hpx_zphi2pix_nest
    end interface

    interface
        !> `pf_nside2npix`, int32.
        pure elemental module function hpx_nside2npix_i32(nside) result(npix)
            integer(int32), intent(in) :: nside !! resolution parameter, `1 .. 8192`.
            integer(int32) :: npix !! `12*nside**2`, or -1 out of domain.
        end function hpx_nside2npix_i32

        !> `pf_nside2npix`, int64.
        pure elemental module function hpx_nside2npix_i64(nside) result(npix)
            integer(int64), intent(in) :: nside !! resolution parameter, `1 .. 2**29`.
            integer(int64) :: npix !! `12*nside**2`, or -1 out of domain.
        end function hpx_nside2npix_i64

        !> `pf_npix2nside`, int32.
        pure elemental module function hpx_npix2nside_i32(npix) result(nside)
            integer(int32), intent(in) :: npix !! a pixel count to validate and invert.
            integer(int32) :: nside !! the resolution parameter, or -1 if `npix` is not valid.
        end function hpx_npix2nside_i32

        !> `pf_npix2nside`, int64.
        pure elemental module function hpx_npix2nside_i64(npix) result(nside)
            integer(int64), intent(in) :: npix !! a pixel count to validate and invert.
            integer(int64) :: nside !! the resolution parameter, or -1 if `npix` is not valid.
        end function hpx_npix2nside_i64

        !> `pf_nside2order`, int32.
        pure elemental module function hpx_nside2order_i32(nside) result(order)
            integer(int32), intent(in) :: nside !! resolution parameter, `1 .. 8192`.
            integer(int32) :: order !! `log2(nside)`, or -1 out of domain.
        end function hpx_nside2order_i32

        !> `pf_nside2order`, int64.
        pure elemental module function hpx_nside2order_i64(nside) result(order)
            integer(int64), intent(in) :: nside !! resolution parameter, `1 .. 2**29`.
            integer(int64) :: order !! `log2(nside)`, or -1 out of domain.
        end function hpx_nside2order_i64

        !> `pf_order2nside`, int32.
        pure elemental module function hpx_order2nside_i32(order) result(nside)
            integer(int32), intent(in) :: order !! resolution order, `0 .. 13` for this kind.
            integer(int32) :: nside !! `2**order`, or -1 out of domain.
        end function hpx_order2nside_i32

        !> `pf_order2nside`, int64.
        pure elemental module function hpx_order2nside_i64(order) result(nside)
            integer(int64), intent(in) :: order !! resolution order, `0 .. 29` for this kind.
            integer(int64) :: nside !! `2**order`, or -1 out of domain.
        end function hpx_order2nside_i64

        !> `pf_nside2pixarea`, int32.
        pure elemental module function hpx_nside2pixarea_i32(nside) result(area)
            integer(int32), intent(in) :: nside !! resolution parameter, `1 .. 8192`.
            real(real64) :: area !! steradians per pixel, or -1 out of domain.
        end function hpx_nside2pixarea_i32

        !> `pf_nside2pixarea`, int64.
        pure elemental module function hpx_nside2pixarea_i64(nside) result(area)
            integer(int64), intent(in) :: nside !! resolution parameter, `1 .. 2**29`.
            real(real64) :: area !! steradians per pixel, or -1 out of domain.
        end function hpx_nside2pixarea_i64

        !> `pf_nside2resol`, int32.
        pure elemental module function hpx_nside2resol_i32(nside) result(resol)
            integer(int32), intent(in) :: nside !! resolution parameter, `1 .. 8192`.
            real(real64) :: resol !! radians per pixel side, or -1 out of domain.
        end function hpx_nside2resol_i32

        !> `pf_nside2resol`, int64.
        pure elemental module function hpx_nside2resol_i64(nside) result(resol)
            integer(int64), intent(in) :: nside !! resolution parameter, `1 .. 2**29`.
            real(real64) :: resol !! radians per pixel side, or -1 out of domain.
        end function hpx_nside2resol_i64

        !> `pf_pix2ring_ring`, int32.
        pure elemental module function hpx_pix2ring_ring_i32(nside, ipix) result(iring)
            integer(int32), intent(in) :: nside !! resolution parameter.
            integer(int32), intent(in) :: ipix !! a RING pixel index.
            integer(int32) :: iring !! its ring, `1 .. 4*nside-1`, or -1 out of domain.
        end function hpx_pix2ring_ring_i32

        !> `pf_pix2ring_ring`, int64.
        pure elemental module function hpx_pix2ring_ring_i64(nside, ipix) result(iring)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: ipix !! a RING pixel index.
            integer(int64) :: iring !! its ring, `1 .. 4*nside-1`, or -1 out of domain.
        end function hpx_pix2ring_ring_i64

        !> `pf_pix2ring_nest`, int32.
        pure elemental module function hpx_pix2ring_nest_i32(nside, ipix) result(iring)
            integer(int32), intent(in) :: nside !! resolution parameter.
            integer(int32), intent(in) :: ipix !! a NEST pixel index.
            integer(int32) :: iring !! its ring, `1 .. 4*nside-1`, or -1 out of domain.
        end function hpx_pix2ring_nest_i32

        !> `pf_pix2ring_nest`, int64.
        pure elemental module function hpx_pix2ring_nest_i64(nside, ipix) result(iring)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: ipix !! a NEST pixel index.
            integer(int64) :: iring !! its ring, `1 .. 4*nside-1`, or -1 out of domain.
        end function hpx_pix2ring_nest_i64

        !> `pf_ring2z`, int32.
        pure elemental module function hpx_ring2z_i32(nside, iring) result(z)
            integer(int32), intent(in) :: nside !! resolution parameter.
            integer(int32), intent(in) :: iring !! ring index, `1 .. 4*nside-1`.
            real(real64) :: z !! `cos(theta)` of that ring, or -2 out of domain.
        end function hpx_ring2z_i32

        !> `pf_ring2z`, int64.
        pure elemental module function hpx_ring2z_i64(nside, iring) result(z)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: iring !! ring index, `1 .. 4*nside-1`.
            real(real64) :: z !! `cos(theta)` of that ring, or -2 out of domain.
        end function hpx_ring2z_i64

        !> `pf_chord2_from_angle`.
        pure elemental module function hpx_chord2_from_angle(angle) result(chord2)
            real(real64), intent(in) :: angle !! an angle in radians.
            real(real64) :: chord2 !! the square of the chord it subtends on the unit sphere.
        end function hpx_chord2_from_angle

        !> `pf_angle_from_chord2`.
        pure elemental module function hpx_angle_from_chord2(chord2) result(angle)
            real(real64), intent(in) :: chord2 !! a squared chord; clamped into `[0, 4]`.
            real(real64) :: angle !! the angle it subtends, radians, in `[0, pi]`.
        end function hpx_angle_from_chord2
    end interface

    ! ---- Tier B: bulk forms ----
    !
    ! **Every conversion this module offers has a bulk form**, which is a rule rather than a list:
    ! a module where some conversions have one and some do not is a module that gets asked about
    ! the rest. What each one buys differs, and is worth stating plainly rather than implying:
    !
    !   * For the four whose scalar form is `pure elemental` -- `pf_ang2pix_*` and `pf_pix2ang_*`
    !     -- a caller ALREADY has the array form, because an elemental procedure accepts array
    !     actuals, and already has threading by writing `!$omp parallel do` around their own loop.
    !     The bulk form adds the threading DISCIPLINE and nothing else: a thread count resolved
    !     through the same rule every other tier in this library uses, which returns 1 inside
    !     somebody else's parallel region instead of nesting, and which is clamped to the CPU
    !     affinity mask instead of opening 64 threads onto 2 processors.
    !   * For the other six, whose scalar form takes a rank-1 `vec(3)` and so cannot be elemental,
    !     the bulk form supplies an array capability that does not otherwise exist.
    !
    ! **They are separate names rather than specifics of the existing generics, and that is
    ! measured rather than stylistic.** Fortran permits an elemental and a non-elemental specific
    ! in one generic and resolves an array-actual reference to the non-elemental one, so folding
    ! them in is legal and does work -- and it would silently break every array call to those
    ! generics from a `pure` procedure or a `do concurrent`, because the reference would then
    ! resolve to the impure bulk specific and be rejected. `pf_ang2pix_ring` and friends are
    ! published as `pure elemental`; that is a contract, and a name added here must not break it.
    !
    ! All eight below validate: `nside` once, array conformance, and an explicit `threads` of less
    ! than one. That is the opposite of the elemental forms they wrap, which validate nothing -- and
    ! it is right, because the check is once per array rather than once per element, and the
    ! realistic mistake at a bulk call site is a bad `nside` read from a file or three arrays that
    ! do not conform. A zero-sized input is a defined no-op.
    !
    ! Every one is bit-identical at every thread count: each element is a function of its own
    ! inputs alone, there is no reduction anywhere, and the schedule is static.
    !> Bulk `pf_ang2pix_ring`, optionally threaded. See the banner above for what this buys.
    interface pf_ang2pix_ring_bulk
        module procedure hpx_ang2pix_ring_bulk_i32
        module procedure hpx_ang2pix_ring_bulk_i64
    end interface pf_ang2pix_ring_bulk

    !> Bulk `pf_ang2pix_nest`, optionally threaded. See the banner above for what this buys.
    interface pf_ang2pix_nest_bulk
        module procedure hpx_ang2pix_nest_bulk_i32
        module procedure hpx_ang2pix_nest_bulk_i64
    end interface pf_ang2pix_nest_bulk

    !> Bulk `pf_pix2ang_ring`, optionally threaded. See the banner above for what this buys.
    interface pf_pix2ang_ring_bulk
        module procedure hpx_pix2ang_ring_bulk_i32
        module procedure hpx_pix2ang_ring_bulk_i64
    end interface pf_pix2ang_ring_bulk

    !> Bulk `pf_pix2ang_nest`, optionally threaded. See the banner above for what this buys.
    interface pf_pix2ang_nest_bulk
        module procedure hpx_pix2ang_nest_bulk_i32
        module procedure hpx_pix2ang_nest_bulk_i64
    end interface pf_pix2ang_nest_bulk

    !> Bulk `pf_vec2pix_ring`, optionally threaded. See the banner above for what this buys.
    interface pf_vec2pix_ring_bulk
        module procedure hpx_vec2pix_ring_bulk_i32
        module procedure hpx_vec2pix_ring_bulk_i64
    end interface pf_vec2pix_ring_bulk

    !> Bulk `pf_vec2pix_nest`, optionally threaded. See the banner above for what this buys.
    interface pf_vec2pix_nest_bulk
        module procedure hpx_vec2pix_nest_bulk_i32
        module procedure hpx_vec2pix_nest_bulk_i64
    end interface pf_vec2pix_nest_bulk

    !> Bulk `pf_pix2vec_ring`, optionally threaded. See the banner above for what this buys.
    interface pf_pix2vec_ring_bulk
        module procedure hpx_pix2vec_ring_bulk_i32
        module procedure hpx_pix2vec_ring_bulk_i64
    end interface pf_pix2vec_ring_bulk

    !> Bulk `pf_pix2vec_nest`, optionally threaded. See the banner above for what this buys.
    interface pf_pix2vec_nest_bulk
        module procedure hpx_pix2vec_nest_bulk_i32
        module procedure hpx_pix2vec_nest_bulk_i64
    end interface pf_pix2vec_nest_bulk
    !> Bulk `pf_ang2vec`, optionally threaded.
    !!
    !! `theta`, `phi` and `vec(3, n)` must conform. This is the one conversion with a named
    !! downstream caller in the projects this module was written for -- a survey pipeline turning
    !! several million target positions into unit vectors -- and it has no array form at all
    !! without this.
    interface pf_ang2vec_bulk
        module procedure hpx_ang2vec_bulk
    end interface pf_ang2vec_bulk

    !> Bulk `pf_vec2ang`, optionally threaded.
    interface pf_vec2ang_bulk
        module procedure hpx_vec2ang_bulk
    end interface pf_vec2ang_bulk

    ! ---- Interfaces: Tier B bulk forms ----
    !
    ! Implemented in submodule parquet_healpix_bulk, the only file in this tier containing an
    ! OpenMP directive.

    interface
        !> `pf_ang2pix_ring_bulk`, int32 kinds.
        module subroutine hpx_ang2pix_ring_bulk_i32(nside, theta, phi, ipix, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta(:) !! colatitudes, radians.
            real(real64), intent(in) :: phi(:) !! longitudes, radians; any values.
            integer(int32), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_ang2pix_ring_bulk_i32
        !> `pf_ang2pix_ring_bulk`, int64 kinds.
        module subroutine hpx_ang2pix_ring_bulk_i64(nside, theta, phi, ipix, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta(:) !! colatitudes, radians.
            real(real64), intent(in) :: phi(:) !! longitudes, radians; any values.
            integer(int64), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_ang2pix_ring_bulk_i64
        !> `pf_ang2pix_nest_bulk`, int32 kinds.
        module subroutine hpx_ang2pix_nest_bulk_i32(nside, theta, phi, ipix, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta(:) !! colatitudes, radians.
            real(real64), intent(in) :: phi(:) !! longitudes, radians; any values.
            integer(int32), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_ang2pix_nest_bulk_i32
        !> `pf_ang2pix_nest_bulk`, int64 kinds.
        module subroutine hpx_ang2pix_nest_bulk_i64(nside, theta, phi, ipix, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta(:) !! colatitudes, radians.
            real(real64), intent(in) :: phi(:) !! longitudes, radians; any values.
            integer(int64), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_ang2pix_nest_bulk_i64
        !> `pf_pix2ang_ring_bulk`, int32 kinds.
        module subroutine hpx_pix2ang_ring_bulk_i32(nside, ipix, theta, phi, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: theta(:) !! each pixel centre's colatitude, radians.
            real(real64), intent(out) :: phi(:) !! each pixel centre's longitude, radians.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2ang_ring_bulk_i32
        !> `pf_pix2ang_ring_bulk`, int64 kinds.
        module subroutine hpx_pix2ang_ring_bulk_i64(nside, ipix, theta, phi, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: theta(:) !! each pixel centre's colatitude, radians.
            real(real64), intent(out) :: phi(:) !! each pixel centre's longitude, radians.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2ang_ring_bulk_i64
        !> `pf_pix2ang_nest_bulk`, int32 kinds.
        module subroutine hpx_pix2ang_nest_bulk_i32(nside, ipix, theta, phi, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: theta(:) !! each pixel centre's colatitude, radians.
            real(real64), intent(out) :: phi(:) !! each pixel centre's longitude, radians.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2ang_nest_bulk_i32
        !> `pf_pix2ang_nest_bulk`, int64 kinds.
        module subroutine hpx_pix2ang_nest_bulk_i64(nside, ipix, theta, phi, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: theta(:) !! each pixel centre's colatitude, radians.
            real(real64), intent(out) :: phi(:) !! each pixel centre's longitude, radians.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2ang_nest_bulk_i64
        !> `pf_vec2pix_ring_bulk`, int32 kinds.
        module subroutine hpx_vec2pix_ring_bulk_i32(nside, vec, ipix, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(:,:) !! directions, shaped `(3, n)`; any nonzero length.
            integer(int32), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_vec2pix_ring_bulk_i32
        !> `pf_vec2pix_ring_bulk`, int64 kinds.
        module subroutine hpx_vec2pix_ring_bulk_i64(nside, vec, ipix, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(:,:) !! directions, shaped `(3, n)`; any nonzero length.
            integer(int64), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_vec2pix_ring_bulk_i64
        !> `pf_vec2pix_nest_bulk`, int32 kinds.
        module subroutine hpx_vec2pix_nest_bulk_i32(nside, vec, ipix, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(:,:) !! directions, shaped `(3, n)`; any nonzero length.
            integer(int32), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_vec2pix_nest_bulk_i32
        !> `pf_vec2pix_nest_bulk`, int64 kinds.
        module subroutine hpx_vec2pix_nest_bulk_i64(nside, vec, ipix, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(:,:) !! directions, shaped `(3, n)`; any nonzero length.
            integer(int64), intent(out) :: ipix(:) !! the pixel containing each direction.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_vec2pix_nest_bulk_i64
        !> `pf_pix2vec_ring_bulk`, int32 kinds.
        module subroutine hpx_pix2vec_ring_bulk_i32(nside, ipix, vec, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: vec(:,:) !! each pixel centre, shaped `(3, n)`.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2vec_ring_bulk_i32
        !> `pf_pix2vec_ring_bulk`, int64 kinds.
        module subroutine hpx_pix2vec_ring_bulk_i64(nside, ipix, vec, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: vec(:,:) !! each pixel centre, shaped `(3, n)`.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2vec_ring_bulk_i64
        !> `pf_pix2vec_nest_bulk`, int32 kinds.
        module subroutine hpx_pix2vec_nest_bulk_i32(nside, ipix, vec, threads)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: vec(:,:) !! each pixel centre, shaped `(3, n)`.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2vec_nest_bulk_i32
        !> `pf_pix2vec_nest_bulk`, int64 kinds.
        module subroutine hpx_pix2vec_nest_bulk_i64(nside, ipix, vec, threads)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix(:) !! pixel indices.
            real(real64), intent(out) :: vec(:,:) !! each pixel centre, shaped `(3, n)`.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_pix2vec_nest_bulk_i64
        !> `pf_ang2vec_bulk`. Not generic: no integer argument to be generic over.
        module subroutine hpx_ang2vec_bulk(theta, phi, vec, threads)
            real(real64), intent(in) :: theta(:) !! colatitudes, radians.
            real(real64), intent(in) :: phi(:) !! longitudes, radians; any values.
            real(real64), intent(out) :: vec(:,:) !! the unit vectors, shaped `(3, n)`.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_ang2vec_bulk

        !> `pf_vec2ang_bulk`. Not generic: no integer argument to be generic over.
        module subroutine hpx_vec2ang_bulk(vec, theta, phi, threads)
            real(real64), intent(in) :: vec(:,:) !! directions, shaped `(3, n)`; any nonzero length.
            real(real64), intent(out) :: theta(:) !! each direction's colatitude, radians.
            real(real64), intent(out) :: phi(:) !! each direction's longitude, radians.
            integer, intent(in), optional :: threads !! threads to open; absent resolves automatically.
        end subroutine hpx_vec2ang_bulk

        !> Threads to open for a bulk call of `n` elements, after every rule and the affinity clamp.
        module function hpx_threads(threads, n, what) result(nt)
            integer, intent(in), optional :: threads !! an explicit request; absent resolves automatically.
            integer(int64), intent(in) :: n !! elements the call will process.
            character(len=*), intent(in) :: what !! the calling entry point, for the message.
            integer :: nt !! threads to open; 1 means run serially.
        end function hpx_threads

        !> Aborts unless every extent matches `n`, naming the caller and the offending sizes.
        module subroutine hpx_check_bulk_sizes(n, sizes, what)
            integer(int64), intent(in) :: n !! the expected extent.
            integer(int64), intent(in) :: sizes(:) !! the extents to compare against it.
            character(len=*), intent(in) :: what !! the calling entry point, for the message.
        end subroutine hpx_check_bulk_sizes
    end interface

    ! ---- Interfaces: small shared helpers ----
    !
    ! Implemented in parquet_healpix_core. These are declared rather than contained for the same
    ! linkage reason as the geometry helpers above: a private module-contained procedure has
    ! internal linkage under gfortran, so a submodule calling one compiles and then fails to link.

    interface
        !> Spreads the low 32 bits of `v` into the even bit positions of a 64-bit result.
        !>
        !> The standard five-step Morton spread, and half of the NEST index's construction. Done
        !> with masks rather than a lookup table so that the module carries no data at all -- there
        !> is then nothing for a parallel region to share, and nothing to initialise lazily.
        pure module function hpx_spread_bits(v) result(s)
            integer(int64), intent(in) :: v !! the value whose low 32 bits are spread.
            integer(int64) :: s !! the spread result, occupying the even bits of 64.
        end function hpx_spread_bits

        !> Gathers the even bit positions of `v` back into a contiguous low field.
        !>
        !> The exact inverse of `hpx_spread_bits`.
        pure module function hpx_compact_bits(v) result(c)
            integer(int64), intent(in) :: v !! the interleaved value to compact.
            integer(int64) :: c !! the even bits of `v`, packed into the low half.
        end function hpx_compact_bits

        !> Whether `nside` is a positive power of two at or below `limit`.
        pure module function hpx_nside_ok(nside, limit) result(ok)
            integer(int64), intent(in) :: nside !! the value to test.
            integer(int64), intent(in) :: limit !! the largest acceptable value.
            logical :: ok !! `.true.` when `nside` is usable.
        end function hpx_nside_ok

        !> Renders an integer as its shortest decimal text, for an `error stop` message.
        !>
        !> A subroutine with an allocatable `intent(out)` argument rather than a function returning
        !> `character(len=:), allocatable`, per the project-wide rule: gfortran's codegen for
        !> receiving such a result races on a hidden length temporary when called concurrently.
        module subroutine hpx_itoa(value, text)
            integer(int64), intent(in) :: value !! the number to render.
            character(len=:), allocatable, intent(out) :: text !! its decimal text, unpadded.
        end subroutine hpx_itoa

        !> Renders a real as a short decimal text, for an `error stop` message.
        module subroutine hpx_rtoa(value, text)
            real(real64), intent(in) :: value !! the number to render.
            character(len=:), allocatable, intent(out) :: text !! its text, unpadded.
        end subroutine hpx_rtoa
    end interface

end module parquet_healpix
