!===========================================
! This file is automatically generated! Do not edit it directly!
! Instead, edit the MAML files under docs/ and run generate_parquet_maml.sh to regenerate this file.
! Generator script: parquet-fortran/tools/generate_parquet_maml.sh
!===========================================
!
module parquet_maml_base
    implicit none
    private

    type, public :: parquet_maml_file
        character(len=:), allocatable :: name
        character(len=:), allocatable :: lines(:)
    end type parquet_maml_file

    public :: get_parquet_maml
    public :: parquet_maml_maml_example
    public :: parquet_maml_maml_example2

contains

    function get_parquet_maml(name) result(maml)
        character(len=*), intent(in) :: name
        type(parquet_maml_file) :: maml

        select case (trim(name))
        case ("maml_example.maml")
            maml = parquet_maml_maml_example()
        case ("maml_example")
            maml = parquet_maml_maml_example()
        case ("maml_example2.maml")
            maml = parquet_maml_maml_example2()
        case ("maml_example2")
            maml = parquet_maml_maml_example2()
        case default
            error stop "get_parquet_maml: unknown internal MAML file: " // trim(name)
        end select
    end function get_parquet_maml

    function parquet_maml_maml_example() result(maml)
        type(parquet_maml_file) :: maml

        maml%name = "maml_example.maml"
        allocate(character(len=104) :: maml%lines(91))
        maml%lines(1) = "dataset: input_data"
        maml%lines(2) = "table: input_table"
        maml%lines(3) = "author: Dave Smith <dave_smith_is_not_here@gmail.com>"
        maml%lines(4) = "coauthors:"
        maml%lines(5) = "- Joe Bloggs <joe_bloggs_is_not_here@gmail.com>"
        maml%lines(6) = "- Jane Doe <jane_doe_is_not_here@gmail.com>"
        maml%lines(7) = "DOIs:"
        maml%lines(8) = "- DOI: 10.1093/mnras/sty440"
        maml%lines(9) = "  type: paper"
        maml%lines(10) = "- DOI: 10.5281/zenodo.10059903"
        maml%lines(11) = "  type: software"
        maml%lines(12) = &
            "description: Just an example. Probably do not write tonnes here. A few sentences is usually about ri" // &
            "ght."
        maml%lines(13) = "comments:"
        maml%lines(14) = "- This is an example. Remember comments are lists."
        maml%lines(15) = "- Another comment."
        maml%lines(16) = "- zeropoint: 1.00"
        maml%lines(17) = "license: Copyright [Private]"
        maml%lines(18) = "keyarray:"
        maml%lines(19) = "- key: test_scalar"
        maml%lines(20) = "  value: 8.1"
        maml%lines(21) = "  comment: something"
        maml%lines(22) = "- key: test_string"
        maml%lines(23) = "  value: Fun times"
        maml%lines(24) = "  comment: something else"
        maml%lines(25) = "- key: test_vector"
        maml%lines(26) = "  value: [1.8, 2, 5]"
        maml%lines(27) = "  comment: something extra"
        maml%lines(28) = "fields:"
        maml%lines(29) = "- name: id0"
        maml%lines(30) = "  unit: unitless"
        maml%lines(31) = "  info: ID field."
        maml%lines(32) = "  ucd: meta.id;meta.main"
        maml%lines(33) = "  data_type: int32"
        maml%lines(34) = "- name: idarr"
        maml%lines(35) = "  unit: unitless"
        maml%lines(36) = "  info: ID field."
        maml%lines(37) = "  ucd: meta.id;meta.main"
        maml%lines(38) = "  data_type: int64"
        maml%lines(39) = "  col_size: 2"
        maml%lines(40) = "- name: name"
        maml%lines(41) = "  unit: unitless"
        maml%lines(42) = "  info: Name of the object."
        maml%lines(43) = "  ucd:"
        maml%lines(44) = "  - meta.id"
        maml%lines(45) = "  - meta.main"
        maml%lines(46) = "  data_type: string"
        maml%lines(47) = "  array_size: 18"
        maml%lines(48) = "- name: name_arr"
        maml%lines(49) = "  info: Name of the object."
        maml%lines(50) = "  data_type: string"
        maml%lines(51) = "  array_size: 8"
        maml%lines(52) = "  col_size: 3"
        maml%lines(53) = "- name: idlong"
        maml%lines(54) = "  unit: count"
        maml%lines(55) = "  info: Long ID field."
        maml%lines(56) = "  ucd: meta.id"
        maml%lines(57) = "  data_type: int64"
        maml%lines(58) = "- name: value"
        maml%lines(59) = "  unit: m/s"
        maml%lines(60) = "  info: Value of the object."
        maml%lines(61) = "  ucd: phys.veloc;phys.speed"
        maml%lines(62) = "  data_type: float32"
        maml%lines(63) = "- name: value_64"
        maml%lines(64) = "  unit: m/s"
        maml%lines(65) = "  info: Second value of the object."
        maml%lines(66) = "  ucd: phys.veloc;phys.speed"
        maml%lines(67) = "  data_type: float64"
        maml%lines(68) = "- name: arr"
        maml%lines(69) = "  unit: unitless"
        maml%lines(70) = "  info: Array of values."
        maml%lines(71) = "  ucd: "
        maml%lines(72) = "  data_type: float32"
        maml%lines(73) = "  col_size: 5"
        maml%lines(74) = "- name: arrlong"
        maml%lines(75) = "  unit: unitless"
        maml%lines(76) = "  info: Array of values."
        maml%lines(77) = "  data_type: float64"
        maml%lines(78) = "  col_size: 5"
        maml%lines(79) = "- name: val"
        maml%lines(80) = "  info: Value of the object."
        maml%lines(81) = "  data_type: float32"
        maml%lines(82) = "- name: iarr"
        maml%lines(83) = "  info: Array of values."
        maml%lines(84) = "  data_type: int32"
        maml%lines(85) = "  col_size: 3"
        maml%lines(86) = "- name: myflag"
        maml%lines(87) = "  data_type: boolean"
        maml%lines(88) = "- name: flag_array"
        maml%lines(89) = "  info: Flag for the object."
        maml%lines(90) = "  data_type: boolean"
        maml%lines(91) = "  col_size: 6"
    end function parquet_maml_maml_example
    function parquet_maml_maml_example2() result(maml)
        type(parquet_maml_file) :: maml

        maml%name = "maml_example2.maml"
        allocate(character(len=104) :: maml%lines(13))
        maml%lines(1) = "dataset: input_data"
        maml%lines(2) = "table: input_table"
        maml%lines(3) = "author: Dave Smith <dave_smith_is_not_here@gmail.com>"
        maml%lines(4) = &
            "description: Just an example. Probably do not write tonnes here. A few sentences is usually about ri" // &
            "ght."
        maml%lines(5) = "license: Copyright [Private]"
        maml%lines(6) = "fields:"
        maml%lines(7) = "- name: id"
        maml%lines(8) = "  info: ID field."
        maml%lines(9) = "  data_type: int32"
        maml%lines(10) = "- name: name"
        maml%lines(11) = "  info: Name of the object."
        maml%lines(12) = "  data_type: string"
        maml%lines(13) = "  array_size: 24"
    end function parquet_maml_maml_example2

end module parquet_maml_base
