!> The HEALPix sphere pixelisation: position <-> pixel, scheme conversion, and disc queries.
!!
!! HEALPix divides the sphere into `12*nside**2` pixels of exactly equal area, arranged on rings of
!! constant latitude. `parquet_healpix` implements the part of it a program actually needs to hold
!! sky data on a grid: converting a direction to the pixel containing it and back, converting
!! between the two pixel-numbering schemes, and enumerating the pixels of a disc.
!!
!! **Written from the published algorithm, not translated from any implementation.** The
!! pixelisation is described completely in Gorski et al. 2005, ApJ 622, 759, and the geometry is
!! elementary; every formula here was derived from that paper and then checked against reference
!! vectors (`test/test_healpix_vectors.f90`, generated by `tools/generate_healpix_reference.py`).
!! No HEALPix source was consulted while writing this module, and none should be if it is ever
!! re-derived -- the paper plus the vectors are sufficient, and they are what keeps this library
!! BSD-3-Clause while `libhealpix` is GPL-2.0.
!!
!! **This module is Arrow-free by construction and that is the point of its tier.** It reaches
!! `iso_fortran_env`, `ieee_arithmetic` and `parquet_settings_base`, and nothing else, so
!! `use parquet_healpix` in a downstream project compiles four Fortran files rather than the
!! sixty-odd the reader/writer stack costs. `check_parquet_healpix_stays_arrow_free`
!! (tools/check_source_conventions.py) and `tools/module_footprints.txt` are what keep that true --
!! a `use` line added here can silently multiply what every consumer compiles, and no test can see
!! it happen.
!!
!! **No module state, no saved variables, no lazy initialisation.** Every procedure here is a
!! function of its arguments alone, so the whole module is thread-safe with nothing to arrange and
!! the scalar conversions are `pure elemental`. Do not add a cache: a `logical, save :: ready`
!! reached from inside a parallel region is a check-then-act on shared state.
!!
!! **Two conventions a caller must get right, and neither has a default this module can pick:**
!!
!! * `theta` is COLATITUDE from the north pole in radians, so `theta = pi/2 - dec`. A mirrored
!!   frame (`theta = pi/2 + dec`) is in live use in several projects that feed this module, and is
!!   self-consistent -- a reflection preserves angular distance -- but mixing the two searches the
!!   wrong hemisphere silently. This module takes HEALPix-native `theta`/`phi` and unit vectors
!!   only, and offers no RA/Dec layer, precisely so that the choice stays visible at each call.
!! * A pixel INDEX runs `0 .. 12*nside**2 - 1`, as the pixelisation itself defines it. The
!!   `listpix` array `pf_query_disc` fills is 1-based, like every other user-facing array in this
!!   library. The array base and the pixel base are different things and are the pair most easily
!!   conflated: `listpix(1)` holds the first pixel found, and its VALUE may well be 0.
module parquet_healpix
    use, intrinsic :: iso_fortran_env, only: int32, int64, real64
    use, intrinsic :: ieee_arithmetic, only: ieee_is_nan, ieee_is_finite
    use parquet_settings_base, only: parquet_set_verbosity, parquet_get_verbosity, &
        parquet_set_message_stream, parquet_get_message_stream
    implicit none
    private

    public :: PF_HP_RING, PF_HP_NEST
    public :: pf_ang2pix_ring, pf_ang2pix_nest
    public :: pf_pix2ang_ring, pf_pix2ang_nest
    public :: pf_pix2vec_ring, pf_pix2vec_nest
    public :: pf_ring2nest, pf_nest2ring
    public :: pf_query_disc
    public :: pf_angdist
    public :: pf_max_pixrad
    !
    ! ---- Settings this module's own code reads, re-exported so a narrow import can configure it ----
    !
    !> The output pair, because `pf_query_disc`'s bulk siblings emit a thread-clamp warning through
    !! the same channel every other tier does. Re-exported here so a program whose only import is
    !! `use parquet_healpix` can silence it without naming `parquet_settings` -- which would put the
    !! C++ boundary, and with it Arrow, back into an otherwise Arrow-free build.
    public :: parquet_set_verbosity, parquet_get_verbosity
    public :: parquet_set_message_stream, parquet_get_message_stream

    ! ---- Scheme selectors ----

    !> RING scheme: pixels numbered along rings of constant latitude, north to south.
    !!
    !! Index order follows latitude, which is what makes a declination band one contiguous range of
    !! indices. `pf_query_disc` returns RING results in ascending index order.
    integer, parameter :: PF_HP_RING = 0
    !> NEST scheme: pixels numbered so that the four children of a pixel at the next resolution are
    !! consecutive.
    !!
    !! A resolution change is a bit shift in this scheme, which is what makes it the right choice
    !! for hierarchical work. `pf_query_disc` does not promise any particular order for NEST output.
    integer, parameter :: PF_HP_NEST = 1

    ! ---- Kind and range limits ----

    !> Largest `nside` whose pixel indices still fit `integer(int32)`.
    !!
    !! `12*8192**2` is 805306368; the next power of two overflows a signed 32-bit index, so the
    !! int32 specifics refuse it rather than wrapping.
    integer(int64), parameter :: hpx_nside_max_i32 = 8192_int64
    !> Largest `nside` this module accepts at all, in either kind.
    !!
    !! `2**29` matches the ceiling the HEALPix ecosystem itself uses and keeps every intermediate
    !! inside `integer(int64)`: `npix` is `3*2**60`, the Morton interleave of two 29-bit
    !! coordinates occupies 58 bits, the face offset reaches `11*4**29 < 2**62`, and the cap-ring
    !! inversion's square-root argument stays below 7e18, where a double still resolves it to
    !! better than one part in a ring.
    integer(int64), parameter :: hpx_nside_max = 536870912_int64

    ! ---- Mathematical constants ----

    !> pi.
    real(real64), parameter :: hpx_pi = 3.141592653589793238462643_real64
    !> pi/2.
    real(real64), parameter :: hpx_halfpi = 0.5_real64 * hpx_pi
    !> 2*pi.
    real(real64), parameter :: hpx_twopi = 2.0_real64 * hpx_pi
    !> The |z| at which the polar caps meet the equatorial belt.
    real(real64), parameter :: hpx_twothird = 2.0_real64 / 3.0_real64

    ! ---- Morton-order bit masks ----
    !
    ! The NEST index interleaves the bits of a pixel's two within-face coordinates. Spreading and
    ! compacting them is done with the standard five-step mask sequence rather than a lookup table,
    ! which keeps the codec branch-free and -- more to the point here -- keeps the module free of
    ! any data at all, so there is nothing for a parallel region to share.

    !> Bit mask 0x00000000FFFFFFFF.
    integer(int64), parameter :: hpx_m32 = int(z'00000000FFFFFFFF', int64)
    !> Bit mask 0x0000FFFF0000FFFF.
    integer(int64), parameter :: hpx_m16 = int(z'0000FFFF0000FFFF', int64)
    !> Bit mask 0x00FF00FF00FF00FF.
    integer(int64), parameter :: hpx_m8 = int(z'00FF00FF00FF00FF', int64)
    !> Bit mask 0x0F0F0F0F0F0F0F0F.
    integer(int64), parameter :: hpx_m4 = int(z'0F0F0F0F0F0F0F0F', int64)
    !> Bit mask 0x3333333333333333.
    integer(int64), parameter :: hpx_m2 = int(z'3333333333333333', int64)
    !> Bit mask 0x5555555555555555 -- the even bit positions.
    integer(int64), parameter :: hpx_m1 = int(z'5555555555555555', int64)

    ! ---- Per-face ring and phi offsets ----
    !
    ! Faces 0-3 are the north cap, 4-7 the equatorial belt, 8-11 the south cap. These two tables
    ! place each face's centre on the (ring, index-in-ring) grid, and are what the NEST <-> RING
    ! conversions are built from.

    !> Ring offset of each face centre, in units of `nside`.
    integer(int64), parameter :: hpx_jrll(0:11) = [2_int64, 2_int64, 2_int64, 2_int64, &
        3_int64, 3_int64, 3_int64, 3_int64, 4_int64, 4_int64, 4_int64, 4_int64]
    !> Longitude offset of each face centre, in units of a ring's quarter width.
    integer(int64), parameter :: hpx_jpll(0:11) = [1_int64, 3_int64, 5_int64, 7_int64, &
        0_int64, 2_int64, 4_int64, 6_int64, 1_int64, 3_int64, 5_int64, 7_int64]

    ! ---- Public generic interfaces ----

    !> Pixel containing the direction `(theta, phi)`, in the RING scheme.
    !!
    !! `nside` is a positive power of two, `theta` is colatitude in radians (0 at the north pole,
    !! pi at the south), `phi` is longitude in radians and may lie outside `[0, 2*pi)`. `ipix`
    !! comes back in the same integer kind as `nside`, in `0 .. 12*nside**2 - 1`.
    !!
    !! **Total and `pure elemental`: it validates nothing and never aborts.** An `nside` that is
    !! not a positive power of two, or a `theta` outside `[0, pi]`, produces a meaningless result
    !! rather than an error -- `pf_ang2pix_ring(0, ...)` returns nonsense. That is deliberate: this
    !! is the per-element hot path, and validation belongs in the once-per-query entry points
    !! (`pf_query_disc`), which check `nside` once before their walk. A NaN angle propagates into
    !! the integer conversion, which may raise `IEEE_INVALID`; every OTHER path in this module is
    !! free of IEEE exceptions on validated input.
    interface pf_ang2pix_ring
        module procedure hpx_ang2pix_ring_i32
        module procedure hpx_ang2pix_ring_i64
    end interface pf_ang2pix_ring

    !> Pixel containing the direction `(theta, phi)`, in the NEST scheme.
    !!
    !! Arguments and kinds are `pf_ang2pix_ring`'s, and so is the total, non-validating contract:
    !! see that procedure for the full statement of both.
    interface pf_ang2pix_nest
        module procedure hpx_ang2pix_nest_i32
        module procedure hpx_ang2pix_nest_i64
    end interface pf_ang2pix_nest

    !> Direction of a RING pixel's centre, as `(theta, phi)` in radians.
    !!
    !! `ipix` is a RING index in `0 .. 12*nside**2 - 1`, in the same kind as `nside`. `theta` comes
    !! back in `[0, pi]` and `phi` in `[0, 2*pi)`.
    !!
    !! **Total and `pure elemental`, exactly as `pf_ang2pix_ring` is** -- an out-of-range `ipix`
    !! gives a meaningless answer rather than an abort.
    !!
    !! **Near the poles at very high resolution, `theta` carries fewer digits than `phi` does**, and
    !! that is inherent rather than a defect here: a ring's centre is defined by its `z`, and
    !! `theta = acos(z)` loses about half the significant digits when `z` is within an ulp or two of
    !! +-1. At `nside = 2**20` the first ring's `z` is `1 - 3e-13`, so `theta` is good to about
    !! 4e-10 rather than to an ulp. Work in `z`, or in unit vectors through `pf_pix2vec_ring`, when
    !! that matters.
    interface pf_pix2ang_ring
        module procedure hpx_pix2ang_ring_i32
        module procedure hpx_pix2ang_ring_i64
    end interface pf_pix2ang_ring

    !> Direction of a NEST pixel's centre, as `(theta, phi)` in radians.
    !!
    !! Arguments, kinds, contract and polar-precision caveat are `pf_pix2ang_ring`'s.
    interface pf_pix2ang_nest
        module procedure hpx_pix2ang_nest_i32
        module procedure hpx_pix2ang_nest_i64
    end interface pf_pix2ang_nest

    !> Unit vector of a RING pixel's centre.
    !!
    !! `vec` is the Cartesian direction `(x, y, z)` of the pixel centre. **This is the primitive
    !! form and `pf_pix2ang_ring` is derived from it**, not the other way round: the centre is
    !! built from the ring's `z` directly, with no `acos`/`cos` round trip. That is load-bearing
    !! rather than an optimisation -- a round trip moves a centre lying exactly on a disc's rim to
    !! the wrong side of it, which flips a whole equatorial ring in or out of a pole-centred
    !! hemisphere.
    !!
    !! Total and `pure`; not `elemental`, because the result is an array.
    interface pf_pix2vec_ring
        module procedure hpx_pix2vec_ring_i32
        module procedure hpx_pix2vec_ring_i64
    end interface pf_pix2vec_ring

    !> Unit vector of a NEST pixel's centre.
    !!
    !! Arguments, kinds and contract are `pf_pix2vec_ring`'s.
    interface pf_pix2vec_nest
        module procedure hpx_pix2vec_nest_i32
        module procedure hpx_pix2vec_nest_i64
    end interface pf_pix2vec_nest

    !> RING pixel index -> NEST pixel index, at the same `nside`.
    !!
    !! `ipring` and `ipnest` are both in `0 .. 12*nside**2 - 1` and in the same kind as `nside`.
    !! Exact integer arithmetic throughout -- no direction is computed and nothing rounds. Total
    !! and `pure elemental`, so an out-of-range input gives a meaningless answer rather than an
    !! abort.
    interface pf_ring2nest
        module procedure hpx_ring2nest_i32
        module procedure hpx_ring2nest_i64
    end interface pf_ring2nest

    !> NEST pixel index -> RING pixel index, at the same `nside`.
    !!
    !! The exact inverse of `pf_ring2nest`; same kinds, same total contract.
    interface pf_nest2ring
        module procedure hpx_nest2ring_i32
        module procedure hpx_nest2ring_i64
    end interface pf_nest2ring

    !> Largest angular distance from a pixel centre to one of its own corners, in radians.
    !!
    !! **The margin `pf_query_disc`'s `inclusive = .true.` mode enlarges its radius by, and the
    !! bound that mode publishes** -- so it is also the honest way to size a search margin around a
    !! position, where code of this kind often carries a rule-of-thumb factor instead.
    !!
    !! Attained on the first equatorial ring, whose pixels are the most elongated, at the corner
    !! lying on the quadrant meridian. `nside` takes either integer kind; the result is `real64`.
    !!
    !! `pure elemental` and total: it validates nothing, so an `nside` that is not a positive power
    !! of two gives a meaningless answer rather than an error, exactly as the conversions do.
    interface pf_max_pixrad
        module procedure hpx_max_pixrad_i32
        module procedure hpx_max_pixrad_i64
    end interface pf_max_pixrad

    !> Pixels of a disc: every pixel within `radius` of the direction `vec`.
    !!
    !! **The one entry point here that validates its arguments**, and the one that aborts. See
    !! `hpx_query_disc_i64` for the full contract: the two `inclusive` modes, the ordering promise
    !! (ascending for `PF_HP_RING`, unspecified for `PF_HP_NEST`), the 1-based `listpix` against
    !! 0-based pixel values, and every condition that stops the run.
    interface pf_query_disc
        module procedure hpx_query_disc_i32
        module procedure hpx_query_disc_i64
    end interface pf_query_disc

    ! ---- Interfaces: position <-> pixel ----
    !
    ! Implemented in submodule parquet_healpix_core.

    interface
        !> RING pixel for a direction, int32 kinds. See the `pf_ang2pix_ring` generic.
        pure elemental module subroutine hpx_ang2pix_ring_i32(nside, theta, phi, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int32), intent(out) :: ipix !! RING pixel index, 0-based.
        end subroutine hpx_ang2pix_ring_i32

        !> RING pixel for a direction, int64 kinds. See the `pf_ang2pix_ring` generic.
        pure elemental module subroutine hpx_ang2pix_ring_i64(nside, theta, phi, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int64), intent(out) :: ipix !! RING pixel index, 0-based.
        end subroutine hpx_ang2pix_ring_i64

        !> NEST pixel for a direction, int32 kinds. See the `pf_ang2pix_nest` generic.
        pure elemental module subroutine hpx_ang2pix_nest_i32(nside, theta, phi, ipix)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int32), intent(out) :: ipix !! NEST pixel index, 0-based.
        end subroutine hpx_ang2pix_nest_i32

        !> NEST pixel for a direction, int64 kinds. See the `pf_ang2pix_nest` generic.
        pure elemental module subroutine hpx_ang2pix_nest_i64(nside, theta, phi, ipix)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: theta !! colatitude from the north pole, radians.
            real(real64), intent(in) :: phi !! longitude, radians; any value is accepted.
            integer(int64), intent(out) :: ipix !! NEST pixel index, 0-based.
        end subroutine hpx_ang2pix_nest_i64

        !> Centre direction of a RING pixel, int32 kinds. See the `pf_pix2ang_ring` generic.
        pure elemental module subroutine hpx_pix2ang_ring_i32(nside, ipix, theta, phi)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_ring_i32

        !> Centre direction of a RING pixel, int64 kinds. See the `pf_pix2ang_ring` generic.
        pure elemental module subroutine hpx_pix2ang_ring_i64(nside, ipix, theta, phi)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_ring_i64

        !> Centre direction of a NEST pixel, int32 kinds. See the `pf_pix2ang_nest` generic.
        pure elemental module subroutine hpx_pix2ang_nest_i32(nside, ipix, theta, phi)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_nest_i32

        !> Centre direction of a NEST pixel, int64 kinds. See the `pf_pix2ang_nest` generic.
        pure elemental module subroutine hpx_pix2ang_nest_i64(nside, ipix, theta, phi)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: theta !! colatitude of the centre, radians, in [0, pi].
            real(real64), intent(out) :: phi !! longitude of the centre, radians, in [0, 2*pi).
        end subroutine hpx_pix2ang_nest_i64

        !> Centre unit vector of a RING pixel, int32 kinds. See the `pf_pix2vec_ring` generic.
        pure module subroutine hpx_pix2vec_ring_i32(nside, ipix, vec)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_ring_i32

        !> Centre unit vector of a RING pixel, int64 kinds. See the `pf_pix2vec_ring` generic.
        pure module subroutine hpx_pix2vec_ring_i64(nside, ipix, vec)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! RING pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_ring_i64

        !> Centre unit vector of a NEST pixel, int32 kinds. See the `pf_pix2vec_nest` generic.
        pure module subroutine hpx_pix2vec_nest_i32(nside, ipix, vec)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_nest_i32

        !> Centre unit vector of a NEST pixel, int64 kinds. See the `pf_pix2vec_nest` generic.
        pure module subroutine hpx_pix2vec_nest_i64(nside, ipix, vec)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipix !! NEST pixel index, 0-based.
            real(real64), intent(out) :: vec(3) !! unit vector of the pixel centre.
        end subroutine hpx_pix2vec_nest_i64
    end interface

    ! ---- Interfaces: scheme conversion ----
    !
    ! Implemented in submodule parquet_healpix_core.

    interface
        !> RING -> NEST, int32 kinds. See the `pf_ring2nest` generic.
        pure elemental module subroutine hpx_ring2nest_i32(nside, ipring, ipnest)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipring !! RING pixel index, 0-based.
            integer(int32), intent(out) :: ipnest !! the same pixel's NEST index.
        end subroutine hpx_ring2nest_i32

        !> RING -> NEST, int64 kinds. See the `pf_ring2nest` generic.
        pure elemental module subroutine hpx_ring2nest_i64(nside, ipring, ipnest)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipring !! RING pixel index, 0-based.
            integer(int64), intent(out) :: ipnest !! the same pixel's NEST index.
        end subroutine hpx_ring2nest_i64

        !> NEST -> RING, int32 kinds. See the `pf_nest2ring` generic.
        pure elemental module subroutine hpx_nest2ring_i32(nside, ipnest, ipring)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int32), intent(in) :: ipnest !! NEST pixel index, 0-based.
            integer(int32), intent(out) :: ipring !! the same pixel's RING index.
        end subroutine hpx_nest2ring_i32

        !> NEST -> RING, int64 kinds. See the `pf_nest2ring` generic.
        pure elemental module subroutine hpx_nest2ring_i64(nside, ipnest, ipring)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            integer(int64), intent(in) :: ipnest !! NEST pixel index, 0-based.
            integer(int64), intent(out) :: ipring !! the same pixel's RING index.
        end subroutine hpx_nest2ring_i64
    end interface

    ! ---- Interfaces: ring geometry and the Morton codec ----
    !
    ! Private to the module and its submodules. Implemented in parquet_healpix_core; declared here
    ! rather than contained in the module because gfortran gives a private module-contained
    ! procedure internal linkage, so a submodule calling one fails to LINK while compiling cleanly.

    interface
        !> Centre `z` of ring `i`, counted from the north pole.
        !>
        !> The single place the three regions' `z` formulas live. Every consumer of a ring's
        !> latitude -- the pixel centre, the disc walk's band test, the per-ring threshold -- goes
        !> through this one function, so the module cannot disagree with itself about where a ring
        !> is.
        pure module function hpx_ring_z(nside, i) result(z)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            real(real64) :: z !! cosine of the ring's colatitude.
        end function hpx_ring_z

        !> Where ring `i` starts, how many pixels it holds, and whether it is offset in longitude.
        pure module subroutine hpx_ring_first(nside, i, first, nr, shifted)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(out) :: first !! RING index of the ring's first pixel.
            integer(int64), intent(out) :: nr !! number of pixels on the ring.
            integer(int64), intent(out) :: shifted !! 1 when centres are offset by half a pixel.
        end subroutine hpx_ring_first

        !> Largest ring index whose centre `z` is at or above `z`; 0 when none is.
        !>
        !> Used only to bracket the disc walk's band of rings, which is then widened by one ring on
        !> each side, so an answer off by one costs three membership tests and never a wrong result.
        pure module function hpx_ring_above(nside, z) result(i)
            integer(int64), intent(in) :: nside !! resolution parameter.
            real(real64), intent(in) :: z !! cosine of a colatitude, in [-1, 1].
            integer(int64) :: i !! the ring index, 0 when the whole sphere lies below `z`.
        end function hpx_ring_above

        !> Ring index of a north-cap RING pixel.
        !>
        !> Inverts `p = 2*i*(i-1) + j` for `i`. The square root seeds the answer and the two
        !> single-step corrections make it exact: at `nside = 2**29` the argument reaches 7e18,
        !> where a double's relative error of 1e-16 is still far below one ring.
        pure module function hpx_cap_ring(p) result(i)
            integer(int64), intent(in) :: p !! a RING index within the north polar cap.
            integer(int64) :: i !! the ring the pixel lies on, 1-based from the pole.
        end function hpx_cap_ring

        !> RING pixel -> the ring it lies on and its position within that ring.
        pure module subroutine hpx_ring_decompose(nside, p, i, j, nr, shifted)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: p !! RING pixel index, 0-based.
            integer(int64), intent(out) :: i !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(out) :: j !! index within the ring, 0-based.
            integer(int64), intent(out) :: nr !! number of pixels on that ring.
            integer(int64), intent(out) :: shifted !! 1 when centres are offset by half a pixel.
        end subroutine hpx_ring_decompose

        !> Centre of a RING pixel as `(z, phi)`, with no `acos`/`cos` round trip.
        pure module subroutine hpx_pix2zphi_ring(nside, p, z, phi)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: p !! RING pixel index, 0-based.
            real(real64), intent(out) :: z !! cosine of the centre's colatitude.
            real(real64), intent(out) :: phi !! the centre's longitude, radians, in [0, 2*pi).
        end subroutine hpx_pix2zphi_ring

        !> `(ring, index-in-ring)` -> NEST pixel index.
        !>
        !> The half of `pf_ring2nest` that follows the ring decomposition, split out because the
        !> disc walk already knows both coordinates: going through `pf_ring2nest` there would
        !> re-derive them, paying a cap-ring inversion per emitted pixel.
        pure module function hpx_ringij2nest(nside, jr, j) result(ipnest)
            integer(int64), intent(in) :: nside !! resolution parameter.
            integer(int64), intent(in) :: jr !! ring index, 1 .. 4*nside-1, from the north pole.
            integer(int64), intent(in) :: j !! index within the ring, 0-based.
            integer(int64) :: ipnest !! the pixel's NEST index.
        end function hpx_ringij2nest

        !> Largest angular distance from a pixel centre to one of its own corners, in radians.
        !>
        !> This is the margin `pf_query_disc`'s inclusive mode enlarges its radius by, and the
        !> bound that mode publishes. It is attained on the first equatorial ring, whose pixels are
        !> the most elongated, at the corner lying on the quadrant meridian.
        pure module function hpx_max_pixrad(nside) result(r)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad

        !> Largest centre-to-corner angle at `nside`, int32 kind. See the `pf_max_pixrad` generic.
        pure elemental module function hpx_max_pixrad_i32(nside) result(r)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad_i32

        !> Largest centre-to-corner angle at `nside`, int64 kind. See the `pf_max_pixrad` generic.
        pure elemental module function hpx_max_pixrad_i64(nside) result(r)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64) :: r !! the largest centre-to-corner angle, radians.
        end function hpx_max_pixrad_i64

        !> Angular separation of two directions, in radians.
        !>
        !> `atan2(|v1 x v2|, v1.v2)` rather than `acos` of the dot product: accurate to about an ulp
        !> across the whole range, where the `acos` form loses half its digits near 0 and pi. The
        !> inputs need not be unit vectors -- the formula is scale-invariant -- and two parallel
        !> zero vectors give 0 rather than an exception.
        pure module subroutine pf_angdist(vec1, vec2, dist)
            real(real64), intent(in) :: vec1(3) !! first direction; any nonzero length.
            real(real64), intent(in) :: vec2(3) !! second direction; any nonzero length.
            real(real64), intent(out) :: dist !! the angle between them, radians, in [0, pi].
        end subroutine pf_angdist
    end interface

    ! ---- Interfaces: disc queries ----
    !
    ! Implemented in submodule parquet_healpix_query.

    interface
        !> Pixels of a disc, int32 kinds. See `hpx_query_disc_i64` for the contract.
        module subroutine hpx_query_disc_i32(nside, vec, radius, listpix, nlist, scheme, inclusive)
            integer(int32), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0.
            integer(int32), intent(out) :: listpix(:) !! filled from element 1 with 0-based indices.
            integer(int32), intent(out) :: nlist !! how many elements of `listpix` were filled.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_i32

        !> Pixels of a disc: every pixel of the pixelisation lying within `radius` of `vec`.
        !>
        !> **`inclusive = .false.` (the default) has an exact specification**: the pixels whose
        !> CENTRES lie within `radius` of `vec`. Reproducible against any correct implementation
        !> and testable by brute force.
        !>
        !> **`inclusive = .true.` returns the pixels OVERLAPPING the disc**, which every
        !> implementation computes as a bounded superset. The contract this one publishes is: every
        !> overlapping pixel is returned, and no pixel whose centre lies farther than
        !> `radius + max_pixrad(nside)` is returned. That bound is what a caller can rely on -- a
        !> returned pixel is not necessarily an overlapping one, and filtering the result is the
        !> caller's business.
        !>
        !> **Output ordering is ascending pixel index for `PF_HP_RING`, and UNSPECIFIED for
        !> `PF_HP_NEST`.** The ring walk emits ascending RING indices naturally, so that half is
        !> free; the RING-to-NEST conversion destroys monotonicity, and sorting afterwards would
        !> cost more than any caller needs. The NEST order is deterministic for a given input, but
        !> it is not promised and may change -- compare NEST results as sets.
        !>
        !> **`listpix` is filled from element 1; the pixel VALUES it holds are 0-based.** Those are
        !> two different bases and are the pair most easily conflated. `nlist` is the count, so the
        !> result is `listpix(1:nlist)`, and a value of 0 in it means pixel zero rather than an
        !> empty slot.
        !>
        !> **A disc smaller than about 1e-08 radians cannot be resolved, and returns too many
        !> pixels rather than too few.** Membership is decided against `cos(radius)`, whose
        !> distance from 1 is about `radius**2/2` -- so the radius is resolved to a fraction
        !> `2.2e-16/radius**2` of itself, which is 2e-10 at a milliradian and 1 at 1.05e-08 rad
        !> (0.0022 arcsec), where `cos(radius)` is exactly 1.0 and the comparison stops
        !> distinguishing anything. This is a property of a double-precision disc query rather than
        !> of this implementation, and it only becomes reachable at extreme resolution: a
        !> pixel-scale disc is resolvable through `nside = 2**28` and degenerates at `2**29`. Every
        !> `nside` a survey actually uses is many orders away from it.
        !>
        !> **No IEEE exception is raised on any input that passes validation.** That is the point of
        !> this module existing: a caller running under `-ffpe-trap=zero,invalid` needs no guard
        !> around these calls.
        !>
        !> Aborts, with a message naming the routine and the offending value, when `nside` is not a
        !> positive power of two or exceeds this kind's ceiling, when `radius` is negative or NaN,
        !> when `vec` holds a NaN or has zero length, when `scheme` is neither selector, or when
        !> `listpix` is too small to hold the result.
        module subroutine hpx_query_disc_i64(nside, vec, radius, listpix, nlist, scheme, inclusive)
            integer(int64), intent(in) :: nside !! resolution parameter, a positive power of two.
            real(real64), intent(in) :: vec(3) !! direction of the disc centre; any nonzero length.
            real(real64), intent(in) :: radius !! disc radius, radians, >= 0; above pi acts as pi.
            integer(int64), intent(out) :: listpix(:) !! filled from element 1 with 0-based indices.
            integer(int64), intent(out) :: nlist !! how many elements of `listpix` were filled.
            integer, intent(in), optional :: scheme !! `PF_HP_RING` (default) or `PF_HP_NEST`.
            logical, intent(in), optional :: inclusive !! overlap superset; default `.false.`.
        end subroutine hpx_query_disc_i64

        !> The disc walk itself, over `integer(int64)` and writing into whichever output is present.
        !>
        !> Both output arrays are optional and exactly one is passed, which is what lets the two
        !> public kinds share one walk without the int32 form allocating a temporary the size of the
        !> caller's buffer -- the same shape `pf_spatial_index`'s scans use for the same reason.
        module subroutine hpx_query_disc_core(nside, vec, radius, scheme, inclusive, nlist, cap, &
                                              out32, out64)
            integer(int64), intent(in) :: nside !! resolution parameter, already validated.
            real(real64), intent(in) :: vec(3) !! disc centre, already validated, any length.
            real(real64), intent(in) :: radius !! disc radius, radians, already validated.
            integer, intent(in) :: scheme !! `PF_HP_RING` or `PF_HP_NEST`, already validated.
            logical, intent(in) :: inclusive !! whether to return the overlap superset.
            integer(int64), intent(out) :: nlist !! number of pixels written.
            integer(int64), intent(in) :: cap !! capacity of the output array, in elements.
            integer(int32), intent(out), optional :: out32(:) !! int32 output buffer.
            integer(int64), intent(out), optional :: out64(:) !! int64 output buffer.
        end subroutine hpx_query_disc_core

        !> Validates the arguments shared by both `pf_query_disc` kinds, and aborts on any fault.
        module subroutine hpx_check_disc_args(nside, nside_max, vec, radius, scheme)
            integer(int64), intent(in) :: nside !! the resolution parameter to check.
            integer(int64), intent(in) :: nside_max !! the ceiling for the caller's integer kind.
            real(real64), intent(in) :: vec(3) !! the disc centre to check.
            real(real64), intent(in) :: radius !! the disc radius to check.
            integer, intent(in) :: scheme !! the resolved scheme selector to check.
        end subroutine hpx_check_disc_args
    end interface

    ! ---- Interfaces: small shared helpers ----
    !
    ! Implemented in parquet_healpix_core. These are declared rather than contained for the same
    ! linkage reason as the geometry helpers above: a private module-contained procedure has
    ! internal linkage under gfortran, so a submodule calling one compiles and then fails to link.

    interface
        !> Spreads the low 32 bits of `v` into the even bit positions of a 64-bit result.
        !>
        !> The standard five-step Morton spread, and half of the NEST index's construction. Done
        !> with masks rather than a lookup table so that the module carries no data at all -- there
        !> is then nothing for a parallel region to share, and nothing to initialise lazily.
        pure module function hpx_spread_bits(v) result(s)
            integer(int64), intent(in) :: v !! the value whose low 32 bits are spread.
            integer(int64) :: s !! the spread result, occupying the even bits of 64.
        end function hpx_spread_bits

        !> Gathers the even bit positions of `v` back into a contiguous low field.
        !>
        !> The exact inverse of `hpx_spread_bits`.
        pure module function hpx_compact_bits(v) result(c)
            integer(int64), intent(in) :: v !! the interleaved value to compact.
            integer(int64) :: c !! the even bits of `v`, packed into the low half.
        end function hpx_compact_bits

        !> Whether `nside` is a positive power of two at or below `limit`.
        pure module function hpx_nside_ok(nside, limit) result(ok)
            integer(int64), intent(in) :: nside !! the value to test.
            integer(int64), intent(in) :: limit !! the largest acceptable value.
            logical :: ok !! `.true.` when `nside` is usable.
        end function hpx_nside_ok

        !> Renders an integer as its shortest decimal text, for an `error stop` message.
        !>
        !> A subroutine with an allocatable `intent(out)` argument rather than a function returning
        !> `character(len=:), allocatable`, per the project-wide rule: gfortran's codegen for
        !> receiving such a result races on a hidden length temporary when called concurrently.
        module subroutine hpx_itoa(value, text)
            integer(int64), intent(in) :: value !! the number to render.
            character(len=:), allocatable, intent(out) :: text !! its decimal text, unpadded.
        end subroutine hpx_itoa

        !> Renders a real as a short decimal text, for an `error stop` message.
        module subroutine hpx_rtoa(value, text)
            real(real64), intent(in) :: value !! the number to render.
            character(len=:), allocatable, intent(out) :: text !! its text, unpadded.
        end subroutine hpx_rtoa
    end interface

end module parquet_healpix
